// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         dpe.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef DPE_H__
#define DPE_H__



typedef union {
  struct {
    uint32 ZeroLenErr                     :1; 
                                              
                                              
                                              
    uint32 Reserved                       :13;
    uint32 MpegPktArbSt                   :2; 
                                              
    uint32 Reserved2                      :1; 
    uint32 DmaEngineSt                    :3; 
                                              
    uint32 Reserved3                      :1; 
    uint32 DmaCtrlSt                      :3; 
                                              
    uint32 Reserved4                      :2; 
    uint32 FifoHelperFetchSt              :2; 
                                              
    uint32 Reserved5                      :2; 
    uint32 FifoHelperFwdSt                :2; 
                                              
  } Bits;
  uint32 Reg32;
}  DpeDebugStateCodes;


typedef union {
  struct {
    uint32 SwControl                      :1; 
                                              
    uint32 Reserved                       :15;
    uint32 SelHigh                        :8; 
    uint32 SelLow                         :8; 
  } Bits;
  uint32 Reg32;
}  DpeDiagControl;


typedef union {
  struct {
    uint32 DiagOutHigh                    :16;
    uint32 DiagOutLow                     :16;
  } Bits;
  uint32 Reg32;
}  DpeDiagOut;


typedef union {
  struct {
    uint32 Reserved                       :29;
    uint32 MpegMode                       :1; 
                                              
                                              
    uint32 EnableFfeCommand               :1; 
                                              
                                              
    uint32 FfeResetN                      :1; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeDpeConfig;


typedef union {
  struct {
    uint32 Reserved                       :29;
    uint32 Ffe                            :1; 
                                              
                                              
    uint32 Mpeg                           :1; 
                                              
                                              
    uint32 Basic                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeDpeInterrupt;


typedef union {
  struct {
    uint32 Cmd                            :2; 
                                              
                                              
                                              
                                              
    uint32 PktMemSlotNum                  :3; 
                                              
                                              
    uint32 NugMemSlotNum                  :3; 
                                              
                                              
    uint32 BufLen                         :9; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FfePc                          :15;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeCmdWord0;


typedef union {
  struct {
    uint32 MpegCmd                        :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :15;
    uint32 DmaAddr                        :16;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeCmdWord1;


typedef union {
  struct {
    uint32 Reserved                       :31;
    uint32 IntDisable                     :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeCtrl1;


typedef union {
  struct {
    uint32 Reserved                       :29;
    uint32 ForceImemCs                    :1; 
                                              
                                              
                                              
    uint32 ForceDmemCs                    :1; 
                                              
                                              
                                              
    uint32 ForceMmemCs                    :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeCtrl2;


typedef union {
  struct {
    uint32 Reserved                       :2; 
    uint32 Np                             :8; 
                                              
    uint32 Dp                             :11;
                                              
    uint32 Ip                             :11;
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeDebug1;


typedef union {
  struct {
    uint32 Reserved                       :23;
    uint32 State                          :1; 
                                              
    uint32 Sp                             :8; 
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeDebug2;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 Status                         :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeStatus;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 Status                         :8; 
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeStatusMask;


typedef union {
  struct {
    uint32 FifoDepth                      :5; 
                                              
                                              
                                              
    uint32 DpeDmaXferError                :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 PktMemSlotNum                  :3; 
                                              
                                              
    uint32 NugMemSlotNum                  :3; 
                                              
                                              
    uint32 MpegFlowQBufFull               :1; 
                                              
                                              
                                              
    uint32 MpegTsNum                      :3; 
                                              
                                              
                                              
    uint32 FfeReturnValue                 :16;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeFfeStsWord0;


typedef union {
  struct {
    uint32 CmdFifo1Full                   :1; 
                                              
    uint32 CmdFifo1NotEmpty               :1; 
                                              
    uint32 CmdFifo1Underrun               :1; 
                                              
                                              
    uint32 CmdFifo1Overrun                :1; 
                                              
                                              
    uint32 CmdFifo2Full                   :1; 
                                              
    uint32 CmdFifo2NotEmpty               :1; 
                                              
    uint32 CmdFifo2Underrun               :1; 
                                              
                                              
    uint32 CmdFifo2Overrun                :1; 
                                              
                                              
    uint32 StsFifo1Full                   :1; 
                                              
    uint32 StsFifo1NotEmpty               :1; 
                                              
    uint32 StsFifo1Underrun               :1; 
                                              
                                              
    uint32 StsFifo1Overrun                :1; 
                                              
                                              
    uint32 StsFifo2Full                   :1; 
                                              
    uint32 StsFifo2NotEmpty               :1; 
                                              
    uint32 StsFifo2Underrun               :1; 
                                              
                                              
    uint32 StsFifo2Overrun                :1; 
                                              
                                              
    uint32 DmaFifoFull                    :1; 
                                              
    uint32 DmaFifoNotEmpty                :1; 
                                              
    uint32 DmaFifoUnderrun                :1; 
                                              
                                              
    uint32 DmaFifoOverrun                 :1; 
                                              
                                              
    uint32 DmaCtrlFifoFull                :1; 
                                              
    uint32 DmaCtrlFifoNotEmpty            :1; 
                                              
    uint32 DmaCtrlFifoUnderrun            :1; 
                                              
                                              
    uint32 DmaCtrlFifoOverrun             :1; 
                                              
                                              
    uint32 MpegFifoFull                   :1; 
                                              
    uint32 MpegFifoNotEmpty               :1; 
                                              
    uint32 MpegFifoUnderrun               :1; 
                                              
                                              
    uint32 MpegFifoOverrun                :1; 
                                              
                                              
    uint32 Reserved                       :4; 
  } Bits;
  uint32 Reg32;
}  DpeFifoStatus;


typedef union {
  struct {
    uint32 Full                           :1; 
                                              
    uint32 NotEmpty                       :1; 
                                              
    uint32 Underrun                       :1; 
                                              
                                              
    uint32 Overrun                        :1; 
                                              
                                              
    uint32 Reserved                       :7; 
    uint32 Wptr                           :5; 
                                              
                                              
    uint32 Reserved2                      :3; 
    uint32 Rptr                           :5; 
                                              
                                              
    uint32 Reserved3                      :3; 
    uint32 Depth                          :5; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeFifoStatus16wordDeep;


typedef union {
  struct {
    uint32 CmdFifo1Full                   :1; 
                                              
                                              
    uint32 CmdFifo1NotEmpty               :1; 
                                              
                                              
    uint32 CmdFifo1Underrun               :1; 
                                              
                                              
    uint32 CmdFifo1Overrun                :1; 
                                              
                                              
    uint32 CmdFifo2Full                   :1; 
                                              
                                              
    uint32 CmdFifo2NotEmpty               :1; 
                                              
                                              
    uint32 CmdFifo2Underrun               :1; 
                                              
                                              
    uint32 CmdFifo2Overrun                :1; 
                                              
                                              
    uint32 StsFifo1Full                   :1; 
                                              
                                              
    uint32 StsFifo1NotEmpty               :1; 
                                              
                                              
    uint32 StsFifo1Underrun               :1; 
                                              
                                              
    uint32 StsFifo1Overrun                :1; 
                                              
                                              
    uint32 StsFifo2Full                   :1; 
                                              
                                              
    uint32 StsFifo2NotEmpty               :1; 
                                              
                                              
    uint32 StsFifo2Underrun               :1; 
                                              
                                              
    uint32 StsFifo2Overrun                :1; 
                                              
                                              
    uint32 DmaFifoFull                    :1; 
                                              
                                              
    uint32 DmaFifoNotEmpty                :1; 
                                              
                                              
    uint32 DmaFifoUnderrun                :1; 
                                              
                                              
    uint32 DmaFifoOverrun                 :1; 
                                              
                                              
    uint32 DmaCtrlFifoFull                :1; 
                                              
                                              
    uint32 DmaCtrlFifoNotEmpty            :1; 
                                              
                                              
    uint32 DmaCtrlFifoUnderrun            :1; 
                                              
                                              
    uint32 DmaCtrlFifoOverrun             :1; 
                                              
                                              
    uint32 MpegFifoFull                   :1; 
                                              
                                              
    uint32 MpegFifoNotEmpty               :1; 
                                              
                                              
    uint32 MpegFifoUnderrun               :1; 
                                              
                                              
    uint32 MpegFifoOverrun                :1; 
                                              
                                              
    uint32 Reserved                       :4; 
  } Bits;
  uint32 Reg32;
}  DpeFifoStatusMask;


typedef union {
  struct {
    uint32 Enable                         :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :27;
    uint32 MinPacket                      :4; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeMpegFlowConfig;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Pointer                        :14;
                                              
                                              
                                              
    uint32 Reserved2                      :2; 
  } Bits;
  uint32 Reg32;
}  DpeMpegFlowQueueBase;


typedef union {
  struct {
    uint32 Wrap                           :1; 
                                              
                                              
                                              
    uint32 Reserved                       :15;
    uint32 Pointer                        :14;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :2; 
  } Bits;
  uint32 Reg32;
}  DpeMpegFlowQueueHead;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Pointer                        :14;
                                              
                                              
                                              
    uint32 Reserved2                      :2; 
  } Bits;
  uint32 Reg32;
}  DpeMpegFlowQueueLast;


typedef union {
  struct {
    uint32 Wrap                           :1; 
                                              
                                              
                                              
    uint32 Reserved                       :15;
    uint32 Pointer                        :14;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :2; 
  } Bits;
  uint32 Reg32;
}  DpeMpegFlowQueueTail;


typedef union {
  struct {
    uint32 BufFull                        :1; 
                                              
                                              
                                              
    uint32 Reserved                       :15;
    uint32 DropCnt                        :8; 
                                              
                                              
    uint32 Reserved2                      :4; 
    uint32 PacketCount                    :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeMpegFlowStatus;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 FlowBufFull                    :8; 
                                              
                                              
    uint32 StreamPacketOverrun            :8; 
                                              
                                              
    uint32 StreamWordOverrun              :8; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeMpegStatus;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 FlowBufFull                    :8; 
                                              
                                              
    uint32 StreamPacketOverrun            :8; 
                                              
                                              
    uint32 StreamWordOverrun              :8; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeMpegStatusMask;


typedef union {
  struct {
    uint32 Active                         :1; 
                                              
                                              
    uint32 Reserved                       :1; 
    uint32 PacketSlotNum                  :2; 
                                              
                                              
    uint32 Reserved2                      :1; 
    uint32 NuggetSlotNum                  :2; 
                                              
                                              
    uint32 NuggetSlotDontToggle           :1; 
                                              
                                              
                                              
    uint32 PacketWordLength               :6; 
                                              
    uint32 Reserved3                      :2; 
    uint32 FfePc                          :16;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DpeMpegStreamConfig;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 DmaPending                     :1; 
                                              
                                              
                                              
                                              
    uint32 FfePending                     :1; 
                                              
                                              
                                              
                                              
    uint32 PacketReady                    :1; 
                                              
                                              
    uint32 WordReady                      :1; 
                                              
                                              
                                              
    uint32 Reserved2                      :1; 
    uint32 PacketOverrun                  :1; 
                                              
                                              
    uint32 WordOverrun                    :1; 
                                              
                                              
    uint32 OddEvenSlot                    :1; 
                                              
                                              
    uint32 ByteCount                      :8; 
                                              
  } Bits;
  uint32 Reg32;
}  DpeMpegStreamStatus;

typedef struct {
  uint32                              Mem16K[4096];            
}  DpeFfeInsMem;

typedef struct {
  uint32                              Mem1K[256];              
}  DpeFfeNugMem;

typedef struct {
  uint32                              Mem2K[512];              
}  DpeFfePktMem;

typedef struct {
  DpeFfeCmdWord0                      FfeCmdWord0;             
  DpeFfeCmdWord1                      FfeCmdWord1;             
  DpeFfeStsWord0                      FfeStsWord0;             
  uint32                              FfeStsWord1;             
  DpeDpeConfig                        DpeConfig;               
  DpeFifoStatus16wordDeep             CmdFifo1Status;          
  DpeFifoStatus16wordDeep             CmdFifo2Status;          
  DpeFifoStatus16wordDeep             StsFifo1Status;          
  DpeFifoStatus16wordDeep             StsFifo2Status;          
  DpeFifoStatus16wordDeep             DmaFifoStatus;           
  DpeFifoStatus16wordDeep             DmaCtrlFifoStatus;       
  DpeFifoStatus                       FifoStatus;              
  DpeFifoStatusMask                   FifoStatusMask;          
  DpeFifoStatus16wordDeep             MpegFifoStatus;          
  DpeMpegStatus                       MpegStatus;              
  DpeMpegStatusMask                   MpegStatusMask;          
  uint32                              MpegTimestamp;           
  DpeFfeStatus                        FfeStatus;               
  DpeFfeStatusMask                    FfeStatusMask;           
  DpeDpeInterrupt                     DpeInterrupt;            
  DpeDebugStateCodes                  DebugStateCodes;         
  DpeFfeDebug1                        FfeDebug1;               
  DpeFfeDebug2                        FfeDebug2;               
  DpeFfeCtrl1                         FfeCtrl1;                
  DpeFfeCtrl2                         FfeCtrl2;                
  DpeDiagControl                      DiagControl;             
  DpeDiagOut                          DiagOut;                 
}  DpeBasicReg;

typedef struct {
  DpeMpegStreamConfig                 StreamConfig[8];         
  DpeMpegStreamStatus                 StreamStatus[8];         
  DpeMpegFlowConfig                   FlowConfig[8];           
  DpeMpegFlowStatus                   FlowStatus[8];           
  DpeMpegFlowQueueBase                QueueBase[8];            
  DpeMpegFlowQueueLast                QueueLast[8];            
  DpeMpegFlowQueueTail                QueueTail[8];            
  DpeMpegFlowQueueHead                QueueHead[8];            
}  DpeMpegReg;

#endif 



