// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         ds_qdsafe.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef DS_QDSAFE_H__
#define DS_QDSAFE_H__





typedef union {
  struct {
    uint32 Iqadc11bhp                     :1; 
                                              
                                              
    uint32 Iqadc11blp                     :1; 
                                              
                                              
    uint32 PwdnBg                         :1; 
                                              
                                              
    uint32 PdAdc                          :1; 
                                              
                                              
    uint32 ReservedForEco                 :2; 
    uint32 SelinputTest                   :1; 
                                              
                                              
    uint32 Selinput                       :1; 
                                              
                                              
    uint32 ReservedForEco2                :2; 
    uint32 IntQPgaset                     :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ReservedForEco3                :4; 
    uint32 Digctrl                        :1; 
                                              
                                              
    uint32 ExtIf1Pgaset                   :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ExtIf0Pgaset                   :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ReservedForEco4                :1; 
    uint32 ClkReset                       :1; 
                                              
                                              
    uint32 Selclk                         :2; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 SelClkMode                     :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl1;


typedef union {
  struct {
    uint32 DataInSelQ                     :1; 
                                              
    uint32 ReservedForEco                 :3; 
    uint32 ClipThrNQ                      :12;
    uint32 ReservedForEco2                :4; 
    uint32 ClipThrPQ                      :12;
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl10;


typedef union {
  struct {
    uint32 ReservedForEco                 :8; 
    uint32 ClipdI                         :24;
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl11;


typedef union {
  struct {
    uint32 ReservedForEco                 :8; 
    uint32 ClipdQ                         :24;
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl12;


typedef union {
  struct {
    uint32 Afetest                        :1; 
                                              
                                              
                                              
    uint32 AiRst                          :1; 
    uint32 DataRst                        :1; 
    uint32 ReservedForEco                 :2; 
    uint32 GateOffPga                     :11;
                                              
                                              
    uint32 ReservedForEco2                :2; 
    uint32 GateOffAdcAllQ                 :1; 
                                              
                                              
    uint32 GateOffAdcAllI                 :1; 
                                              
                                              
    uint32 GateOffAdc                     :12;
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl2;


typedef union {
  struct {
    uint32 TadjI40uref                    :2; 
                                              
    uint32 TadjI40umdsqt3                 :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI40umdsqt2                 :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI40umdsqt1                 :2; 
                                              
                                              
                                              
                                              
    uint32 ReservedForEco                 :2; 
    uint32 TadjI20uth                     :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI20umdac3                  :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI20umdac2                  :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI20umdac1                  :2; 
                                              
                                              
                                              
                                              
    uint32 ReservedForEco2                :2; 
    uint32 TadjI10uflash                  :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI10urefamp                 :2; 
                                              
                                              
                                              
                                              
    uint32 ReservedForEco3                :2; 
    uint32 VcmCtl                         :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 SjcmCtl                        :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl3;


typedef union {
  struct {
    uint32 TadjI20uls                     :2; 
                                              
                                              
                                              
                                              
    uint32 ReservedForEco                 :1; 
    uint32 TadjI10uvsjref                 :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI10uvcm                    :2; 
                                              
                                              
                                              
                                              
    uint32 TadjI10usjamp                  :2; 
                                              
                                              
                                              
                                              
    uint32 Ptatadj                        :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Ctatadj                        :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ReservedForEco2                :2; 
    uint32 Tstf4                          :1; 
                                              
                                              
    uint32 Tstf3                          :1; 
                                              
                                              
    uint32 Tstf2                          :1; 
                                              
                                              
    uint32 Tstf1                          :1; 
                                              
                                              
    uint32 ReservedForEco3                :1; 
    uint32 TadjOifls                      :2; 
                                              
                                              
                                              
                                              
    uint32 ReservedForEco4                :1; 
    uint32 TadjOqls                       :2; 
                                              
                                              
                                              
                                              
    uint32 ReservedForEco5                :1; 
    uint32 TadjOils                       :2; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl4;


typedef union {
  struct {
    uint32 ReservedForEco                 :24;
    uint32 Nctrl                          :8; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl5;


typedef union {
  struct {
    uint32 ReservedForEco                 :25;
    uint32 Fmt                            :1; 
                                              
                                              
    uint32 SwapIq                         :1; 
                                              
    uint32 Dly1CycleQ                     :1; 
                                              
    uint32 Dly1CycleI                     :1; 
                                              
    uint32 EdgeselQ                       :1; 
                                              
    uint32 EdgeselI                       :1; 
                                              
    uint32 TpInSel                        :1; 
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl6;


typedef union {
  struct {
    uint32 GateOffQData                   :12;
                                              
                                              
    uint32 GateOffIData                   :12;
                                              
                                              
    uint32 ReservedForEco                 :6; 
    uint32 GateOffQDataAll                :1; 
                                              
                                              
    uint32 GateOffIDataAll                :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl7;


typedef union {
  struct {
    uint32 ReservedForEco                 :28;
    uint32 SwapDoutIq                     :1; 
                                              
    uint32 SwapDinIq                      :1; 
                                              
    uint32 Byp                            :1; 
                                              
    uint32 UseBaseband                    :1; 
                                              
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl8;


typedef union {
  struct {
    uint32 DataInSelI                     :1; 
                                              
    uint32 ReservedForEco                 :3; 
    uint32 ClipThrNI                      :12;
    uint32 ReservedForEco2                :4; 
    uint32 ClipThrPI                      :12;
  } Bits;
  uint32 Reg32;
}  DsRelQdsafeAfeCtrl9;

typedef struct {
  DsRelQdsafeAfeCtrl1                 Ctrl1;                   
  DsRelQdsafeAfeCtrl2                 Ctrl2;                   
  DsRelQdsafeAfeCtrl3                 Ctrl3;                   
  DsRelQdsafeAfeCtrl4                 Ctrl4;                   
  DsRelQdsafeAfeCtrl5                 Ctrl5;                   
  DsRelQdsafeAfeCtrl6                 Ctrl6;                   
  DsRelQdsafeAfeCtrl7                 Ctrl7;                   
  DsRelQdsafeAfeCtrl8                 Ctrl8;                   
  DsRelQdsafeAfeCtrl9                 Ctrl9;                   
  DsRelQdsafeAfeCtrl10                Ctrl10;                  
  DsRelQdsafeAfeCtrl11                Ctrl11;                  
  DsRelQdsafeAfeCtrl12                Ctrl12;                  
  uint8                               Pad0[0x8];
  uint32                              Spare;                   
}  DsRelQdsafeRegisters;

#endif 



