// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         ds_tuner.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef DS_TUNER_H__
#define DS_TUNER_H__


enum DS_REL_TUNER_on_off {
  DS_REL_TUNER_on_off_on=0x1,                        
  DS_REL_TUNER_on_off_off=0x0,                       
};

enum DS_REL_TUNER_enable_disable {
  DS_REL_TUNER_enable_disable_enable=0x1,            
  DS_REL_TUNER_enable_disable_disable=0x0,           
};


typedef union {
  struct {
    uint32 Ds0Irq1Iclr                    :1; 
    uint32 Ds0Irq2Iclr                    :1; 
    uint32 Ds1Irq1Iclr                    :1; 
    uint32 Ds1Irq2Iclr                    :1; 
    uint32 Ds2Irq1Iclr                    :1; 
    uint32 Ds2Irq2Iclr                    :1; 
    uint32 Ds3Irq1Iclr                    :1; 
    uint32 Ds3Irq2Iclr                    :1; 
    uint32 Ds4Irq1Iclr                    :1; 
    uint32 Ds4Irq2Iclr                    :1; 
    uint32 Ds5Irq1Iclr                    :1; 
    uint32 Ds5Irq2Iclr                    :1; 
    uint32 Ds6Irq1Iclr                    :1; 
    uint32 Ds6Irq2Iclr                    :1; 
    uint32 Ds7Irq1Iclr                    :1; 
    uint32 Ds7Irq2Iclr                    :1; 
    uint32 Reserved                       :16;
  } Bits;
  uint32 Reg32;
}  DsRelTunerDsCoreIrqclr;


typedef union {
  struct {
    uint32 Ds0Irq1Imclr                   :1; 
    uint32 Ds0Irq2Imclr                   :1; 
    uint32 Ds1Irq1Imclr                   :1; 
    uint32 Ds1Irq2Imclr                   :1; 
    uint32 Ds2Irq1Imclr                   :1; 
    uint32 Ds2Irq2Imclr                   :1; 
    uint32 Ds3Irq1Imclr                   :1; 
    uint32 Ds3Irq2Imclr                   :1; 
    uint32 Ds4Irq1Imclr                   :1; 
    uint32 Ds4Irq2Imclr                   :1; 
    uint32 Ds5Irq1Imclr                   :1; 
    uint32 Ds5Irq2Imclr                   :1; 
    uint32 Ds6Irq1Imclr                   :1; 
    uint32 Ds6Irq2Imclr                   :1; 
    uint32 Ds7Irq1Imclr                   :1; 
    uint32 Ds7Irq2Imclr                   :1; 
    uint32 Reserved                       :16;
  } Bits;
  uint32 Reg32;
}  DsRelTunerDsCoreIrqmclr;


typedef union {
  struct {
    uint32 Ds0Irq1Imset                   :1; 
    uint32 Ds0Irq2Imset                   :1; 
    uint32 Ds1Irq1Imset                   :1; 
    uint32 Ds1Irq2Imset                   :1; 
    uint32 Ds2Irq1Imset                   :1; 
    uint32 Ds2Irq2Imset                   :1; 
    uint32 Ds3Irq1Imset                   :1; 
    uint32 Ds3Irq2Imset                   :1; 
    uint32 Ds4Irq1Imset                   :1; 
    uint32 Ds4Irq2Imset                   :1; 
    uint32 Ds5Irq1Imset                   :1; 
    uint32 Ds5Irq2Imset                   :1; 
    uint32 Ds6Irq1Imset                   :1; 
    uint32 Ds6Irq2Imset                   :1; 
    uint32 Ds7Irq1Imset                   :1; 
    uint32 Ds7Irq2Imset                   :1; 
    uint32 Reserved                       :16;
  } Bits;
  uint32 Reg32;
}  DsRelTunerDsCoreIrqmset;


typedef union {
  struct {
    uint32 Ds0Irq1Imsk                    :1; 
    uint32 Ds0Irq2Imsk                    :1; 
    uint32 Ds1Irq1Imsk                    :1; 
    uint32 Ds1Irq2Imsk                    :1; 
    uint32 Ds2Irq1Imsk                    :1; 
    uint32 Ds2Irq2Imsk                    :1; 
    uint32 Ds3Irq1Imsk                    :1; 
    uint32 Ds3Irq2Imsk                    :1; 
    uint32 Ds4Irq1Imsk                    :1; 
    uint32 Ds4Irq2Imsk                    :1; 
    uint32 Ds5Irq1Imsk                    :1; 
    uint32 Ds5Irq2Imsk                    :1; 
    uint32 Ds6Irq1Imsk                    :1; 
    uint32 Ds6Irq2Imsk                    :1; 
    uint32 Ds7Irq1Imsk                    :1; 
    uint32 Ds7Irq2Imsk                    :1; 
    uint32 Reserved                       :16;
  } Bits;
  uint32 Reg32;
}  DsRelTunerDsCoreIrqmsk;


typedef union {
  struct {
    uint32 Ds0Irq1Iset                    :1; 
    uint32 Ds0Irq2Iset                    :1; 
    uint32 Ds1Irq1Iset                    :1; 
    uint32 Ds1Irq2Iset                    :1; 
    uint32 Ds2Irq1Iset                    :1; 
    uint32 Ds2Irq2Iset                    :1; 
    uint32 Ds3Irq1Iset                    :1; 
    uint32 Ds3Irq2Iset                    :1; 
    uint32 Ds4Irq1Iset                    :1; 
    uint32 Ds4Irq2Iset                    :1; 
    uint32 Ds5Irq1Iset                    :1; 
    uint32 Ds5Irq2Iset                    :1; 
    uint32 Ds6Irq1Iset                    :1; 
    uint32 Ds6Irq2Iset                    :1; 
    uint32 Ds7Irq1Iset                    :1; 
    uint32 Ds7Irq2Iset                    :1; 
    uint32 Reserved                       :16;
  } Bits;
  uint32 Reg32;
}  DsRelTunerDsCoreIrqset;


typedef union {
  struct {
    uint32 Ds0Irq1Is                      :1; 
                                              
                                              
    uint32 Ds0Irq2Is                      :1; 
                                              
                                              
    uint32 Ds1Irq1Is                      :1; 
                                              
                                              
    uint32 Ds1Irq2Is                      :1; 
                                              
                                              
    uint32 Ds2Irq1Is                      :1; 
                                              
                                              
    uint32 Ds2Irq2Is                      :1; 
                                              
                                              
    uint32 Ds3Irq1Is                      :1; 
                                              
                                              
    uint32 Ds3Irq2Is                      :1; 
                                              
                                              
    uint32 Ds4Irq1Is                      :1; 
                                              
                                              
    uint32 Ds4Irq2Is                      :1; 
                                              
                                              
    uint32 Ds5Irq1Is                      :1; 
                                              
                                              
    uint32 Ds5Irq2Is                      :1; 
                                              
                                              
    uint32 Ds6Irq1Is                      :1; 
                                              
                                              
    uint32 Ds6Irq2Is                      :1; 
                                              
                                              
    uint32 Ds7Irq1Is                      :1; 
                                              
                                              
    uint32 Ds7Irq2Is                      :1; 
                                              
                                              
    uint32 Reserved                       :16;
  } Bits;
  uint32 Reg32;
}  DsRelTunerDsCoreIrqsts;


typedef union {
  struct {
    uint32 Tuner0QdsafeClpdtrIIclr        :1; 
    uint32 Tuner0QdsafeClpdtrQIclr        :1; 
    uint32 Tuner0VafeClpdtrIIclr          :1; 
    uint32 Tuner0VafeClpdtrQIclr          :1; 
    uint32 Tuner1QdsafeClpdtrIIclr        :1; 
    uint32 Tuner1QdsafeClpdtrQIclr        :1; 
    uint32 Tuner1VafeClpdtrIIclr          :1; 
    uint32 Tuner1VafeClpdtrQIclr          :1; 
    uint32 Tuner0QdsafeFifoIclr           :1; 
    uint32 Tuner0VafeFifoIclr             :1; 
    uint32 Tuner1QdsafeFifoIclr           :1; 
    uint32 Tuner1VafeFifoIclr             :1; 
    uint32 Chnz0AgfIclr                   :1; 
    uint32 Chnz1AgfIclr                   :1; 
    uint32 Chnz2AgfIclr                   :1; 
    uint32 Chnz3AgfIclr                   :1; 
    uint32 Chnz4AgfIclr                   :1; 
    uint32 Chnz5AgfIclr                   :1; 
    uint32 Chnz6AgfIclr                   :1; 
    uint32 Chnz7AgfIclr                   :1; 
    uint32 Chnz8AgfIclr                   :1; 
    uint32 Chnz9AgfIclr                   :1; 
    uint32 Chnz10AgfIclr                  :1; 
    uint32 Chnz11AgfIclr                  :1; 
    uint32 Reserved                       :8; 
  } Bits;
  uint32 Reg32;
}  DsRelTunerIrqclr;


typedef union {
  struct {
    uint32 Tuner0QdsafeClpdtrIImclr       :1; 
    uint32 Tuner0QdsafeClpdtrQImclr       :1; 
    uint32 Tuner0VafeClpdtrIImclr         :1; 
    uint32 Tuner0VafeClpdtrQImclr         :1; 
    uint32 Tuner1QdsafeClpdtrIImclr       :1; 
    uint32 Tuner1QdsafeClpdtrQImclr       :1; 
    uint32 Tuner1VafeClpdtrIImclr         :1; 
    uint32 Tuner1VafeClpdtrQImclr         :1; 
    uint32 Tuner0QdsafeFifoImclr          :1; 
    uint32 Tuner0VafeFifoImclr            :1; 
    uint32 Tuner1QdsafeFifoImclr          :1; 
    uint32 Tuner1VafeFifoImclr            :1; 
    uint32 Chnz0AgfImclr                  :1; 
    uint32 Chnz1AgfImclr                  :1; 
    uint32 Chnz2AgfImclr                  :1; 
    uint32 Chnz3AgfImclr                  :1; 
    uint32 Chnz4AgfImclr                  :1; 
    uint32 Chnz5AgfImclr                  :1; 
    uint32 Chnz6AgfImclr                  :1; 
    uint32 Chnz7AgfImclr                  :1; 
    uint32 Chnz8AgfImclr                  :1; 
    uint32 Chnz9AgfImclr                  :1; 
    uint32 Chnz10AgfImclr                 :1; 
    uint32 Chnz11AgfImclr                 :1; 
    uint32 Reserved                       :8; 
  } Bits;
  uint32 Reg32;
}  DsRelTunerIrqmclr;


typedef union {
  struct {
    uint32 Tuner0QdsafeClpdtrIImset       :1; 
    uint32 Tuner0QdsafeClpdtrQImset       :1; 
    uint32 Tuner0VafeClpdtrIImset         :1; 
    uint32 Tuner0VafeClpdtrQImset         :1; 
    uint32 Tuner1QdsafeClpdtrIImset       :1; 
    uint32 Tuner1QdsafeClpdtrQImset       :1; 
    uint32 Tuner1VafeClpdtrIImset         :1; 
    uint32 Tuner1VafeClpdtrQImset         :1; 
    uint32 Tuner0QdsafeFifoImset          :1; 
    uint32 Tuner0VafeFifoImset            :1; 
    uint32 Tuner1QdsafeFifoImset          :1; 
    uint32 Tuner1VafeFifoImset            :1; 
    uint32 Chnz0AgfImset                  :1; 
    uint32 Chnz1AgfImset                  :1; 
    uint32 Chnz2AgfImset                  :1; 
    uint32 Chnz3AgfImset                  :1; 
    uint32 Chnz4AgfImset                  :1; 
    uint32 Chnz5AgfImset                  :1; 
    uint32 Chnz6AgfImset                  :1; 
    uint32 Chnz7AgfImset                  :1; 
    uint32 Chnz8AgfImset                  :1; 
    uint32 Chnz9AgfImset                  :1; 
    uint32 Chnz10AgfImset                 :1; 
    uint32 Chnz11AgfImset                 :1; 
    uint32 Reserved                       :8; 
  } Bits;
  uint32 Reg32;
}  DsRelTunerIrqmset;


typedef union {
  struct {
    uint32 Tuner0QdsafeClpdtrIImsk        :1; 
    uint32 Tuner0QdsafeClpdtrQImsk        :1; 
    uint32 Tuner0VafeClpdtrIImsk          :1; 
    uint32 Tuner0VafeClpdtrQImsk          :1; 
    uint32 Tuner1QdsafeClpdtrIImsk        :1; 
    uint32 Tuner1QdsafeClpdtrQImsk        :1; 
    uint32 Tuner1VafeClpdtrIImsk          :1; 
    uint32 Tuner1VafeClpdtrQImsk          :1; 
    uint32 Tuner0QdsafeFifoImsk           :1; 
    uint32 Tuner0VafeFifoImsk             :1; 
    uint32 Tuner1QdsafeFifoImsk           :1; 
    uint32 Tuner1VafeFifoImsk             :1; 
    uint32 Chnz0AgfImsk                   :1; 
    uint32 Chnz1AgfImsk                   :1; 
    uint32 Chnz2AgfImsk                   :1; 
    uint32 Chnz3AgfImsk                   :1; 
    uint32 Chnz4AgfImsk                   :1; 
    uint32 Chnz5AgfImsk                   :1; 
    uint32 Chnz6AgfImsk                   :1; 
    uint32 Chnz7AgfImsk                   :1; 
    uint32 Chnz8AgfImsk                   :1; 
    uint32 Chnz9AgfImsk                   :1; 
    uint32 Chnz10AgfImsk                  :1; 
    uint32 Chnz11AgfImsk                  :1; 
    uint32 Reserved                       :8; 
  } Bits;
  uint32 Reg32;
}  DsRelTunerIrqmsk;


typedef union {
  struct {
    uint32 Tuner0QdsafeClpdtrIIset        :1; 
    uint32 Tuner0QdsafeClpdtrQIset        :1; 
    uint32 Tuner0VafeClpdtrIIset          :1; 
    uint32 Tuner0VafeClpdtrQIset          :1; 
    uint32 Tuner1QdsafeClpdtrIIset        :1; 
    uint32 Tuner1QdsafeClpdtrQIset        :1; 
    uint32 Tuner1VafeClpdtrIIset          :1; 
    uint32 Tuner1VafeClpdtrQIset          :1; 
    uint32 Tuner0QdsafeFifoIset           :1; 
    uint32 Tuner0VafeFifoIset             :1; 
    uint32 Tuner1QdsafeFifoIset           :1; 
    uint32 Tuner1VafeFifoIset             :1; 
    uint32 Chnz0AgfIset                   :1; 
    uint32 Chnz1AgfIset                   :1; 
    uint32 Chnz2AgfIset                   :1; 
    uint32 Chnz3AgfIset                   :1; 
    uint32 Chnz4AgfIset                   :1; 
    uint32 Chnz5AgfIset                   :1; 
    uint32 Chnz6AgfIset                   :1; 
    uint32 Chnz7AgfIset                   :1; 
    uint32 Chnz8AgfIset                   :1; 
    uint32 Chnz9AgfIset                   :1; 
    uint32 Chnz10AgfIset                  :1; 
    uint32 Chnz11AgfIset                  :1; 
    uint32 Reserved                       :8; 
  } Bits;
  uint32 Reg32;
}  DsRelTunerIrqset;


typedef union {
  struct {
    uint32 Tuner0QdsafeClpdtrIIs          :1; 
                                              
                                              
                                              
    uint32 Tuner0QdsafeClpdtrQIs          :1; 
                                              
                                              
                                              
    uint32 Tuner0VafeClpdtrIIs            :1; 
                                              
                                              
                                              
    uint32 Tuner0VafeClpdtrQIs            :1; 
                                              
                                              
                                              
    uint32 Tuner1QdsafeClpdtrIIs          :1; 
                                              
                                              
                                              
    uint32 Tuner1QdsafeClpdtrQIs          :1; 
                                              
                                              
                                              
    uint32 Tuner1VafeClpdtrIIs            :1; 
                                              
                                              
                                              
    uint32 Tuner1VafeClpdtrQIs            :1; 
                                              
                                              
                                              
    uint32 Tuner0QdsafeFifoIs             :1; 
                                              
                                              
    uint32 Tuner0VafeFifoIs               :1; 
                                              
                                              
    uint32 Tuner1QdsafeFifoIs             :1; 
                                              
                                              
    uint32 Tuner1VafeFifoIs               :1; 
                                              
                                              
    uint32 Chnz0AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz1AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz2AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz3AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz4AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz5AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz6AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz7AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz8AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz9AgfIs                     :1; 
                                              
                                              
                                              
    uint32 Chnz10AgfIs                    :1; 
                                              
                                              
                                              
    uint32 Chnz11AgfIs                    :1; 
                                              
                                              
                                              
    uint32 Reserved                       :8; 
  } Bits;
  uint32 Reg32;
}  DsRelTunerIrqsts;


typedef union {
  struct {
    uint32 ReservedForEco                 :15;
    uint32 ClkTpSelect                    :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Core0TpSelect                  :4; 
                                              
                                              
    uint32 Core1TpSelect                  :4; 
                                              
                                              
    uint32 TopTpSelect                    :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 TpinEn                         :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelTunerTunerTopCntl0;


typedef union {
  struct {
    uint32 ReservedForEco                 :24;
    uint32 TunerTopVafe1ExtMode           :1; 
                                              
                                              
                                              
                                              
    uint32 TunerTopVafe0ExtMode           :1; 
                                              
                                              
                                              
                                              
    uint32 TunerTopQdsafe2FsMode          :1; 
                                              
                                              
    uint32 TunerTopVafe4FsMode            :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ReservedForEco2                :2; 
    uint32 TunerTopCtrlReset              :1; 
                                              
                                              
                                              
    uint32 TunerTopDataReset              :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelTunerTunerTopCntl1;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 T1MixerPllPopcapStatus         :1; 
                                              
                                              
    uint32 T1MixerPllLockStatus           :1; 
                                              
                                              
    uint32 T0MixerPllPopcapStatus         :1; 
                                              
                                              
    uint32 T0MixerPllLockStatus           :1; 
                                              
                                              
    uint32 RefPllLockStatus               :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelTunerTunerTopStatus;

typedef struct {
  DsRelTunerTunerTopCntl0             TunerTopCntl0;           
  DsRelTunerTunerTopCntl1             TunerTopCntl1;           
  DsRelTunerTunerTopStatus            TunerTopStatus;          
  DsRelTunerIrqsts                    Irqsts;                  
  DsRelTunerIrqset                    Irqset;                  
  DsRelTunerIrqclr                    Irqclr;                  
  DsRelTunerIrqmsk                    Irqmsk;                  
  DsRelTunerIrqmset                   Irqmset;                 
  DsRelTunerIrqmclr                   Irqmclr;                 
  DsRelTunerDsCoreIrqsts              DsCoreIrqsts;            
  DsRelTunerDsCoreIrqset              DsCoreIrqset;            
  DsRelTunerDsCoreIrqclr              DsCoreIrqclr;            
  DsRelTunerDsCoreIrqmsk              DsCoreIrqmsk;            
  DsRelTunerDsCoreIrqmset             DsCoreIrqmset;           
  DsRelTunerDsCoreIrqmclr             DsCoreIrqmclr;           
  uint32                              Tuner0R00;               
  uint32                              Tuner1R00;               
}  DsRelTunerRegisters;

#endif 



