// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         ds_tuner_core_gen.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef DS_TUNER_CORE_GEN_H__
#define DS_TUNER_CORE_GEN_H__


enum DS_REL_TUNER_CORE_GEN_on_off {
  DS_REL_TUNER_CORE_GEN_on_off_on=0x1,               
  DS_REL_TUNER_CORE_GEN_on_off_off=0x0,              
};

enum DS_REL_TUNER_CORE_GEN_enable_disable {
  DS_REL_TUNER_CORE_GEN_enable_disable_enable=0x1,   
  DS_REL_TUNER_CORE_GEN_enable_disable_disable=0x0,  
};


typedef union {
  struct {
    uint32 TunLowPwr                      :1; 
                                              
                                              
    uint32 ReservedForEco                 :3; 
    uint32 VdfSkip1Cycle                  :1; 
                                              
                                              
    uint32 ReservedForEco2                :3; 
    uint32 Fcw                            :24;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelTunerCoreGenCtrl0;


typedef union {
  struct {
    uint32 Reserved                       :7; 
    uint32 TpinIqSel                      :1; 
    uint32 Reserved2                      :16;
    uint32 IqampShift                     :4; 
                                              
    uint32 Reserved3                      :1; 
    uint32 IqampByp                       :1; 
                                              
                                              
    uint32 IqampFreeze                    :1; 
                                              
                                              
                                              
    uint32 IqRst                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DsRelTunerCoreGenIqamp;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 IqphsShift                     :4; 
                                              
    uint32 Reserved2                      :1; 
    uint32 IqphsByp                       :1; 
                                              
                                              
    uint32 IqphsFreeze                    :1; 
                                              
                                              
                                              
    uint32 Reserved3                      :1; 
  } Bits;
  uint32 Reg32;
}  DsRelTunerCoreGenIqphs;

typedef struct {
  DsRelTunerCoreGenCtrl0              Ctrl0;                   
  uint8                               Pad0[0xc];
  DsRelTunerCoreGenIqamp              Iqamp;                   
  DsRelTunerCoreGenIqphs              Iqphs;                   
  uint32                              Iqampi;                  
  uint32                              Iqphsi;                  
}  DsRelTunerCoreGenRegisters;

#endif 



