// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         dtp.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef DTP_H__
#define DTP_H__



typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 ClstrVld                       :1; 
                                              
    uint32 ClstrPtr                       :7; 
  } Bits;
  uint32 Reg32;
}  DtpClstrMem;


typedef union {
  struct {
    uint32 Reserved                       :7; 
    uint32 DsidState                      :3; 
    uint32 SccPend                        :1; 
    uint32 Scc                            :1; 
    uint32 Dsid                           :20;
  } Bits;
  uint32 Reg32;
}  DtpDsidState0;


typedef union {
  struct {
    uint32 Reserved                       :1; 
    uint32 Rws                            :7; 
                                              
    uint32 Reserved2                      :1; 
    uint32 NxtModUpperBits                :7; 
                                              
    uint32 NxtExpPsn                      :16;
  } Bits;
  uint32 Reg32;
}  DtpDsidState2;


typedef union {
  struct {
    uint32 Reserved                       :6; 
    uint32 RsqWarnThrsh                   :5; 
    uint32 RsqWaitTime                    :5; 
    uint32 HwRsvdLrnHighQPsn              :16;
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsidState3;


typedef union {
  struct {
    uint32 Reserved                       :15;
    uint32 SccHoldTimeTc                  :17;
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsidState4;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 SccHoldTime                    :16;
  } Bits;
  uint32 Reg32;
}  DtpDsidState5;


typedef union {
  struct {
    uint32 Reserved                       :15;
    uint32 NewRws                         :7; 
                                              
    uint32 NewWarnTime                    :5; 
                                              
    uint32 NewWaitTime                    :5; 
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsidState7;


typedef union {
  struct {
    uint32 TmoutMem                       :4; 
    uint32 RldMem                         :4; 
    uint32 ClstrMem                       :4; 
    uint32 SaMem                          :4; 
    uint32 Tagc                           :4; 
    uint32 Tag                            :4; 
    uint32 Stats                          :4; 
    uint32 State                          :4; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmBistTm0;


typedef union {
  struct {
    uint32 Reserved                       :30;
    uint32 ClstrFreeFifoMem               :2; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmBistTm1;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmClrTm1K;


typedef union {
  struct {
    uint32 Reserved                       :22;
    uint32 EnDynClstrAlloc                :1; 
                                              
                                              
    uint32 FreezeMsCntr                   :1; 
                                              
                                              
    uint32 RstMsCntr                      :1; 
                                              
    uint32 Reserved2                      :2; 
    uint32 RstNmCntr                      :1; 
    uint32 FreePoolNum                    :2; 
                                              
    uint32 Reserved3                      :2; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmCtrl;


typedef union {
  struct {
    uint32 DiagHighCap                    :16;
    uint32 DiagLowCap                     :16;
  } Bits;
  uint32 Reg32;
}  DtpDsrmDiagCap;


typedef union {
  struct {
    uint32 DiagHighCmp                    :16;
                                              
    uint32 DiagLowCmp                     :16;
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmDiagCmp;


typedef union {
  struct {
    uint32 UseIntDiagHigh                 :1; 
    uint32 DiagHighMode                   :3; 
    uint32 Reserved                       :4; 
    uint32 DiagHighSel                    :8; 
    uint32 UseIntDiagLow                  :1; 
    uint32 DiagLowMode                    :3; 
    uint32 Reserved2                      :4; 
    uint32 DiagLowSel                     :8; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDiagCtrl;


typedef union {
  struct {
    uint32 DiagHighMask                   :16;
                                              
    uint32 DiagLowMask                    :16;
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmDiagMask;


typedef union {
  struct {
    uint32 DiagHighRslt                   :16;
    uint32 DiagLowRslt                    :16;
  } Bits;
  uint32 Reg32;
}  DtpDsrmDiagRslt;


typedef union {
  struct {
    uint32 Reserved                       :15;
    uint32 DiagHighCaptureValid           :1; 
                                              
    uint32 Reserved2                      :15;
    uint32 DiagLowCaptureValid            :1; 
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmDiagStat;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 DiagHighMatchMask              :1; 
    uint32 DiagLowMatchMask               :1; 
    uint32 FsmErrMask                     :1; 
    uint32 ArbTimeoutErrMask              :1; 
    uint32 TknStatusMask                  :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDiagcapMask;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDsidAssigned;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDsidChgSts;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDsidClusterDirty;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDsidLearning;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDsidSccPending;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmDsidTagcDirty;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 DiagHighMatch                  :1; 
    uint32 DiagLowMatch                   :1; 
    uint32 FsmErr                         :1; 
    uint32 ArbTimeoutErr                  :1; 
    uint32 TknStatus                      :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmErrcapStat;


typedef union {
  struct {
    uint32 Reserved                       :25;
    uint32 WrVal                          :7; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmFreeClstrFifo;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 Level                          :8; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmFreeClstrFifoLevel;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 LowWmk                         :8; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmFreeClstrFifoLowWmk;


typedef union {
  struct {
    uint32 Reserved                       :23;
    uint32 TknacsDisable                  :1; 
    uint32 TmoutDisable                   :1; 
    uint32 RldDisable                     :1; 
    uint32 SparseAryDisable               :1; 
    uint32 ClstrDisable                   :1; 
    uint32 TagDisable                     :1; 
    uint32 UpdateDisable                  :1; 
    uint32 TkninDisable                   :1; 
    uint32 StioDisable                    :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmFsmCtrl;


typedef union {
  struct {
    uint32 Reserved                       :19;
    uint32 UpdtErr0                       :1; 
    uint32 TkninErr0                      :1; 
    uint32 TknacsErr0                     :1; 
    uint32 SaErr0                         :1; 
    uint32 TmoutErr0                      :1; 
    uint32 RldErr0                        :1; 
    uint32 ClstrErr0                      :1; 
    uint32 TagErr2                        :1; 
    uint32 TagErr1                        :1; 
    uint32 TagErr0                        :1; 
    uint32 StioErr2                       :1; 
    uint32 StioErr1                       :1; 
    uint32 StioErr0                       :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmFsmErr;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 DiagHighMatchMask              :1; 
    uint32 DiagLowMatchMask               :1; 
    uint32 FsmErrMask                     :1; 
    uint32 ArbTimeoutErrMask              :1; 
    uint32 TknStatusMask                  :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmIntMask;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 DiagHighMatch                  :1; 
    uint32 DiagLowMatch                   :1; 
    uint32 FsmErr                         :1; 
    uint32 ArbTimeoutErr                  :1; 
    uint32 TknStatus                      :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmIntStat;


typedef union {
  struct {
    uint32 Reserved                       :20;
    uint32 Count                          :12;
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmPowbCnt;


typedef union {
  struct {
    uint32 Reserved                       :20;
    uint32 Tc                             :12;
                                              
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmPowbTc;


typedef union {
  struct {
    uint32 Reserved                       :23;
    uint32 Tc                             :9; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmPrescaleTc;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 Execute                        :1; 
                                              
    uint32 Cmd                            :4; 
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmStCmd;


typedef union {
  struct {
    uint32 Valid                          :1; 
    uint32 LogDsid                        :4; 
    uint32 Reserved                       :5; 
    uint32 LearningActive                 :1; 
    uint32 ReseqTknAvail                  :1; 
    uint32 Tm1kActive                     :1; 
                                              
    uint32 NxtExpPsn                      :1; 
    uint32 RldActive                      :1; 
    uint32 TimeoutActive                  :1; 
    uint32 Reserved2                      :6; 
    uint32 BadTkn                         :1; 
    uint32 NullSeqPkt                     :1; 
    uint32 WarnThrsh                      :1; 
    uint32 DiffScc                        :1; 
    uint32 Reserved3                      :1; 
    uint32 OutsideWdw                     :1; 
    uint32 BadScc                         :1; 
    uint32 BadCh                          :1; 
    uint32 DsidMatch                      :1; 
    uint32 NoDsidMatch                    :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmStRslt;


typedef union {
  struct {
    uint32 Reserved                       :28;
    uint32 Execute                        :1; 
                                              
    uint32 Cmd                            :3; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmStUpdtCmd;


typedef union {
  struct {
    uint32 Reserved                       :1; 
    uint32 LogDsid                        :4; 
    uint32 Reserved2                      :17;
    uint32 BadTkn                         :1; 
    uint32 NullSeqPkt                     :1; 
    uint32 WarnThrsh                      :1; 
    uint32 DiffScc                        :1; 
    uint32 DupPsn                         :1; 
    uint32 OutsideWdw                     :1; 
    uint32 BadScc                         :1; 
    uint32 BadCh                          :1; 
    uint32 DsidMatch                      :1; 
    uint32 NoDsidMatch                    :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmStUpdtData;


typedef union {
  struct {
    uint32 Reserved                       :18;
    uint32 TmoutMemErr                    :1; 
    uint32 TmoutEngErr                    :1; 
    uint32 RldMemErr                      :1; 
    uint32 RldEngErr                      :1; 
    uint32 SaMemErr                       :1; 
    uint32 SaEngErr                       :1; 
    uint32 ClstrMemErr                    :1; 
    uint32 ClstrEngErr                    :1; 
    uint32 TagcMemErr                     :1; 
    uint32 TagMemErr                      :1; 
    uint32 TagEngErr                      :1; 
    uint32 UpdateEngErr                   :1; 
    uint32 StatsMemErr                    :1; 
    uint32 StateMemErr                    :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTimeoutErr;


typedef union {
  struct {
    uint32 Reserved                       :20;
    uint32 TimeoutVal                     :12;
  } Bits;
  uint32 Reg32;
}  DtpDsrmTimeoutVal;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 Psn                            :16;
    uint32 Execute                        :1; 
                                              
    uint32 Cmd                            :3; 
    uint32 LogDsid                        :4; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknAcsCmd;


typedef union {
  struct {
    uint32 Valid                          :1; 
    uint32 Reserved                       :1; 
    uint32 Token                          :30;
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknAcsRslt;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Dsid15                         :1; 
    uint32 Dsid14                         :1; 
    uint32 Dsid13                         :1; 
    uint32 Dsid12                         :1; 
    uint32 Dsid11                         :1; 
    uint32 Dsid10                         :1; 
    uint32 Dsid9                          :1; 
    uint32 Dsid8                          :1; 
    uint32 Dsid7                          :1; 
    uint32 Dsid6                          :1; 
    uint32 Dsid5                          :1; 
    uint32 Dsid4                          :1; 
    uint32 Dsid3                          :1; 
    uint32 Dsid2                          :1; 
    uint32 Dsid1                          :1; 
    uint32 Dsid0                          :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknAcsSts;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 TknQueued                      :1; 
    uint32 Tm1kActive                     :1; 
    uint32 RldActive                      :1; 
    uint32 TimeoutActive                  :1; 
    uint32 RsqTknAvail                    :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknAcsStsDsid;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 TknQueued                      :1; 
    uint32 Tm1kActive                     :1; 
    uint32 RldActive                      :1; 
    uint32 TimeoutActive                  :1; 
    uint32 RsqTknAvail                    :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknAcsStsMsk;


typedef union {
  struct {
    uint32 Reserved                       :7; 
    uint32 Ch                             :5; 
    uint32 Reserved2                      :4; 
    uint32 Psn                            :16;
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknData0;


typedef union {
  struct {
    uint32 Reserved                       :11;
    uint32 Scc                            :1; 
    uint32 Dsid                           :20;
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknData1;


typedef union {
  struct {
    uint32 Reserved                       :28;
    uint32 Execute                        :1; 
                                              
    uint32 Cmd                            :3; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknInCmd;


typedef union {
  struct {
    uint32 Valid                          :1; 
    uint32 LogDsid                        :4; 
    uint32 Reserved                       :5; 
    uint32 LearningActive                 :1; 
    uint32 ReseqTknAvail                  :1; 
    uint32 Tm1kActive                     :1; 
                                              
    uint32 NxtExpPsn                      :1; 
    uint32 RldActive                      :1; 
    uint32 TimeoutActive                  :1; 
    uint32 Reserved2                      :6; 
    uint32 BadTkn                         :1; 
    uint32 NullSeqPkt                     :1; 
    uint32 WarnThrsh                      :1; 
    uint32 DiffScc                        :1; 
    uint32 DupPsn                         :1; 
    uint32 OutsideWdw                     :1; 
    uint32 BadScc                         :1; 
    uint32 BadCh                          :1; 
    uint32 DsidMatch                      :1; 
    uint32 NoDsidMatch                    :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknInRslt;


typedef union {
  struct {
    uint32 Reserved                       :9; 
    uint32 ModPsn                         :7; 
    uint32 Reserved2                      :1; 
    uint32 NxtModPsn                      :15;
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknLuData1;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 PktIsNxtExp                    :1; 
    uint32 Rws                            :7; 
    uint32 Reserved2                      :1; 
    uint32 Log2rws                        :3; 
    uint32 LogDsid                        :4; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmTknLuRslt;


typedef union {
  struct {
    uint32 Reserved                       :23;
    uint32 Count                          :9; 
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmTwominCnt;


typedef union {
  struct {
    uint32 Reserved                       :23;
    uint32 Tc                             :9; 
                                              
  } Bits;
  uint32 Reg32;
}  DtpDsrmTwominTc;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 DiagHighMatchMask              :1; 
    uint32 DiagLowMatchMask               :1; 
    uint32 FsmErrMask                     :1; 
    uint32 ArbTimeoutErrMask              :1; 
    uint32 TknStatusMask                  :1; 
  } Bits;
  uint32 Reg32;
}  DtpDsrmUbcapMask;


typedef union {
  struct {
    uint32 Reserved                       :25;
    uint32 ClstrPtr                       :7; 
  } Bits;
  uint32 Reg32;
}  DtpFreeClstrMem;


typedef union {
  struct {
    uint32 Vld1                           :1; 
    uint32 Psn1                           :15;
    uint32 Vld0                           :1; 
    uint32 Psn0                           :15;
  } Bits;
  uint32 Reg32;
}  DtpRldMem;


typedef union {
  struct {
    uint32 Reserved                       :4; 
    uint32 Token                          :28;
                                              
  } Bits;
  uint32 Reg32;
}  DtpSaMem;


typedef union {
  struct {
    uint32 Vld31                          :1; 
    uint32 Vld30                          :1; 
    uint32 Vld29                          :1; 
    uint32 Vld28                          :1; 
    uint32 Vld27                          :1; 
    uint32 Vld26                          :1; 
    uint32 Vld25                          :1; 
    uint32 Vld24                          :1; 
    uint32 Vld23                          :1; 
    uint32 Vld22                          :1; 
    uint32 Vld21                          :1; 
    uint32 Vld20                          :1; 
    uint32 Vld19                          :1; 
    uint32 Vld18                          :1; 
    uint32 Vld17                          :1; 
    uint32 Vld16                          :1; 
    uint32 Vld15                          :1; 
    uint32 Vld14                          :1; 
    uint32 Vld13                          :1; 
    uint32 Vld12                          :1; 
    uint32 Vld11                          :1; 
    uint32 Vld10                          :1; 
    uint32 Vld9                           :1; 
    uint32 Vld8                           :1; 
    uint32 Vld7                           :1; 
    uint32 Vld6                           :1; 
    uint32 Vld5                           :1; 
    uint32 Vld4                           :1; 
    uint32 Vld3                           :1; 
    uint32 Vld2                           :1; 
    uint32 Vld1                           :1; 
    uint32 Vld0                           :1; 
  } Bits;
  uint32 Reg32;
}  DtpTagMem;


typedef union {
  struct {
    uint32 Vld31                          :1; 
    uint32 Vld30                          :1; 
    uint32 Vld29                          :1; 
    uint32 Vld28                          :1; 
    uint32 Vld27                          :1; 
    uint32 Vld26                          :1; 
    uint32 Vld25                          :1; 
    uint32 Vld24                          :1; 
    uint32 Vld23                          :1; 
    uint32 Vld22                          :1; 
    uint32 Vld21                          :1; 
    uint32 Vld20                          :1; 
    uint32 Vld19                          :1; 
    uint32 Vld18                          :1; 
    uint32 Vld17                          :1; 
    uint32 Vld16                          :1; 
    uint32 Vld15                          :1; 
    uint32 Vld14                          :1; 
    uint32 Vld13                          :1; 
    uint32 Vld12                          :1; 
    uint32 Vld11                          :1; 
    uint32 Vld10                          :1; 
    uint32 Vld9                           :1; 
    uint32 Vld8                           :1; 
    uint32 Vld7                           :1; 
    uint32 Vld6                           :1; 
    uint32 Vld5                           :1; 
    uint32 Vld4                           :1; 
    uint32 Vld3                           :1; 
    uint32 Vld2                           :1; 
    uint32 Vld1                           :1; 
    uint32 Vld0                           :1; 
  } Bits;
  uint32 Reg32;
}  DtpTagcMem;


typedef union {
  struct {
    uint32 Vld1                           :1; 
    uint32 Psn1                           :15;
    uint32 Vld0                           :1; 
    uint32 Psn0                           :15;
  } Bits;
  uint32 Reg32;
}  DtpTimeoutMem;

typedef struct {
  DtpClstrMem                         DSID0_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID1_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID2_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID3_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID4_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID5_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID6_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID7_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID8_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID9_CLSTR_ENTRY[128];  
  DtpClstrMem                         DSID10_CLSTR_ENTRY[128]; 
  DtpClstrMem                         DSID11_CLSTR_ENTRY[128]; 
  DtpClstrMem                         DSID12_CLSTR_ENTRY[128]; 
  DtpClstrMem                         DSID13_CLSTR_ENTRY[128]; 
  DtpClstrMem                         DSID14_CLSTR_ENTRY[128]; 
  DtpClstrMem                         DSID15_CLSTR_ENTRY[128]; 
}  DtpDtpDsrmClstrMem;

typedef struct {
  DtpFreeClstrMem                     FREE_CLSTR_DATA[128];    
}  DtpDtpDsrmFreeClstrMem;

typedef struct {
  DtpRldMem                           DSID0_RLD_ENTRY[16];     
  DtpRldMem                           DSID1_RLD_ENTRY[16];     
  DtpRldMem                           DSID2_RLD_ENTRY[16];     
  DtpRldMem                           DSID3_RLD_ENTRY[16];     
  DtpRldMem                           DSID4_RLD_ENTRY[16];     
  DtpRldMem                           DSID5_RLD_ENTRY[16];     
  DtpRldMem                           DSID6_RLD_ENTRY[16];     
  DtpRldMem                           DSID7_RLD_ENTRY[16];     
  DtpRldMem                           DSID8_RLD_ENTRY[16];     
  DtpRldMem                           DSID9_RLD_ENTRY[16];     
  DtpRldMem                           DSID10_RLD_ENTRY[16];    
  DtpRldMem                           DSID11_RLD_ENTRY[16];    
  DtpRldMem                           DSID12_RLD_ENTRY[16];    
  DtpRldMem                           DSID13_RLD_ENTRY[16];    
  DtpRldMem                           DSID14_RLD_ENTRY[16];    
  DtpRldMem                           DSID15_RLD_ENTRY[16];    
}  DtpDtpDsrmRldMem;

typedef struct {
  DtpSaMem                            TOKEN[32768];            
}  DtpDtpDsrmSparseAryMem;

typedef struct {
  DtpDsidState0                       DSID0_WD0;               
  uint32                              DSID0_WD1;               
  DtpDsidState2                       DSID0_WD2;               
  DtpDsidState3                       DSID0_WD3;               
  DtpDsidState4                       DSID0_WD4;               
  DtpDsidState5                       DSID0_WD5;               
  uint32                              DSID0_WD6;               
  DtpDsidState7                       DSID0_WD7;               
  uint32                              DSID0_RSVD_WD[8];        
  DtpDsidState0                       DSID1_WD0;               
  uint32                              DSID1_WD1;               
  DtpDsidState2                       DSID1_WD2;               
  DtpDsidState3                       DSID1_WD3;               
  DtpDsidState4                       DSID1_WD4;               
  DtpDsidState5                       DSID1_WD5;               
  uint32                              DSID1_WD6;               
  DtpDsidState7                       DSID1_WD7;               
  uint32                              DSID1_RSVD_WD[8];        
  DtpDsidState0                       DSID2_WD0;               
  uint32                              DSID2_WD1;               
  DtpDsidState2                       DSID2_WD2;               
  DtpDsidState3                       DSID2_WD3;               
  DtpDsidState4                       DSID2_WD4;               
  DtpDsidState5                       DSID2_WD5;               
  uint32                              DSID2_WD6;               
  DtpDsidState7                       DSID2_WD7;               
  uint32                              DSID2_RSVD_WD[8];        
  DtpDsidState0                       DSID3_WD0;               
  uint32                              DSID3_WD1;               
  DtpDsidState2                       DSID3_WD2;               
  DtpDsidState3                       DSID3_WD3;               
  DtpDsidState4                       DSID3_WD4;               
  DtpDsidState5                       DSID3_WD5;               
  uint32                              DSID3_WD6;               
  DtpDsidState7                       DSID3_WD7;               
  uint32                              DSID3_RSVD_WD[8];        
  DtpDsidState0                       DSID4_WD0;               
  uint32                              DSID4_WD1;               
  DtpDsidState2                       DSID4_WD2;               
  DtpDsidState3                       DSID4_WD3;               
  DtpDsidState4                       DSID4_WD4;               
  DtpDsidState5                       DSID4_WD5;               
  uint32                              DSID4_WD6;               
  DtpDsidState7                       DSID4_WD7;               
  uint32                              DSID4_RSVD_WD[8];        
  DtpDsidState0                       DSID5_WD0;               
  uint32                              DSID5_WD1;               
  DtpDsidState2                       DSID5_WD2;               
  DtpDsidState3                       DSID5_WD3;               
  DtpDsidState4                       DSID5_WD4;               
  DtpDsidState5                       DSID5_WD5;               
  uint32                              DSID5_WD6;               
  DtpDsidState7                       DSID5_WD7;               
  uint32                              DSID5_RSVD_WD[8];        
  DtpDsidState0                       DSID6_WD0;               
  uint32                              DSID6_WD1;               
  DtpDsidState2                       DSID6_WD2;               
  DtpDsidState3                       DSID6_WD3;               
  DtpDsidState4                       DSID6_WD4;               
  DtpDsidState5                       DSID6_WD5;               
  uint32                              DSID6_WD6;               
  DtpDsidState7                       DSID6_WD7;               
  uint32                              DSID6_RSVD_WD[8];        
  DtpDsidState0                       DSID7_WD0;               
  uint32                              DSID7_WD1;               
  DtpDsidState2                       DSID7_WD2;               
  DtpDsidState3                       DSID7_WD3;               
  DtpDsidState4                       DSID7_WD4;               
  DtpDsidState5                       DSID7_WD5;               
  uint32                              DSID7_WD6;               
  DtpDsidState7                       DSID7_WD7;               
  uint32                              DSID7_RSVD_WD[8];        
  DtpDsidState0                       DSID8_WD0;               
  uint32                              DSID8_WD1;               
  DtpDsidState2                       DSID8_WD2;               
  DtpDsidState3                       DSID8_WD3;               
  DtpDsidState4                       DSID8_WD4;               
  DtpDsidState5                       DSID8_WD5;               
  uint32                              DSID8_WD6;               
  DtpDsidState7                       DSID8_WD7;               
  uint32                              DSID8_RSVD_WD[8];        
  DtpDsidState0                       DSID9_WD0;               
  uint32                              DSID9_WD1;               
  DtpDsidState2                       DSID9_WD2;               
  DtpDsidState3                       DSID9_WD3;               
  DtpDsidState4                       DSID9_WD4;               
  DtpDsidState5                       DSID9_WD5;               
  uint32                              DSID9_WD6;               
  DtpDsidState7                       DSID9_WD7;               
  uint32                              DSID9_RSVD_WD[8];        
  DtpDsidState0                       DSID10_WD0;              
  uint32                              DSID10_WD1;              
  DtpDsidState2                       DSID10_WD2;              
  DtpDsidState3                       DSID10_WD3;              
  DtpDsidState4                       DSID10_WD4;              
  DtpDsidState5                       DSID10_WD5;              
  uint32                              DSID10_WD6;              
  DtpDsidState7                       DSID10_WD7;              
  uint32                              DSID10_RSVD_WD[8];       
  DtpDsidState0                       DSID11_WD0;              
  uint32                              DSID11_WD1;              
  DtpDsidState2                       DSID11_WD2;              
  DtpDsidState3                       DSID11_WD3;              
  DtpDsidState4                       DSID11_WD4;              
  DtpDsidState5                       DSID11_WD5;              
  uint32                              DSID11_WD6;              
  DtpDsidState7                       DSID11_WD7;              
  uint32                              DSID11_RSVD_WD[8];       
  DtpDsidState0                       DSID12_WD0;              
  uint32                              DSID12_WD1;              
  DtpDsidState2                       DSID12_WD2;              
  DtpDsidState3                       DSID12_WD3;              
  DtpDsidState4                       DSID12_WD4;              
  DtpDsidState5                       DSID12_WD5;              
  uint32                              DSID12_WD6;              
  DtpDsidState7                       DSID12_WD7;              
  uint32                              DSID12_RSVD_WD[8];       
  DtpDsidState0                       DSID13_WD0;              
  uint32                              DSID13_WD1;              
  DtpDsidState2                       DSID13_WD2;              
  DtpDsidState3                       DSID13_WD3;              
  DtpDsidState4                       DSID13_WD4;              
  DtpDsidState5                       DSID13_WD5;              
  uint32                              DSID13_WD6;              
  DtpDsidState7                       DSID13_WD7;              
  uint32                              DSID13_RSVD_WD[8];       
  DtpDsidState0                       DSID14_WD0;              
  uint32                              DSID14_WD1;              
  DtpDsidState2                       DSID14_WD2;              
  DtpDsidState3                       DSID14_WD3;              
  DtpDsidState4                       DSID14_WD4;              
  DtpDsidState5                       DSID14_WD5;              
  uint32                              DSID14_WD6;              
  DtpDsidState7                       DSID14_WD7;              
  uint32                              DSID14_RSVD_WD[8];       
  DtpDsidState0                       DSID15_WD0;              
  uint32                              DSID15_WD1;              
  DtpDsidState2                       DSID15_WD2;              
  DtpDsidState3                       DSID15_WD3;              
  DtpDsidState4                       DSID15_WD4;              
  DtpDsidState5                       DSID15_WD5;              
  uint32                              DSID15_WD6;              
  DtpDsidState7                       DSID15_WD7;              
  uint32                              DSID15_RSVD_WD[8];       
}  DtpDtpDsrmStateMem;

typedef struct {
  uint32                              DSID0_NUM_PKTS_RCVD;     
  uint32                              DSID0_NUM_PKTS_PROC;     
  uint32                              DSID0_NUM_PKTS_LOST_RLD; 
  uint32                              DSID0_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID0_NUM_PKTS_WRONG_CH; 
  uint32                              DSID0_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID0_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID0_NUM_PKTS_WRONG_SCC;
  uint32                              DSID0_NUM_PKTS_BAD_TKN;  
  uint32                              DSID0_NUM_SCC;           
  uint32                              DSID0_NUM_PKTS_WARN_CNT; 
  uint32                              DSID0_NUM_PKTS_NULL_TKN; 
  uint32                              DSID0_NUM_PKTS_INS_ERR;  
  uint32                              DSID0_NUM_PKTS_LOST_OTHER;
  uint32                              DSID0_NUM_NXT_DECL_LOST; 
  uint32                              DSID0_RSVD_WD;           
  uint32                              DSID1_NUM_PKTS_RCVD;     
  uint32                              DSID1_NUM_PKTS_PROC;     
  uint32                              DSID1_NUM_PKTS_LOST_RLD; 
  uint32                              DSID1_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID1_NUM_PKTS_WRONG_CH; 
  uint32                              DSID1_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID1_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID1_NUM_PKTS_WRONG_SCC;
  uint32                              DSID1_NUM_PKTS_BAD_TKN;  
  uint32                              DSID1_NUM_SCC;           
  uint32                              DSID1_NUM_PKTS_WARN_CNT; 
  uint32                              DSID1_NUM_PKTS_NULL_TKN; 
  uint32                              DSID1_NUM_PKTS_INS_ERR;  
  uint32                              DSID1_NUM_PKTS_LOST_OTHER;
  uint32                              DSID1_NUM_NXT_DECL_LOST; 
  uint32                              DSID1_RSVD_WD;           
  uint32                              DSID2_NUM_PKTS_RCVD;     
  uint32                              DSID2_NUM_PKTS_PROC;     
  uint32                              DSID2_NUM_PKTS_LOST_RLD; 
  uint32                              DSID2_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID2_NUM_PKTS_WRONG_CH; 
  uint32                              DSID2_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID2_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID2_NUM_PKTS_WRONG_SCC;
  uint32                              DSID2_NUM_PKTS_BAD_TKN;  
  uint32                              DSID2_NUM_SCC;           
  uint32                              DSID2_NUM_PKTS_WARN_CNT; 
  uint32                              DSID2_NUM_PKTS_NULL_TKN; 
  uint32                              DSID2_NUM_PKTS_INS_ERR;  
  uint32                              DSID2_NUM_PKTS_LOST_OTHER;
  uint32                              DSID2_NUM_NXT_DECL_LOST; 
  uint32                              DSID2_RSVD_WD;           
  uint32                              DSID3_NUM_PKTS_RCVD;     
  uint32                              DSID3_NUM_PKTS_PROC;     
  uint32                              DSID3_NUM_PKTS_LOST_RLD; 
  uint32                              DSID3_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID3_NUM_PKTS_WRONG_CH; 
  uint32                              DSID3_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID3_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID3_NUM_PKTS_WRONG_SCC;
  uint32                              DSID3_NUM_PKTS_BAD_TKN;  
  uint32                              DSID3_NUM_SCC;           
  uint32                              DSID3_NUM_PKTS_WARN_CNT; 
  uint32                              DSID3_NUM_PKTS_NULL_TKN; 
  uint32                              DSID3_NUM_PKTS_INS_ERR;  
  uint32                              DSID3_NUM_PKTS_LOST_OTHER;
  uint32                              DSID3_NUM_NXT_DECL_LOST; 
  uint32                              DSID3_RSVD_WD;           
  uint32                              DSID4_NUM_PKTS_RCVD;     
  uint32                              DSID4_NUM_PKTS_PROC;     
  uint32                              DSID4_NUM_PKTS_LOST_RLD; 
  uint32                              DSID4_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID4_NUM_PKTS_WRONG_CH; 
  uint32                              DSID4_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID4_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID4_NUM_PKTS_WRONG_SCC;
  uint32                              DSID4_NUM_PKTS_BAD_TKN;  
  uint32                              DSID4_NUM_SCC;           
  uint32                              DSID4_NUM_PKTS_WARN_CNT; 
  uint32                              DSID4_NUM_PKTS_NULL_TKN; 
  uint32                              DSID4_NUM_PKTS_INS_ERR;  
  uint32                              DSID4_NUM_PKTS_LOST_OTHER;
  uint32                              DSID4_NUM_NXT_DECL_LOST; 
  uint32                              DSID4_RSVD_WD;           
  uint32                              DSID5_NUM_PKTS_RCVD;     
  uint32                              DSID5_NUM_PKTS_PROC;     
  uint32                              DSID5_NUM_PKTS_LOST_RLD; 
  uint32                              DSID5_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID5_NUM_PKTS_WRONG_CH; 
  uint32                              DSID5_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID5_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID5_NUM_PKTS_WRONG_SCC;
  uint32                              DSID5_NUM_PKTS_BAD_TKN;  
  uint32                              DSID5_NUM_SCC;           
  uint32                              DSID5_NUM_PKTS_WARN_CNT; 
  uint32                              DSID5_NUM_PKTS_NULL_TKN; 
  uint32                              DSID5_NUM_PKTS_INS_ERR;  
  uint32                              DSID5_NUM_PKTS_LOST_OTHER;
  uint32                              DSID5_NUM_NXT_DECL_LOST; 
  uint32                              DSID5_RSVD_WD;           
  uint32                              DSID6_NUM_PKTS_RCVD;     
  uint32                              DSID6_NUM_PKTS_PROC;     
  uint32                              DSID6_NUM_PKTS_LOST_RLD; 
  uint32                              DSID6_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID6_NUM_PKTS_WRONG_CH; 
  uint32                              DSID6_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID6_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID6_NUM_PKTS_WRONG_SCC;
  uint32                              DSID6_NUM_PKTS_BAD_TKN;  
  uint32                              DSID6_NUM_SCC;           
  uint32                              DSID6_NUM_PKTS_WARN_CNT; 
  uint32                              DSID6_NUM_PKTS_NULL_TKN; 
  uint32                              DSID6_NUM_PKTS_INS_ERR;  
  uint32                              DSID6_NUM_PKTS_LOST_OTHER;
  uint32                              DSID6_NUM_NXT_DECL_LOST; 
  uint32                              DSID6_RSVD_WD;           
  uint32                              DSID7_NUM_PKTS_RCVD;     
  uint32                              DSID7_NUM_PKTS_PROC;     
  uint32                              DSID7_NUM_PKTS_LOST_RLD; 
  uint32                              DSID7_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID7_NUM_PKTS_WRONG_CH; 
  uint32                              DSID7_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID7_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID7_NUM_PKTS_WRONG_SCC;
  uint32                              DSID7_NUM_PKTS_BAD_TKN;  
  uint32                              DSID7_NUM_SCC;           
  uint32                              DSID7_NUM_PKTS_WARN_CNT; 
  uint32                              DSID7_NUM_PKTS_NULL_TKN; 
  uint32                              DSID7_NUM_PKTS_INS_ERR;  
  uint32                              DSID7_NUM_PKTS_LOST_OTHER;
  uint32                              DSID7_NUM_NXT_DECL_LOST; 
  uint32                              DSID7_RSVD_WD;           
  uint32                              DSID8_NUM_PKTS_RCVD;     
  uint32                              DSID8_NUM_PKTS_PROC;     
  uint32                              DSID8_NUM_PKTS_LOST_RLD; 
  uint32                              DSID8_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID8_NUM_PKTS_WRONG_CH; 
  uint32                              DSID8_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID8_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID8_NUM_PKTS_WRONG_SCC;
  uint32                              DSID8_NUM_PKTS_BAD_TKN;  
  uint32                              DSID8_NUM_SCC;           
  uint32                              DSID8_NUM_PKTS_WARN_CNT; 
  uint32                              DSID8_NUM_PKTS_NULL_TKN; 
  uint32                              DSID8_NUM_PKTS_INS_ERR;  
  uint32                              DSID8_NUM_PKTS_LOST_OTHER;
  uint32                              DSID8_NUM_NXT_DECL_LOST; 
  uint32                              DSID8_RSVD_WD;           
  uint32                              DSID9_NUM_PKTS_RCVD;     
  uint32                              DSID9_NUM_PKTS_PROC;     
  uint32                              DSID9_NUM_PKTS_LOST_RLD; 
  uint32                              DSID9_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID9_NUM_PKTS_WRONG_CH; 
  uint32                              DSID9_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID9_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID9_NUM_PKTS_WRONG_SCC;
  uint32                              DSID9_NUM_PKTS_BAD_TKN;  
  uint32                              DSID9_NUM_SCC;           
  uint32                              DSID9_NUM_PKTS_WARN_CNT; 
  uint32                              DSID9_NUM_PKTS_NULL_TKN; 
  uint32                              DSID9_NUM_PKTS_INS_ERR;  
  uint32                              DSID9_NUM_PKTS_LOST_OTHER;
  uint32                              DSID9_NUM_NXT_DECL_LOST; 
  uint32                              DSID9_RSVD_WD;           
  uint32                              DSID10_NUM_PKTS_RCVD;    
  uint32                              DSID10_NUM_PKTS_PROC;    
  uint32                              DSID10_NUM_PKTS_LOST_RLD;
  uint32                              DSID10_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID10_NUM_PKTS_WRONG_CH;
  uint32                              DSID10_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID10_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID10_NUM_PKTS_WRONG_SCC;
  uint32                              DSID10_NUM_PKTS_BAD_TKN; 
  uint32                              DSID10_NUM_SCC;          
  uint32                              DSID10_NUM_PKTS_WARN_CNT;
  uint32                              DSID10_NUM_PKTS_NULL_TKN;
  uint32                              DSID10_NUM_PKTS_INS_ERR; 
  uint32                              DSID10_NUM_PKTS_LOST_OTHER;
  uint32                              DSID10_NUM_NXT_DECL_LOST;
  uint32                              DSID10_RSVD_WD;          
  uint32                              DSID11_NUM_PKTS_RCVD;    
  uint32                              DSID11_NUM_PKTS_PROC;    
  uint32                              DSID11_NUM_PKTS_LOST_RLD;
  uint32                              DSID11_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID11_NUM_PKTS_WRONG_CH;
  uint32                              DSID11_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID11_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID11_NUM_PKTS_WRONG_SCC;
  uint32                              DSID11_NUM_PKTS_BAD_TKN; 
  uint32                              DSID11_NUM_SCC;          
  uint32                              DSID11_NUM_PKTS_WARN_CNT;
  uint32                              DSID11_NUM_PKTS_NULL_TKN;
  uint32                              DSID11_NUM_PKTS_INS_ERR; 
  uint32                              DSID11_NUM_PKTS_LOST_OTHER;
  uint32                              DSID11_NUM_NXT_DECL_LOST;
  uint32                              DSID11_RSVD_WD;          
  uint32                              DSID12_NUM_PKTS_RCVD;    
  uint32                              DSID12_NUM_PKTS_PROC;    
  uint32                              DSID12_NUM_PKTS_LOST_RLD;
  uint32                              DSID12_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID12_NUM_PKTS_WRONG_CH;
  uint32                              DSID12_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID12_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID12_NUM_PKTS_WRONG_SCC;
  uint32                              DSID12_NUM_PKTS_BAD_TKN; 
  uint32                              DSID12_NUM_SCC;          
  uint32                              DSID12_NUM_PKTS_WARN_CNT;
  uint32                              DSID12_NUM_PKTS_NULL_TKN;
  uint32                              DSID12_NUM_PKTS_INS_ERR; 
  uint32                              DSID12_NUM_PKTS_LOST_OTHER;
  uint32                              DSID12_NUM_NXT_DECL_LOST;
  uint32                              DSID12_RSVD_WD;          
  uint32                              DSID13_NUM_PKTS_RCVD;    
  uint32                              DSID13_NUM_PKTS_PROC;    
  uint32                              DSID13_NUM_PKTS_LOST_RLD;
  uint32                              DSID13_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID13_NUM_PKTS_WRONG_CH;
  uint32                              DSID13_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID13_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID13_NUM_PKTS_WRONG_SCC;
  uint32                              DSID13_NUM_PKTS_BAD_TKN; 
  uint32                              DSID13_NUM_SCC;          
  uint32                              DSID13_NUM_PKTS_WARN_CNT;
  uint32                              DSID13_NUM_PKTS_NULL_TKN;
  uint32                              DSID13_NUM_PKTS_INS_ERR; 
  uint32                              DSID13_NUM_PKTS_LOST_OTHER;
  uint32                              DSID13_NUM_NXT_DECL_LOST;
  uint32                              DSID13_RSVD_WD;          
  uint32                              DSID14_NUM_PKTS_RCVD;    
  uint32                              DSID14_NUM_PKTS_PROC;    
  uint32                              DSID14_NUM_PKTS_LOST_RLD;
  uint32                              DSID14_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID14_NUM_PKTS_WRONG_CH;
  uint32                              DSID14_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID14_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID14_NUM_PKTS_WRONG_SCC;
  uint32                              DSID14_NUM_PKTS_BAD_TKN; 
  uint32                              DSID14_NUM_SCC;          
  uint32                              DSID14_NUM_PKTS_WARN_CNT;
  uint32                              DSID14_NUM_PKTS_NULL_TKN;
  uint32                              DSID14_NUM_PKTS_INS_ERR; 
  uint32                              DSID14_NUM_PKTS_LOST_OTHER;
  uint32                              DSID14_NUM_NXT_DECL_LOST;
  uint32                              DSID14_RSVD_WD;          
  uint32                              DSID15_NUM_PKTS_RCVD;    
  uint32                              DSID15_NUM_PKTS_PROC;    
  uint32                              DSID15_NUM_PKTS_LOST_RLD;
  uint32                              DSID15_NUM_PKTS_LOST_TMOUT;
  uint32                              DSID15_NUM_PKTS_WRONG_CH;
  uint32                              DSID15_NUM_PKTS_OUTSIDE_WDW;
  uint32                              DSID15_NUM_PKTS_DUP_SEQNUM;
  uint32                              DSID15_NUM_PKTS_WRONG_SCC;
  uint32                              DSID15_NUM_PKTS_BAD_TKN; 
  uint32                              DSID15_NUM_SCC;          
  uint32                              DSID15_NUM_PKTS_WARN_CNT;
  uint32                              DSID15_NUM_PKTS_NULL_TKN;
  uint32                              DSID15_NUM_PKTS_INS_ERR; 
  uint32                              DSID15_NUM_PKTS_LOST_OTHER;
  uint32                              DSID15_NUM_NXT_DECL_LOST;
  uint32                              DSID15_RSVD_WD;          
}  DtpDtpDsrmStatsMem;

typedef struct {
  DtpTagcMem                          TAGC_DSID[32];           
}  DtpDtpDsrmTagCacheMem;

typedef struct {
  DtpTagMem                           TAG_DATA[1024];          
}  DtpDtpDsrmTagMem;

typedef struct {
  DtpTimeoutMem                       DSID0_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID1_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID2_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID3_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID4_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID5_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID6_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID7_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID8_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID9_TMOUT_ENTRY[16];   
  DtpTimeoutMem                       DSID10_TMOUT_ENTRY[16];  
  DtpTimeoutMem                       DSID11_TMOUT_ENTRY[16];  
  DtpTimeoutMem                       DSID12_TMOUT_ENTRY[16];  
  DtpTimeoutMem                       DSID13_TMOUT_ENTRY[16];  
  DtpTimeoutMem                       DSID14_TMOUT_ENTRY[16];  
  DtpTimeoutMem                       DSID15_TMOUT_ENTRY[16];  
}  DtpDtpDsrmTmoutMem;

typedef struct {
  DtpDsrmCtrl                         Ctrl;                    
  uint32                              NmCntr;                  
  DtpDsrmIntMask                      IntMask;                 
  DtpDsrmIntStat                      IntStat;                 
  DtpDsrmClrTm1K                      ClrTm1kInd;              
                                                                 
  DtpDsrmPowbTc                       PowbTc;                  
                                                                 
  DtpDsrmTwominTc                     TwominTc;                
  DtpDsrmPrescaleTc                   PrescaleTc;              
  uint32                              CurMsCntLoad;            
  uint32                              CurMsCnt;                
  uint32                              CurUsCnt;                
  uint32                              CurSCnt;                 
  DtpDsrmFreeClstrFifo                FreeClstrFifo;           
  DtpDsrmFreeClstrFifoLevel           FreeClstrFifoLvl;        
  DtpDsrmFreeClstrFifoLowWmk          FreeClstrFifoLowWmk;     
  DtpDsrmDsidAssigned                 DsidAssigned;            
  DtpDsrmDsidLearning                 DsidLearning;            
  DtpDsrmDsidChgSts                   DsidChgSts;              
  DtpDsrmDsidSccPending               DsidSccPending;          
  DtpDsrmFsmCtrl                      FsmCtrl;                 
  DtpDsrmFsmErr                       FsmErr;                  
  DtpDsrmDsidTagcDirty                DsidTagcDirty;           
  DtpDsrmDsidClusterDirty             DsidClstrDirty;          
  DtpDsrmTimeoutVal                   TimeoutVal;              
  DtpDsrmTimeoutErr                   TimeoutErr;              
  DtpDsrmErrcapStat                   ErrcapStat;              
  DtpDsrmUbcapMask                    UbcapMask;               
  DtpDsrmDiagcapMask                  DiagcapMask;             
  uint8                               Pad0[0x10];
  DtpDsrmPowbCnt                      PowbCntDsid[16];         
                                                                 
  DtpDsrmTwominCnt                    TwominCntDsid[16];       
                                                                 
  DtpDsrmTknData0                     TknData0;                
  DtpDsrmTknData1                     TknData1;                
  uint32                              TknData2;                
  DtpDsrmTknLuRslt                    TknLuRslt;               
  DtpDsrmTknLuData1                   TknLuData1;              
  uint32                              TknLuData2;              
  uint8                               Pad1[0x8];
  DtpDsrmStCmd                        StCmd;                   
  DtpDsrmStRslt                       StRslt;                  
  DtpDsrmStUpdtCmd                    StUpdtCmd;               
  DtpDsrmStUpdtData                   StUpdtData;              
  DtpDsrmTknInCmd                     TknInCmd;                
  DtpDsrmTknInRslt                    TknInRslt;               
  uint32                              TknInTkn;                
  uint8                               Pad2[0x4];
  DtpDsrmTknAcsCmd                    TknAcsCmd;               
  DtpDsrmTknAcsRslt                   TknAcsRslt;              
  DtpDsrmTknAcsSts                    TknAcsSts;               
  DtpDsrmTknAcsStsMsk                 TknAcsStsMsk;            
  uint8                               Pad3[0x30];
  DtpDsrmTknAcsStsDsid                TknAcsStsDsid[16];       
  DtpDsrmBistTm0                      BistTm0;                 
  DtpDsrmBistTm1                      BistTm1;                 
  DtpDsrmDiagCtrl                     DiagCtrl;                
  DtpDsrmDiagStat                     DiagStat;                
  DtpDsrmDiagRslt                     DiagRslt;                
  DtpDsrmDiagMask                     DiagMask;                
  DtpDsrmDiagCmp                      DiagCmp;                 
  DtpDsrmDiagCap                      DiagCap;                 
}  DtpDtpDsrmRegs;

#endif 



