// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         legacy_mac.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef LEGACY_MAC_H__
#define LEGACY_MAC_H__


enum LEGACY_MAC_LED_CONTROL {
  LEGACY_MAC_LED_CONTROL_LED_00=0x0,                 
  LEGACY_MAC_LED_CONTROL_LED_01=0x1,                 
  LEGACY_MAC_LED_CONTROL_LED_10=0x2,                 
  LEGACY_MAC_LED_CONTROL_LED_11=0x3,                 
};

enum LEGACY_MAC_MAC_BURST {
  LEGACY_MAC_MAC_BURST_MAC_BURST_16=0x0,             
  LEGACY_MAC_MAC_BURST_MAC_BURST_32=0x1,             
  LEGACY_MAC_MAC_BURST_MAC_BURST_64=0x2,             
  LEGACY_MAC_MAC_BURST_MAC_BURST_128=0x3,            
};

enum LEGACY_MAC_CAM_BIST {
  LEGACY_MAC_CAM_BIST_CAM_BIST_SEL0=0x0,             
  LEGACY_MAC_CAM_BIST_CAM_BIST_SEL1=0x1,             
  LEGACY_MAC_CAM_BIST_CAM_BIST_SEL2=0x2,             
  LEGACY_MAC_CAM_BIST_CAM_BIST_SEL3=0x3,             
};

enum LEGACY_MAC_CAMSEGEN {
  LEGACY_MAC_CAMSEGEN_CAMSEGEN0=0x0,                 
  LEGACY_MAC_CAMSEGEN_CAMSEGEN1=0x1,                 
  LEGACY_MAC_CAMSEGEN_CAMSEGEN2=0x2,                 
  LEGACY_MAC_CAMSEGEN_CAMSEGEN3=0x3,                 
};

enum LEGACY_MAC_MODULATION_TYPE {
  LEGACY_MAC_MODULATION_TYPE_BPSK=0x0,               
  LEGACY_MAC_MODULATION_TYPE_QPSK=0x1,               
  LEGACY_MAC_MODULATION_TYPE_QAM8=0x2,               
  LEGACY_MAC_MODULATION_TYPE_QAM16=0x3,              
  LEGACY_MAC_MODULATION_TYPE_QAM32=0x4,              
  LEGACY_MAC_MODULATION_TYPE_QAM64=0x5,              
  LEGACY_MAC_MODULATION_TYPE_QAM128=0x6,             
  LEGACY_MAC_MODULATION_TYPE_QAM256=0x7,             
};


typedef union {
  struct {
    uint8  DboStart                       :4; 
    uint8  DboEnd                         :4; 
  } Bits;
  uint8 Reg8;
}  LegacyMacDatabackoff;


typedef union {
  struct {
    uint8  RtlRev                         :4; 
    uint8  MetalRev                       :4; 
  } Bits;
  uint8 Reg8;
}  LegacyMacDeviceVersion;


typedef union {
  struct {
    uint16 Fc015                          :1; 
    uint16 Fc014                          :1; 
    uint16 Fc013                          :1; 
    uint16 Fc012                          :1; 
    uint16 Fc011                          :1; 
    uint16 Fc010                          :1; 
    uint16 Fc09                           :1; 
    uint16 Fc08                           :1; 
    uint16 Fc07                           :1; 
    uint16 Fc06                           :1; 
    uint16 Fc05                           :1; 
    uint16 Fc04                           :1; 
    uint16 Fc03                           :1; 
    uint16 Fc02                           :1; 
    uint16 Fc01                           :1; 
    uint16 Fc00                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacFc0IrqMask;


typedef union {
  struct {
    uint16 Fc015                          :1; 
    uint16 Fc014                          :1; 
    uint16 Fc013                          :1; 
    uint16 Fc012                          :1; 
    uint16 Fc011                          :1; 
    uint16 Fc010                          :1; 
    uint16 Fc09                           :1; 
    uint16 Fc08                           :1; 
    uint16 Fc07                           :1; 
    uint16 Fc06                           :1; 
    uint16 Fc05                           :1; 
    uint16 Fc04                           :1; 
    uint16 Fc03                           :1; 
    uint16 Fc02                           :1; 
    uint16 Fc01                           :1; 
    uint16 Fc00                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacFc0IrqPend;


typedef union {
  struct {
    uint16 Gnt15                          :1; 
    uint16 Gnt14                          :1; 
    uint16 Gnt13                          :1; 
    uint16 Gnt12                          :1; 
    uint16 Gnt11                          :1; 
    uint16 Gnt10                          :1; 
    uint16 Gnt9                           :1; 
    uint16 Gnt8                           :1; 
    uint16 Gnt7                           :1; 
    uint16 Gnt6                           :1; 
    uint16 Gnt5                           :1; 
    uint16 Gnt4                           :1; 
    uint16 Gnt3                           :1; 
    uint16 Gnt2                           :1; 
    uint16 Gnt1                           :1; 
    uint16 Gnt0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacGntIrqMask;


typedef union {
  struct {
    uint16 Gnt15                          :1; 
    uint16 Gnt14                          :1; 
    uint16 Gnt13                          :1; 
    uint16 Gnt12                          :1; 
    uint16 Gnt11                          :1; 
    uint16 Gnt10                          :1; 
    uint16 Gnt9                           :1; 
    uint16 Gnt8                           :1; 
    uint16 Gnt7                           :1; 
    uint16 Gnt6                           :1; 
    uint16 Gnt5                           :1; 
    uint16 Gnt4                           :1; 
    uint16 Gnt3                           :1; 
    uint16 Gnt2                           :1; 
    uint16 Gnt1                           :1; 
    uint16 Gnt0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacGntIrqPend;


typedef union {
  struct {
    uint16 Gmm15                          :1; 
    uint16 Gmm14                          :1; 
    uint16 Gmm13                          :1; 
    uint16 Gmm12                          :1; 
    uint16 Gmm11                          :1; 
    uint16 Gmm10                          :1; 
    uint16 Gmm9                           :1; 
    uint16 Gmm8                           :1; 
    uint16 Gmm7                           :1; 
    uint16 Gmm6                           :1; 
    uint16 Gmm5                           :1; 
    uint16 Gmm4                           :1; 
    uint16 Gmm3                           :1; 
    uint16 Gmm2                           :1; 
    uint16 Gmm1                           :1; 
    uint16 Gmm0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacGrantMismatch;


typedef union {
  struct {
    uint16 Gtm15                          :1; 
    uint16 Gtm14                          :1; 
    uint16 Gtm13                          :1; 
    uint16 Gtm12                          :1; 
    uint16 Gtm11                          :1; 
    uint16 Gtm10                          :1; 
    uint16 Gtm9                           :1; 
    uint16 Gtm8                           :1; 
    uint16 Gtm7                           :1; 
    uint16 Gtm6                           :1; 
    uint16 Gtm5                           :1; 
    uint16 Gtm4                           :1; 
    uint16 Gtm3                           :1; 
    uint16 Gtm2                           :1; 
    uint16 Gtm1                           :1; 
    uint16 Gtm0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacGtmIrqMask;


typedef union {
  struct {
    uint16 Gtm15                          :1; 
    uint16 Gtm14                          :1; 
    uint16 Gtm13                          :1; 
    uint16 Gtm12                          :1; 
    uint16 Gtm11                          :1; 
    uint16 Gtm10                          :1; 
    uint16 Gtm9                           :1; 
    uint16 Gtm8                           :1; 
    uint16 Gtm7                           :1; 
    uint16 Gtm6                           :1; 
    uint16 Gtm5                           :1; 
    uint16 Gtm4                           :1; 
    uint16 Gtm3                           :1; 
    uint16 Gtm2                           :1; 
    uint16 Gtm1                           :1; 
    uint16 Gtm0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacGtmIrqPend;


typedef union {
  struct {
    uint16 Idl15                          :1; 
    uint16 Idl14                          :1; 
    uint16 Idl13                          :1; 
    uint16 Idl12                          :1; 
    uint16 Idl11                          :1; 
    uint16 Idl10                          :1; 
    uint16 Idl9                           :1; 
    uint16 Idl8                           :1; 
    uint16 Idl7                           :1; 
    uint16 Idl6                           :1; 
    uint16 Idl5                           :1; 
    uint16 Idl4                           :1; 
    uint16 Idl3                           :1; 
    uint16 Idl2                           :1; 
    uint16 Idl1                           :1; 
    uint16 Idl0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacIdlIrqMask;


typedef union {
  struct {
    uint16 Idl15                          :1; 
    uint16 Idl14                          :1; 
    uint16 Idl13                          :1; 
    uint16 Idl12                          :1; 
    uint16 Idl11                          :1; 
    uint16 Idl10                          :1; 
    uint16 Idl9                           :1; 
    uint16 Idl8                           :1; 
    uint16 Idl7                           :1; 
    uint16 Idl6                           :1; 
    uint16 Idl5                           :1; 
    uint16 Idl4                           :1; 
    uint16 Idl3                           :1; 
    uint16 Idl2                           :1; 
    uint16 Idl1                           :1; 
    uint16 Idl0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacIdlIrqPend;


typedef union {
  struct {
    uint16 Idn15                          :1; 
    uint16 Idn14                          :1; 
    uint16 Idn13                          :1; 
    uint16 Idn12                          :1; 
    uint16 Idn11                          :1; 
    uint16 Idn10                          :1; 
    uint16 Idn9                           :1; 
    uint16 Idn8                           :1; 
    uint16 Idn7                           :1; 
    uint16 Idn6                           :1; 
    uint16 Idn5                           :1; 
    uint16 Idn4                           :1; 
    uint16 Idn3                           :1; 
    uint16 Idn2                           :1; 
    uint16 Idn1                           :1; 
    uint16 Idn0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacIdnIrqMask;


typedef union {
  struct {
    uint16 Idn15                          :1; 
    uint16 Idn14                          :1; 
    uint16 Idn13                          :1; 
    uint16 Idn12                          :1; 
    uint16 Idn11                          :1; 
    uint16 Idn10                          :1; 
    uint16 Idn9                           :1; 
    uint16 Idn8                           :1; 
    uint16 Idn7                           :1; 
    uint16 Idn6                           :1; 
    uint16 Idn5                           :1; 
    uint16 Idn4                           :1; 
    uint16 Idn3                           :1; 
    uint16 Idn2                           :1; 
    uint16 Idn1                           :1; 
    uint16 Idn0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacIdnIrqPend;


typedef union {
  struct {
    uint8  ModType                        :3; 
    uint8  FecEn                          :1; 
                                              
    uint8  Flcw                           :1; 
                                              
                                              
    uint8  BankNum                        :3; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacInitMaintBank;


typedef union {
  struct {
    uint16 Mci                            :1; 
    uint16 Gmi                            :1; 
    uint16 UbusError                      :1; 
    uint16 LmpRa                          :1; 
    uint16 UbusReplyError                 :1; 
    uint16 Tim1                           :1; 
    uint16 Tim0                           :1; 
    uint16 Imn                            :1; 
    uint16 Brf                            :1; 
    uint16 Reserved                       :2; 
    uint16 Rrs                            :1; 
    uint16 Lmp                            :1; 
    uint16 Reserved2                      :3; 
  } Bits;
  uint16 Reg16;
}  LegacyMacIrqMask;


typedef union {
  struct {
    uint16 Mci                            :1; 
                                              
                                              
    uint16 Gmi                            :1; 
    uint16 Reserved                       :1; 
    uint16 LmpRa                          :1; 
                                              
                                              
    uint16 Reserved2                      :1; 
    uint16 Tim1                           :1; 
                                              
                                              
    uint16 Tim0                           :1; 
                                              
                                              
    uint16 Imn                            :1; 
                                              
    uint16 Brf                            :1; 
                                              
                                              
                                              
                                              
    uint16 Reserved3                      :2; 
    uint16 Rrs                            :1; 
                                              
    uint16 Lmp                            :1; 
                                              
    uint16 Reserved4                      :2; 
    uint16 UbusError                      :1; 
                                              
  } Bits;
  uint16 Reg16;
}  LegacyMacIrqPending;


typedef union {
  struct {
    uint16 UbDevTimeout                   :1; 
    uint16 UbReqoutPlenError              :1; 
    uint16 UbRepinErr                     :1; 
    uint16 UbSbError                      :1; 
    uint16 Reserved                       :3; 
    uint16 GtmIrqBank                     :1; 
    uint16 IdlIrqBank                     :1; 
    uint16 IdnIrqBank                     :1; 
    uint16 NplIrqBank                     :1; 
    uint16 Fc0IrqBank                     :1; 
    uint16 GntIrqBank                     :1; 
    uint16 RqopIrqBank                    :1; 
    uint16 UstIrqBank                     :1; 
    uint16 MainIrqBank                    :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacIrqStatus;


typedef union {
  struct {
    uint16 Reserved                       :7; 
    uint16 GtmIrqBank                     :1; 
    uint16 IdlIrqBank                     :1; 
    uint16 IdnIrqBank                     :1; 
    uint16 NplIrqBank                     :1; 
    uint16 Fc0IrqBank                     :1; 
    uint16 GntIrqBank                     :1; 
    uint16 RqopIrqBank                    :1; 
    uint16 UstIrqBank                     :1; 
    uint16 MainIrqBank                    :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacIrqTopMask;

typedef struct {
  uint32 Word0;
  uint32 Word1;
  uint32 Word2;
  uint32 Word3;
}  LegacyMacIv;

typedef struct {
  uint32 Word0;
  uint32 Word1;
  uint32 Word2;
  uint32 Word3;
}  LegacyMacKey;


typedef union {
  struct {
    uint8  Reserved                       :6; 
    uint8  LedControl                     :2; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacLedCntl;


typedef union {
  struct {
    uint8  Reserved                       :3; 
    uint8  LhGrantIucEn                   :1; 
    uint8  Reserved2                      :4; 
  } Bits;
  uint8 Reg8;
}  LegacyMacLhGrantIucEn;


typedef union {
  struct {
    uint8  ModType                        :3; 
    uint8  FecEn                          :1; 
                                              
    uint8  Flcw                           :1; 
                                              
                                              
    uint8  BankNum                        :3; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacLongGrantBank;


typedef union {
  struct {
    uint8  Reserved                       :6; 
    uint8  MacUbusBurstSize               :2; 
  } Bits;
  uint8 Reg8;
}  LegacyMacMacUbusBsize;


typedef union {
  struct {
    uint8  Reserved                       :2; 
    uint8  MxAutoDisable                  :1; 
                                              
                                              
                                              
    uint8  MxClrRangingFifo               :1; 
                                              
                                              
                                              
    uint8  MxRexmitEnable                 :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  MxXmitEnable                   :1; 
                                              
                                              
                                              
                                              
    uint8  MxStnMaint                     :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  MxRanged                       :1; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacMaintXmit;


typedef union {
  struct {
    uint32 MapFifoOvBase                  :30;
    uint32 Reserved                       :2; 
  } Bits;
  uint32 Reg32;
}  LegacyMacMapFifoOvBase;


typedef union {
  struct {
    uint8  MaxSchedCodesEnable            :1; 
    uint8  Reserved                       :1; 
    uint8  MaxMsPerFrame                  :6; 
  } Bits;
  uint8 Reg8;
}  LegacyMacMaxMsPerFrame;


typedef union {
  struct {
    uint8  MibClear                       :1; 
                                              
                                              
    uint8  Reserved                       :6; 
    uint8  ReadClearDisable               :1; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacMibControl;


typedef union {
  struct {
    uint8  Reserved                       :5; 
    uint8  MibSelect                      :3; 
  } Bits;
  uint8 Reg8;
}  LegacyMacMibSelect;


typedef union {
  struct {
    uint8  Reserved                       :4; 
    uint8  MinislotsPerRequest            :4; 
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacMinislotsPerRequest;


typedef union {
  struct {
    uint8  Reserved                       :2; 
    uint8  MsPerFrame                     :6; 
  } Bits;
  uint8 Reg8;
}  LegacyMacMsPerFrame;


typedef union {
  struct {
    uint16 Npl15                          :1; 
    uint16 Npl14                          :1; 
    uint16 Npl13                          :1; 
    uint16 Npl12                          :1; 
    uint16 Npl11                          :1; 
    uint16 Npl10                          :1; 
    uint16 Npl9                           :1; 
    uint16 Npl8                           :1; 
    uint16 Npl7                           :1; 
    uint16 Npl6                           :1; 
    uint16 Npl5                           :1; 
    uint16 Npl4                           :1; 
    uint16 Npl3                           :1; 
    uint16 Npl2                           :1; 
    uint16 Npl1                           :1; 
    uint16 Npl0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacNplIrqMask;


typedef union {
  struct {
    uint16 Npl15                          :1; 
    uint16 Npl14                          :1; 
    uint16 Npl13                          :1; 
    uint16 Npl12                          :1; 
    uint16 Npl11                          :1; 
    uint16 Npl10                          :1; 
    uint16 Npl9                           :1; 
    uint16 Npl8                           :1; 
    uint16 Npl7                           :1; 
    uint16 Npl6                           :1; 
    uint16 Npl5                           :1; 
    uint16 Npl4                           :1; 
    uint16 Npl3                           :1; 
    uint16 Npl2                           :1; 
    uint16 Npl1                           :1; 
    uint16 Npl0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacNplIrqPend;


typedef union {
  struct {
    uint8  Reserved                       :6; 
    uint8  UsPhsEn                        :1; 
                                              
                                              
    uint8  Reserved2                      :1; 
  } Bits;
  uint8 Reg8;
}  LegacyMacPhsControl;


typedef union {
  struct {
    uint16 Reserved                       :2; 
    uint16 PrimarySid                     :14;
  } Bits;
  uint16 Reg16;
}  LegacyMacPrimarySid;


typedef union {
  struct {
    uint16 SeedEn                         :1; 
    uint16 Randnumseed                    :15;
  } Bits;
  uint16 Reg16;
}  LegacyMacRandnumseed;


typedef union {
  struct {
    uint8  RboStart                       :4; 
    uint8  RboEnd                         :4; 
  } Bits;
  uint8 Reg8;
}  LegacyMacRangbackoff;


typedef union {
  struct {
    uint8  ModType                        :3; 
    uint8  FecEn                          :1; 
                                              
    uint8  Flcw                           :1; 
                                              
                                              
    uint8  BankNum                        :3; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacRequestBank;


typedef union {
  struct {
    uint8  ModType                        :3; 
    uint8  FecEn                          :1; 
                                              
    uint8  Flcw                           :1; 
                                              
                                              
    uint8  BankNum                        :3; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacRequestDataBank;


typedef union {
  struct {
    uint16 Rqop15                         :1; 
    uint16 Rqop14                         :1; 
    uint16 Rqop13                         :1; 
    uint16 Rqop12                         :1; 
    uint16 Rqop11                         :1; 
    uint16 Rqop10                         :1; 
    uint16 Rqop9                          :1; 
    uint16 Rqop8                          :1; 
    uint16 Rqop7                          :1; 
    uint16 Rqop6                          :1; 
    uint16 Rqop5                          :1; 
    uint16 Rqop4                          :1; 
    uint16 Rqop3                          :1; 
    uint16 Rqop2                          :1; 
    uint16 Rqop1                          :1; 
    uint16 Rqop0                          :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacRqopIrqMask;


typedef union {
  struct {
    uint16 Rqop15                         :1; 
    uint16 Rqop14                         :1; 
    uint16 Rqop13                         :1; 
    uint16 Rqop12                         :1; 
    uint16 Rqop11                         :1; 
    uint16 Rqop10                         :1; 
    uint16 Rqop9                          :1; 
    uint16 Rqop8                          :1; 
    uint16 Rqop7                          :1; 
    uint16 Rqop6                          :1; 
    uint16 Rqop5                          :1; 
    uint16 Rqop4                          :1; 
    uint16 Rqop3                          :1; 
    uint16 Rqop2                          :1; 
    uint16 Rqop1                          :1; 
    uint16 Rqop0                          :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacRqopIrqPend;


typedef union {
  struct {
    uint8  ModType                        :3; 
    uint8  FecEn                          :1; 
                                              
    uint8  Flcw                           :1; 
                                              
                                              
    uint8  BankNum                        :3; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacShortGrantBank;


typedef union {
  struct {
    uint8  Reserved                       :3; 
    uint8  ShGrantIucEn                   :1; 
    uint8  Reserved2                      :4; 
  } Bits;
  uint8 Reg8;
}  LegacyMacShGrantIucEn;


typedef union {
  struct {
    uint8  ModType                        :3; 
    uint8  FecEn                          :1; 
                                              
    uint8  Flcw                           :1; 
                                              
                                              
    uint8  BankNum                        :3; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacStnMaintBank;


typedef union {
  struct {
    uint8  Reserved                       :4; 
    uint8  TFreeze                        :1; 
                                              
    uint8  TIrqen                         :1; 
                                              
                                              
                                              
    uint8  TRepeat                        :1; 
                                              
                                              
                                              
                                              
    uint8  TEnable                        :1; 
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacTcontrol;


typedef union {
  struct {
    uint8  DataavClkN                     :1; 
    uint8  Reserved                       :6; 
    uint8  Lben                           :1; 
  } Bits;
  uint8 Reg8;
}  LegacyMacTestControl;


typedef union {
  struct {
    uint8  MapParseFreezeEn               :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  MapParseFreeze                 :1; 
    uint8  Ms32mode                       :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  Clrflowctrl                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  IgnoreLostMap                  :1; 
                                              
                                              
                                              
                                              
    uint8  IgnoreSync                     :1; 
                                              
                                              
                                              
                                              
    uint8  UsXmitInhibit                  :1; 
                                              
                                              
                                              
    uint8  UsXmitEnable                   :1; 
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacUcsr;


typedef union {
  struct {
    uint16 Utp15                          :1; 
    uint16 Utp14                          :1; 
    uint16 Utp13                          :1; 
    uint16 Utp12                          :1; 
    uint16 Utp11                          :1; 
    uint16 Utp10                          :1; 
    uint16 Utp9                           :1; 
    uint16 Utp8                           :1; 
    uint16 Utp7                           :1; 
    uint16 Utp6                           :1; 
    uint16 Utp5                           :1; 
    uint16 Utp4                           :1; 
    uint16 Utp3                           :1; 
    uint16 Utp2                           :1; 
    uint16 Utp1                           :1; 
    uint16 Utp0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacUstIrqMask;


typedef union {
  struct {
    uint16 Utp15                          :1; 
    uint16 Utp14                          :1; 
    uint16 Utp13                          :1; 
    uint16 Utp12                          :1; 
    uint16 Utp11                          :1; 
    uint16 Utp10                          :1; 
    uint16 Utp9                           :1; 
    uint16 Utp8                           :1; 
    uint16 Utp7                           :1; 
    uint16 Utp6                           :1; 
    uint16 Utp5                           :1; 
    uint16 Utp4                           :1; 
    uint16 Utp3                           :1; 
    uint16 Utp2                           :1; 
    uint16 Utp1                           :1; 
    uint16 Utp0                           :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacUstIrqPend;


typedef union {
  struct {
    uint32 UsBufDescBase                  :30;
    uint32 Reserved                       :2; 
  } Bits;
  uint32 Reg32;
}  LegacyMacUsBufDescBase;


typedef union {
  struct {
    uint8  UsDesChk                       :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  Reserved                       :1; 
    uint8  UsDesEnable                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  Reserved2                      :2; 
    uint8  UsDesMode                      :1; 
                                              
                                              
                                              
                                              
    uint8  Reserved3                      :1; 
    uint8  DesMode                        :1; 
  } Bits;
  uint8 Reg8;
}  LegacyMacUsDesControl;


typedef union {
  struct {
    uint8  UsEn                           :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  Reserved                       :1; 
    uint8  UsBusy                         :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  UsUdgEnable                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  UsFragSeqCntrl                 :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  UsPbDisable                    :1; 
                                              
                                              
    uint8  UsFragEnable                   :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  UsCcEnable                     :1; 
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacUsDmaControl;


typedef union {
  struct {
    uint16 Reserved                       :2; 
    uint16 UsGroupSid                     :14;
  } Bits;
  uint16 Reg16;
}  LegacyMacUsGroupSid;


typedef union {
  struct {
    uint16 Us15GsidEn                     :1; 
    uint16 Us14GsidEn                     :1; 
    uint16 Us13GsidEn                     :1; 
    uint16 Us12GsidEn                     :1; 
    uint16 Us11GsidEn                     :1; 
    uint16 Us10GsidEn                     :1; 
    uint16 Us9GSidEn                      :1; 
    uint16 Us8GsidEn                      :1; 
    uint16 Us7GsidEn                      :1; 
    uint16 Us6GsidEn                      :1; 
    uint16 Us5GsidEn                      :1; 
    uint16 Us4GsidEn                      :1; 
    uint16 Us3GsidEn                      :1; 
    uint16 Us2GsidEn                      :1; 
    uint16 Us1GsidEn                      :1; 
    uint16 Us0GsidEn                      :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacUsGrpSidControl;


typedef union {
  struct {
    uint32 UsPhsBase                      :29;
    uint32 Reserved                       :3; 
  } Bits;
  uint32 Reg32;
}  LegacyMacUsPhsBase;


typedef union {
  struct {
    uint32 UsPktDescBase                  :30;
    uint32 Reserved                       :2; 
  } Bits;
  uint32 Reg32;
}  LegacyMacUsPktDescBase;


typedef union {
  struct {
    uint16 Reserved                       :15;
    uint16 PrimarySidEn                   :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacUsPrimSidControl;


typedef union {
  struct {
    uint8  Reserved                       :4; 
    uint8  UsQueueSelect                  :4; 
  } Bits;
  uint8 Reg8;
}  LegacyMacUsQueueSelect;


typedef union {
  struct {
    uint8  Reserved                       :4; 
    uint8  UsTpQueueSelect                :4; 
  } Bits;
  uint8 Reg8;
}  LegacyMacUsTpQueueSelect;


typedef union {
  struct {
    uint16 Reserved                       :2; 
    uint16 UsUnicastSid                   :14;
  } Bits;
  uint16 Reg16;
}  LegacyMacUsUnicastSid;


typedef union {
  struct {
    uint16 Us15SidEn                      :1; 
    uint16 Us14SidEn                      :1; 
    uint16 Us13SidEn                      :1; 
    uint16 Us12SidEn                      :1; 
    uint16 Us11SidEn                      :1; 
    uint16 Us10SidEn                      :1; 
    uint16 Us9SidEn                       :1; 
    uint16 Us8SidEn                       :1; 
    uint16 Us7SidEn                       :1; 
    uint16 Us6SidEn                       :1; 
    uint16 Us5SidEn                       :1; 
    uint16 Us4SidEn                       :1; 
    uint16 Us3SidEn                       :1; 
    uint16 Us2SidEn                       :1; 
    uint16 Us1SidEn                       :1; 
    uint16 Us0SidEn                       :1; 
  } Bits;
  uint16 Reg16;
}  LegacyMacUsUniSidControl;


typedef union {
  struct {
    uint8  ModType                        :3; 
    uint8  FecEn                          :1; 
                                              
    uint8  Flcw                           :1; 
                                              
                                              
    uint8  BankNum                        :3; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  LegacyMacUGrantBank;

typedef struct {
  LegacyMacLedCntl                    LedCntl;                 
  uint8                               Pad0[0x1];
  LegacyMacTcontrol                   T1control;               
  LegacyMacTcontrol                   T2control;               
  uint8                               T1count;                 
  uint8                               Pad1[0x3];
  uint8                               T2count;                 
  uint8                               Pad2[0x3];
  LegacyMacMacUbusBsize               MacUbusBsize;            
  uint8                               Pad3[0x1];
  uint8                               Reserved00e;             
  uint8                               Pad4[0x1];
  LegacyMacIrqStatus                  IrqStatus;               
  LegacyMacIrqTopMask                 IrqTopMask;              
  LegacyMacIrqPending                 IrqPending;              
  LegacyMacIrqMask                    IrqMask;                 
  LegacyMacUstIrqPend                 UstIrqPend;              
  LegacyMacUstIrqMask                 UstIrqMask;              
  LegacyMacRqopIrqPend                RqopIrqPend;             
  LegacyMacRqopIrqMask                RqopIrqMask;             
  LegacyMacGntIrqPend                 GntIrqPend;              
  LegacyMacGntIrqMask                 GntIrqMask;              
  LegacyMacFc0IrqPend                 Fc0IrqPend;              
  LegacyMacFc0IrqMask                 Fc0IrqMask;              
  LegacyMacNplIrqPend                 NplIrqPend;              
  LegacyMacNplIrqMask                 NplIrqMask;              
  LegacyMacIdnIrqPend                 IdnIrqPend;              
  LegacyMacIdnIrqMask                 IdnIrqMask;              
  LegacyMacIdlIrqPend                 IdlIrqPend;              
  LegacyMacIdlIrqMask                 IdlIrqMask;              
  LegacyMacGtmIrqPend                 GtmIrqPend;              
  LegacyMacGtmIrqMask                 GtmIrqMask;              
  LegacyMacDeviceVersion              DeviceVersion;           
  uint8                               Pad5[0x1];
  uint16                              TestPort1;               
  uint16                              TestPort2;               
  uint8                               DiagSel1;                
  uint8                               DiagSel2;                
  uint8                               Pad6[0x140];
  uint32                              UsReqDataRetrys;         
  uint32                              UsUnicastRetrys;         
  uint32                              UsRetryFails;            
  uint32                              UsPktCount;              
  uint32                              UsCdMinislotsUsed;       
  uint32                              UsUniMinislotsUsed;      
  uint8                               Pad7[0x1c];
  uint32                              OverMaxSchedCodes;       
  uint32                              UsRangeReqs;             
  uint8                               Pad8[0x20];
  uint32                              UsTxByteCount;           
  uint8                               Pad9[0x4];
  LegacyMacMibSelect                  MibSelect;               
  uint8                               Pad10[0x3];
  LegacyMacMibControl                 MibControl;              
  uint8                               Pad11[0x17];
  LegacyMacKey                        KeyEven;                 
  LegacyMacKey                        KeyOdd;                  
  LegacyMacIv                         IvEven;                  
  LegacyMacIv                         IvOdd;                   
  LegacyMacUsTpQueueSelect            UsTpQueueSelect;         
  LegacyMacUsQueueSelect              UsQueueSelect;           
  uint8                               Pad12[0x1];
  LegacyMacUsDmaControl               UsDmaControl;            
  uint8                               UsUdgBurstLen;           
  uint8                               UsPktDescIndex;          
  LegacyMacUsUnicastSid               UsUnicastSid;            
  LegacyMacUsPktDescBase              UsPktDescBase;           
  LegacyMacUsBufDescBase              UsBufDescBase;           
  LegacyMacUsGroupSid                 UsGroupSid;              
  uint8                               Pad13[0x1];
  uint8                               UsDmaXmitStart;          
  uint8                               Pad14[0x1];
  uint8                               UsUbusBurstsize;         
  uint8                               Pad15[0x4a];
  LegacyMacUsUniSidControl            UsUniSidControl;         
  LegacyMacUsGrpSidControl            UsGrpSidControl;         
  LegacyMacUsPrimSidControl           UsPrimSidControl;        
  LegacyMacPrimarySid                 PrimarySid;              
  uint8                               Pad16[0x8];
  LegacyMacMapFifoOvBase              MapFifoOvBase;           
  uint8                               Pad17[0x10];
  LegacyMacUsPhsBase                  UsPhsBase;               
  LegacyMacPhsControl                 PhsControl;              
  uint8                               PhsMaxsize;              
  uint8                               Pad18[0x2];
  uint16                              Maxshortbytes;           
  uint8                               Pad19[0x2];
  uint16                              UsFragCount;             
  uint16                              UsQueueDepth;            
  uint16                              UsFrameCount;            
  uint16                              UsConcatCount;           
  uint8                               Pad20[0x4];
  LegacyMacUsDesControl               UsDesControl;            
  uint8                               DesUnencrypPduLen;       
  uint8                               ResUnencrypPduLen;       
  uint8                               AtmUnencrypPduLen;       
  uint8                               Pad21[0x320];
  uint8                               RangingFifo;             
  LegacyMacUcsr                       Ucsr;                    
  LegacyMacMaintXmit                  MaintXmit;               
  uint8                               MacAdvTdma;              
  uint8                               TicksPerMinislot;        
  uint8                               SymbPerMinislot;         
  LegacyMacMinislotsPerRequest        MinislotsPerRequest;     
  uint8                               MaxRereq;                
  uint16                              Broadreqdis;             
  uint16                              Reqinrddis;              
  uint16                              Datainrddis;             
  LegacyMacRequestBank                RequestBank;             
  LegacyMacRequestDataBank            RequestDataBank;         
  LegacyMacInitMaintBank              InitMaintBank;           
                                                                 
  LegacyMacStnMaintBank               StnMaintBank;            
                                                                 
  LegacyMacShortGrantBank             ShortGrantBank;          
  LegacyMacLongGrantBank              LongGrantBank;           
  uint8                               ShortDataGrant;          
  uint8                               LongDataGrant;           
  uint8                               ImntBurstLen;            
  LegacyMacMsPerFrame                 MsPerFrame;              
  LegacyMacMaxMsPerFrame              MaxMsPerFrame;           
                                                                 
  uint8                               SpareReg19;              
  uint8                               SpareReg1a;              
  uint8                               SpareReg1b;              
  uint8                               SpareReg1c;              
  uint8                               SpareReg1d;              
  uint8                               SpareReg1e;              
  uint8                               SpareReg1f;              
  uint16                              Idledown;                
  LegacyMacDatabackoff                Databackoff;             
  LegacyMacRangbackoff                Rangbackoff;             
  uint8                               UsUcdcount;              
  LegacyMacUGrantBank                 UGrantBank;              
                                                                 
  LegacyMacShGrantIucEn               ShGrantIucEn;            
  LegacyMacLhGrantIucEn               LhGrantIucEn;            
  LegacyMacGrantMismatch              GrantMismatch;           
  uint16                              MacRunAhead;             
  uint8                               SpareReg2c;              
  uint8                               SpareReg2d;              
  uint8                               SpareReg2e;              
  uint8                               SpareReg2f;              
  uint16                              ReqDataLu[14];           
  LegacyMacRandnumseed                Randnumseed;             
  uint16                              Randtesten;              
  uint8                               TestBackoff[16];         
  LegacyMacTestControl                TestControl;             
  uint8                               UsLoopData;              
  uint8                               UsLoopDv;                
  uint8                               Pad22[0x19d];
  uint8                               PhyTableBase;            
  uint8                               Pad23[0x1ff];
  uint8                               LaTableBase;             
}  LegacyMacRegs;

#endif 



