// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         segdma.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef SEGDMA_H__
#define SEGDMA_H__



typedef union {
  struct {
    uint32 Chan1FlowIdle                  :16;
                                              
                                              
                                              
    uint32 Chan0FlowIdle                  :16;
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaChan10FlowIdle;


typedef union {
  struct {
    uint32 Chan3FlowIdle                  :16;
                                              
                                              
                                              
    uint32 Chan2FlowIdle                  :16;
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaChan32FlowIdle;


typedef union {
  struct {
    uint32 Chan3IrqMask                   :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Chan2IrqMask                   :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Chan1IrqMask                   :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Chan0IrqMask                   :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaChanIrqMask;


typedef union {
  struct {
    uint32 Channel3Irq                    :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Channel2Irq                    :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Channel1Irq                    :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Channel0Irq                    :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaChanIrqStatus;


typedef union {
  struct {
    uint32 UbusMemCaptureEnable           :1; 
    uint32 Reserved                       :3; 
    uint32 UbusMaxReqSize                 :4; 
                                              
                                              
    uint32 Reserved2                      :2; 
    uint32 BfmUbusMsgId                   :6; 
                                              
                                              
    uint32 Reserved3                      :11;
    uint32 BurstableClientEnable          :1; 
                                              
                                              
    uint32 DiagSelectsInternal            :1; 
                                              
    uint32 Reserved4                      :1; 
    uint32 GrantBackdoorEnable            :1; 
                                              
                                              
    uint32 DmaPriority                    :1; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaConfig1;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 DiscardTimerValue              :16;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaDiscardTimer;


typedef union {
  struct {
    uint32 Reserved                       :2; 
    uint32 BfmMsgfifoThreshold            :6; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :2; 
    uint32 DmaMsgfifoThreshold            :6; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 DmaUbusNoackThreshold          :16;
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaDmabfmThresholds;


typedef union {
  struct {
    uint32 GrantProcTimeAllowed           :16;
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :8; 
    uint32 GrantTimerDisable              :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 FlowUgsQiEn                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FlowLowLatencyEn               :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FlowSeqNumWr                   :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FlowSegoffConcatEn             :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FlowFlush                      :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 SegHeaderOn                    :1; 
                                              
    uint32 FlowEnable                     :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaFlowControl;


typedef union {
  struct {
    uint32 FlowBusy                       :1; 
                                              
    uint32 Reserved                       :3; 
    uint32 FlowBusyOnChan3                :1; 
                                              
    uint32 FlowBusyOnChan2                :1; 
                                              
    uint32 FlowBusyOnChan1                :1; 
                                              
    uint32 FlowBusyOnChan0                :1; 
                                              
    uint32 Reserved2                      :6; 
    uint32 DmaEhdrError                   :2; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 SegErrorFlags                  :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved3                      :2; 
    uint32 DmaUgsQiBitSet                 :1; 
                                              
                                              
    uint32 SegSeqnumWrDone                :1; 
                                              
    uint32 BfmFlushComplete               :1; 
                                              
    uint32 SegFlushComplete               :1; 
    uint32 SegDisTimerExpired             :1; 
                                              
                                              
    uint32 SegGntTimerExpired             :1; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaFlowIrqStatus;


typedef union {
  struct {
    uint32 Reserved                       :15;
    uint32 NumofTkidsHighQueue            :17;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaFlowNumofTkidHq;


typedef union {
  struct {
    uint32 Reserved                       :15;
    uint32 NumofTkidsLowQueue             :17;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaFlowNumofTkidLq;


typedef union {
  struct {
    uint32 GntbkdrStart                   :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 GntbkdrDone                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 GrantChannelNum                :2; 
    uint32 GrantFlowId                    :4; 
    uint32 Reserved                       :4; 
    uint32 GrantLengthBkdr                :20;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaGntStatusBkdr;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 SegdmaTkmNoackIrq              :1; 
                                              
    uint32 Reserved2                      :3; 
    uint32 SegdmaMasterRepinError         :1; 
                                              
    uint32 SegdmaMasterReqoutPlenError    :1; 
                                              
    uint32 SegdmaSlaveDevTimeout          :1; 
                                              
    uint32 SegdmaRbusBridgeError          :1; 
    uint32 Reserved3                      :1; 
    uint32 SegdmaRbusSlaveDevTimeout      :1; 
                                              
    uint32 UsphyRbusSlaveDevTimeout       :1; 
                                              
    uint32 UsmacRbusSlaveDevTimeout       :1; 
                                              
    uint32 Tc3RbusSlaveDevTimeout         :1; 
                                              
    uint32 Tc2RbusSlaveDevTimeout         :1; 
                                              
    uint32 Tc1RbusSlaveDevTimeout         :1; 
                                              
    uint32 Tc0RbusSlaveDevTimeout         :1; 
                                              
    uint32 Reserved4                      :1; 
    uint32 SegdmaRbusSlaveErrAck          :1; 
                                              
    uint32 UsphyRbusSlaveErrAck           :1; 
                                              
    uint32 UsmacRbusSlaveErrAck           :1; 
                                              
    uint32 Tc3RbusSlaveErrAck             :1; 
                                              
    uint32 Tc2RbusSlaveErrAck             :1; 
                                              
    uint32 Tc1RbusSlaveErrAck             :1; 
                                              
    uint32 Tc0RbusSlaveErrAck             :1; 
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaIrqAuxStatus;


typedef union {
  struct {
    uint32 PipeBusy                       :1; 
                                              
                                              
    uint32 UpiFlowBusy                    :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 UpiDiag1                       :1; 
    uint32 UpiDiag2                       :1; 
    uint32 UpiChan3FlowBusy               :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 UpiChan2FlowBusy               :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 UpiChan1FlowBusy               :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 UpiChan0FlowBusy               :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 AuxIrq                         :1; 
                                              
    uint32 Reserved                       :3; 
    uint32 Channel3Irq                    :1; 
                                              
    uint32 Channel2Irq                    :1; 
                                              
    uint32 Channel1Irq                    :1; 
                                              
    uint32 Channel0Irq                    :1; 
                                              
    uint32 FlowFIrq                       :1; 
                                              
                                              
    uint32 FlowEIrq                       :1; 
                                              
                                              
    uint32 FlowDIrq                       :1; 
                                              
                                              
    uint32 FlowCIrq                       :1; 
                                              
                                              
    uint32 FlowBIrq                       :1; 
                                              
                                              
    uint32 FlowAIrq                       :1; 
                                              
                                              
    uint32 Flow9Irq                       :1; 
                                              
                                              
    uint32 Flow8Irq                       :1; 
                                              
                                              
    uint32 Flow7Irq                       :1; 
                                              
                                              
    uint32 Flow6Irq                       :1; 
                                              
                                              
    uint32 Flow5Irq                       :1; 
                                              
                                              
    uint32 Flow4Irq                       :1; 
                                              
                                              
    uint32 Flow3Irq                       :1; 
                                              
                                              
    uint32 Flow2Irq                       :1; 
                                              
                                              
    uint32 Flow1Irq                       :1; 
                                              
                                              
    uint32 Flow0Irq                       :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaIrqStatus;


typedef union {
  struct {
    uint32 MibBytesDiscardFl3Rst          :1; 
    uint32 MibPacketsDiscardFl3Reset      :1; 
                                              
    uint32 MibPacketsProcessFl3Reset      :1; 
                                              
    uint32 MibSegProcFl3Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl3Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl3Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl3Ch0Reset          :1; 
                                              
    uint32 Reserved                       :1; 
    uint32 MibBytesDiscardFl2Rst          :1; 
    uint32 MibPacketsDiscardFl2Reset      :1; 
                                              
    uint32 MibPacketsProcessFl2Reset      :1; 
                                              
    uint32 MibSegProcFl2Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl2Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl2Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl2Ch0Reset          :1; 
                                              
    uint32 Reserved2                      :1; 
    uint32 MibBytesDiscardFl1Rst          :1; 
    uint32 MibPacketsDiscardFl1Reset      :1; 
                                              
    uint32 MibPacketsProcessFl1Reset      :1; 
                                              
    uint32 MibSegProcFl1Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl1Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl1Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl1Ch0Reset          :1; 
                                              
    uint32 Reserved3                      :1; 
    uint32 MibBytesDiscardFl0Rst          :1; 
    uint32 MibPacketsDiscardFl0Reset      :1; 
                                              
    uint32 MibPacketsProcessFl0Reset      :1; 
                                              
    uint32 MibSegProcFl0Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl0Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl0Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl0Ch0Reset          :1; 
                                              
    uint32 Reserved4                      :1; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaMibResetFlow30;


typedef union {
  struct {
    uint32 MibBytesDiscardFl7Rst          :1; 
    uint32 MibPacketsDiscardFl7Reset      :1; 
                                              
    uint32 MibPacketsProcessFl7Reset      :1; 
                                              
    uint32 MibSegProcFl7Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl7Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl7Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl7Ch0Reset          :1; 
                                              
    uint32 Reserved                       :1; 
    uint32 MibBytesDiscardFl6Rst          :1; 
    uint32 MibPacketsDiscardFl6Reset      :1; 
                                              
    uint32 MibPacketsProcessFl6Reset      :1; 
                                              
    uint32 MibSegProcFl6Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl6Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl6Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl6Ch0Reset          :1; 
                                              
    uint32 Reserved2                      :1; 
    uint32 MibBytesDiscardFl5Rst          :1; 
    uint32 MibPacketsDiscardFl5Reset      :1; 
                                              
    uint32 MibPacketsProcessFl5Reset      :1; 
                                              
    uint32 MibSegProcFl5Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl5Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl5Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl5Ch0Reset          :1; 
                                              
    uint32 Reserved3                      :1; 
    uint32 MibBytesDiscardFl4Rst          :1; 
    uint32 MibPacketsDiscardFl4Reset      :1; 
                                              
    uint32 MibPacketsProcessFl4Reset      :1; 
                                              
    uint32 MibSegProcFl4Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl4Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl4Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl4Ch0Reset          :1; 
                                              
    uint32 Reserved4                      :1; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaMibResetFlow74;


typedef union {
  struct {
    uint32 MibBytesDiscardFlBRst          :1; 
                                              
    uint32 MibPacketsDiscardFlBReset      :1; 
                                              
    uint32 MibPacketsProcessFlBReset      :1; 
                                              
    uint32 MibSegProcFlBCh3Reset          :1; 
                                              
    uint32 MibSegProcFlBCh2Reset          :1; 
                                              
    uint32 MibSegProcFlBCh1Reset          :1; 
                                              
    uint32 MibSegProcFlBCh0Reset          :1; 
                                              
    uint32 Reserved                       :1; 
    uint32 MibBytesDiscardFlARst          :1; 
                                              
    uint32 MibPacketsDiscardFlAReset      :1; 
                                              
    uint32 MibPacketsProcessFlAReset      :1; 
                                              
    uint32 MibSegProcFlACh3Reset          :1; 
                                              
    uint32 MibSegProcFlACh2Reset          :1; 
                                              
    uint32 MibSegProcFlACh1Reset          :1; 
                                              
    uint32 MibSegProcFlACh0Reset          :1; 
                                              
    uint32 Reserved2                      :1; 
    uint32 MibBytesDiscardFl9Rst          :1; 
    uint32 MibPacketsDiscardFl9Reset      :1; 
                                              
    uint32 MibPacketsProcessFl9Reset      :1; 
                                              
    uint32 MibSegProcFl9Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl9Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl9Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl9Ch0Reset          :1; 
                                              
    uint32 Reserved3                      :1; 
    uint32 MibBytesDiscardFl8Rst          :1; 
    uint32 MibPacketsDiscardFl8Reset      :1; 
                                              
    uint32 MibPacketsProcessFl8Reset      :1; 
                                              
    uint32 MibSegProcFl8Ch3Reset          :1; 
                                              
    uint32 MibSegProcFl8Ch2Reset          :1; 
                                              
    uint32 MibSegProcFl8Ch1Reset          :1; 
                                              
    uint32 MibSegProcFl8Ch0Reset          :1; 
                                              
    uint32 Reserved4                      :1; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaMibResetFlowB8;


typedef union {
  struct {
    uint32 MibBytesDiscardFlFRst          :1; 
                                              
    uint32 MibPacketsDiscardFlFReset      :1; 
                                              
    uint32 MibPacketsProcessFlFReset      :1; 
                                              
    uint32 MibSegProcFlFCh3Reset          :1; 
                                              
    uint32 MibSegProcFlFCh2Reset          :1; 
                                              
    uint32 MibSegProcFlFCh1Reset          :1; 
                                              
    uint32 MibSegProcFlFCh0Reset          :1; 
                                              
    uint32 Reserved                       :1; 
    uint32 MibBytesDiscardFlERst          :1; 
                                              
    uint32 MibPacketsDiscardFlEReset      :1; 
                                              
    uint32 MibPacketsProcessFlEReset      :1; 
                                              
    uint32 MibSegProcFlECh3Reset          :1; 
                                              
    uint32 MibSegProcFlECh2Reset          :1; 
                                              
    uint32 MibSegProcFlECh1Reset          :1; 
                                              
    uint32 MibSegProcFlECh0Reset          :1; 
                                              
    uint32 Reserved2                      :1; 
    uint32 MibBytesDiscardFlDRst          :1; 
                                              
    uint32 MibPacketsDiscardFlDReset      :1; 
                                              
    uint32 MibPacketsProcessFlDReset      :1; 
                                              
    uint32 MibSegProcFlDCh3Reset          :1; 
                                              
    uint32 MibSegProcFlDCh2Reset          :1; 
                                              
    uint32 MibSegProcFlDCh1Reset          :1; 
                                              
    uint32 MibSegProcFlDCh0Reset          :1; 
                                              
    uint32 Reserved3                      :1; 
    uint32 MibBytesDiscardFlCRst          :1; 
                                              
    uint32 MibPacketsDiscardFlCReset      :1; 
                                              
    uint32 MibPacketsProcessFlCReset      :1; 
                                              
    uint32 MibSegProcFlCCh3Reset          :1; 
                                              
    uint32 MibSegProcFlCCh2Reset          :1; 
                                              
    uint32 MibSegProcFlCCh1Reset          :1; 
                                              
    uint32 MibSegProcFlCCh0Reset          :1; 
                                              
    uint32 Reserved4                      :1; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaMibResetFlowFC;


typedef union {
  struct {
    uint32 SegdmaLogicReset               :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 SegdmaRegfileReset             :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :3; 
    uint32 SegdmaSegReset                 :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 SegdmaTkmReset                 :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 SegdmaUbusReset                :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 BfmChn3LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 BfmChn2LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 BfmChn1LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 BfmChn0LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 DmaChn3LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 DmaChn2LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 DmaChn1LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 DmaChn0LogicReset              :1; 
                                              
                                              
                                              
                                              
    uint32 RegisterTestInproc             :1; 
                                              
                                              
    uint32 Reserved2                      :5; 
    uint32 Diag2CntReset                  :1; 
                                              
                                              
    uint32 Diag1CntReset                  :1; 
                                              
                                              
    uint32 BfmChn3StatCntReset            :1; 
                                              
                                              
                                              
    uint32 BfmChn2StatCntReset            :1; 
                                              
                                              
                                              
    uint32 BfmChn1StatCntReset            :1; 
                                              
                                              
                                              
    uint32 BfmChn0StatCntReset            :1; 
                                              
                                              
                                              
    uint32 DmaChn3StatCntReset            :1; 
                                              
                                              
                                              
    uint32 DmaChn2StatCntReset            :1; 
                                              
                                              
                                              
    uint32 DmaChn1StatCntReset            :1; 
                                              
                                              
                                              
    uint32 DmaChn0StatCntReset            :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaResetControl;


typedef union {
  struct {
    uint32 Reserved                       :19;
    uint32 SequenceNumber                 :13;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaSequenceNum;


typedef union {
  struct {
    uint32 BfmChn3StatFlow                :4; 
    uint32 BfmChn3StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 BfmChn2StatFlow                :4; 
    uint32 BfmChn2StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 BfmChn1StatFlow                :4; 
    uint32 BfmChn1StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 BfmChn0StatFlow                :4; 
    uint32 BfmChn0StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaStatusBfmConfig;


typedef union {
  struct {
    uint32 DmaChn3StatFlow                :4; 
    uint32 DmaChn3StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 DmaChn2StatFlow                :4; 
    uint32 DmaChn2StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 DmaChn1StatFlow                :4; 
    uint32 DmaChn1StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 DmaChn0StatFlow                :4; 
    uint32 DmaChn0StatSelect              :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaStatusDmaConfig;


typedef union {
  struct {
    uint32 PipeIdle                       :1; 
                                              
    uint32 Reserved                       :11;
    uint32 ChanIdle3                      :1; 
                                              
    uint32 ChanIdle2                      :1; 
                                              
    uint32 ChanIdle1                      :1; 
                                              
    uint32 ChanIdle0                      :1; 
                                              
    uint32 FlowIdle                       :16;
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaStatusIdle;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 StsRamRead                     :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :3; 
    uint32 StsRamFlowId                   :4; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaStatusStsrdConfig;


typedef union {
  struct {
    uint32 Reserved                       :21;
    uint32 UbusIfStatus                   :1; 
    uint32 TkmIfStatus                    :1; 
    uint32 SegmenterStatus                :1; 
    uint32 BfmChan3Status                 :1; 
    uint32 BfmChan2Status                 :1; 
    uint32 BfmChan1Status                 :1; 
    uint32 BfmChan0Status                 :1; 
    uint32 DmaChan3Status                 :1; 
    uint32 DmaChan2Status                 :1; 
    uint32 DmaChan1Status                 :1; 
    uint32 DmaChan0Status                 :1; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaStatusWord;


typedef union {
  struct {
    uint32 Diag2MsHiSel                   :4; 
    uint32 Diag2PsHiSel                   :4; 
    uint32 Diag2MsLoSel                   :4; 
    uint32 Diag2PsLoSel                   :4; 
    uint32 Diag1MsHiSel                   :4; 
    uint32 Diag1PsHiSel                   :4; 
    uint32 Diag1MsLoSel                   :4; 
    uint32 Diag1PsLoSel                   :4; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaTestDiagselAux;


typedef union {
  struct {
    uint32 DiagmMsHiSel                   :4; 
    uint32 DiagmPsHiSel                   :4; 
    uint32 DiagmMsLoSel                   :4; 
    uint32 DiagmPsLoSel                   :4; 
    uint32 DiagmSegBusSel                 :4; 
                                              
    uint32 DiagmDmaBusSel                 :4; 
                                              
    uint32 DiagmBfmBusSel                 :4; 
                                              
    uint32 DiagmTkmUbusBusSel             :4; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaTestDiagselMain;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 DiagPsClkHiSel                 :4; 
    uint32 DiagPsClkLoSel                 :4; 
    uint32 DiagPortHiRegVer               :1; 
                                              
    uint32 DiagPortLoRegVer               :1; 
                                              
    uint32 Reserved2                      :2; 
    uint32 DiagClkEnMask                  :4; 
    uint32 DiagStartTriggerMask           :4; 
    uint32 DiagStopTriggerMask            :4; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaTestMemcapCntrl;


typedef union {
  struct {
    uint32 Reserved                       :3; 
    uint32 Diag2BitposSel                 :5; 
    uint32 Reserved2                      :3; 
    uint32 Diag1BitposSel                 :5; 
    uint32 Diag2GfuncSel                  :4; 
    uint32 Diag1GfuncSel                  :4; 
    uint32 Diag2TfuncSel                  :4; 
    uint32 Diag1TfuncSel                  :4; 
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaTestModeselAux;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 TkmIfNoackThreshold            :16;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaTkmThreshold;


typedef union {
  struct {
    uint32 Chan1FlowMask                  :16;
                                              
                                              
                                              
                                              
    uint32 Chan0FlowMask                  :16;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaUpiChn10FlowMask;


typedef union {
  struct {
    uint32 Chan3FlowMask                  :16;
                                              
                                              
                                              
                                              
    uint32 Chan2FlowMask                  :16;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaUpiChn32FlowMask;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 FlowMask                       :16;
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  SegdmaSegdmaUpiFlowMask;

typedef struct {
  SegdmaSegdmaConfig1                 Config1;                 
  uint32                              ConfigRsvd1;             
  uint32                              ConfigRsvd2;             
  uint32                              UtpDestAdr;              
  SegdmaSegdmaGntStatusBkdr           GntStatBkdr;             
  SegdmaSegdmaSequenceNum             SequenceNum;             
  SegdmaSegdmaDiscardTimer            DiscardTimerValue;       
  SegdmaSegdmaDmabfmThresholds        DmaBfmThresholds;        
  SegdmaSegdmaTkmThreshold            TkmThreshold;            
  SegdmaSegdmaResetControl            ResetControl;            
  uint32                              ConfigRsvd4;             
  uint32                              ConfigRsvd5;             
  SegdmaSegdmaMibResetFlowFC          MibResetFlows1512;       
  SegdmaSegdmaMibResetFlowB8          MibResetFlows118;        
  SegdmaSegdmaMibResetFlow74          MibResetFlows74;         
  SegdmaSegdmaMibResetFlow30          MibResetFlows30;         
  uint32                              ConfigRsvd6;             
  uint32                              ConfigRsvd7;             
  uint32                              ConfigRsvd8;             
  uint32                              ConfigRsvd9;             
  SegdmaSegdmaIrqStatus               IrqMainStatus;           
  uint32                              IrqMainMaskHost;         
  uint32                              IrqMainMaskUtp;          
  uint32                              IrqRsvd1;                
  SegdmaSegdmaUpiFlowMask             IrqUpiFlowMask;          
  SegdmaSegdmaUpiChn32FlowMask        IrqUpiChn32FlowMask;     
  SegdmaSegdmaUpiChn10FlowMask        IrqUpiChn10FlowMask;     
  uint32                              IrqRsvd2;                
  SegdmaSegdmaIrqAuxStatus            IrqAuxStatus;            
  uint32                              IrqAuxMask;              
  SegdmaSegdmaChanIrqStatus           IrqChanStatus;           
  SegdmaSegdmaChanIrqMask             IrqChanMask;             
  SegdmaSegdmaFlowIrqStatus           IrqFlow0Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow1Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow2Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow3Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow4Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow5Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow6Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow7Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow8Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow9Status;          
  SegdmaSegdmaFlowIrqStatus           IrqFlow10Status;         
  SegdmaSegdmaFlowIrqStatus           IrqFlow11Status;         
  SegdmaSegdmaFlowIrqStatus           IrqFlow12Status;         
  SegdmaSegdmaFlowIrqStatus           IrqFlow13Status;         
  SegdmaSegdmaFlowIrqStatus           IrqFlow14Status;         
  SegdmaSegdmaFlowIrqStatus           IrqFlow15Status;         
  uint32                              IrqFlow0Mask;            
  uint32                              IrqFlow1Mask;            
  uint32                              IrqFlow2Mask;            
  uint32                              IrqFlow3Mask;            
  uint32                              IrqFlow4Mask;            
  uint32                              IrqFlow5Mask;            
  uint32                              IrqFlow6Mask;            
  uint32                              IrqFlow7Mask;            
  uint32                              IrqFlow8Mask;            
  uint32                              IrqFlow9Mask;            
  uint32                              IrqFlow10Mask;           
  uint32                              IrqFlow11Mask;           
  uint32                              IrqFlow12Mask;           
  uint32                              IrqFlow13Mask;           
  uint32                              IrqFlow14Mask;           
  uint32                              IrqFlow15Mask;           
  SegdmaSegdmaFlowControl             Flow0Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow0NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow0NtkidsLq;           
  uint32                              Flow0Rsvd1;              
  SegdmaSegdmaFlowControl             Flow1Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow1NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow1NtkidsLq;           
  uint32                              Flow1Rsvd1;              
  SegdmaSegdmaFlowControl             Flow2Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow2NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow2NtkidsLq;           
  uint32                              Flow2Rsvd1;              
  SegdmaSegdmaFlowControl             Flow3Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow3NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow3NtkidsLq;           
  uint32                              Flow3Rsvd1;              
  SegdmaSegdmaFlowControl             Flow4Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow4NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow4NtkidsLq;           
  uint32                              Flow4Rsvd1;              
  SegdmaSegdmaFlowControl             Flow5Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow5NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow5NtkidsLq;           
  uint32                              Flow5Rsvd1;              
  SegdmaSegdmaFlowControl             Flow6Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow6NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow6NtkidsLq;           
  uint32                              Flow6Rsvd1;              
  SegdmaSegdmaFlowControl             Flow7Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow7NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow7NtkidsLq;           
  uint32                              Flow7Rsvd1;              
  SegdmaSegdmaFlowControl             Flow8Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow8NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow8NtkidsLq;           
  uint32                              Flow8Rsvd1;              
  SegdmaSegdmaFlowControl             Flow9Control;            
  SegdmaSegdmaFlowNumofTkidHq         Flow9NtkidsHq;           
  SegdmaSegdmaFlowNumofTkidLq         Flow9NtkidsLq;           
  uint32                              Flow9Rsvd1;              
  SegdmaSegdmaFlowControl             Flow10Control;           
  SegdmaSegdmaFlowNumofTkidHq         Flow10NtkidsHq;          
  SegdmaSegdmaFlowNumofTkidLq         Flow10NtkidsLq;          
  uint32                              Flow10Rsvd1;             
  SegdmaSegdmaFlowControl             Flow11Control;           
  SegdmaSegdmaFlowNumofTkidHq         Flow11NtkidsHq;          
  SegdmaSegdmaFlowNumofTkidLq         Flow11NtkidsLq;          
  uint32                              Flow11Rsvd1;             
  SegdmaSegdmaFlowControl             Flow12Control;           
  SegdmaSegdmaFlowNumofTkidHq         Flow12NtkidsHq;          
  SegdmaSegdmaFlowNumofTkidLq         Flow12NtkidsLq;          
  uint32                              Flow12Rsvd1;             
  SegdmaSegdmaFlowControl             Flow13Control;           
  SegdmaSegdmaFlowNumofTkidHq         Flow13NtkidsHq;          
  SegdmaSegdmaFlowNumofTkidLq         Flow13NtkidsLq;          
  uint32                              Flow13Rsvd1;             
  SegdmaSegdmaFlowControl             Flow14Control;           
  SegdmaSegdmaFlowNumofTkidHq         Flow14NtkidsHq;          
  SegdmaSegdmaFlowNumofTkidLq         Flow14NtkidsLq;          
  uint32                              Flow14Rsvd1;             
  SegdmaSegdmaFlowControl             Flow15Control;           
  SegdmaSegdmaFlowNumofTkidHq         Flow15NtkidsHq;          
  SegdmaSegdmaFlowNumofTkidLq         Flow15NtkidsLq;          
  uint32                              Flow15Rsvd1;             
  SegdmaSegdmaStatusDmaConfig         StatCntDmaConfig;        
  SegdmaSegdmaStatusBfmConfig         StatCntBfmConfig;        
  SegdmaSegdmaStatusStsrdConfig       StsRamReadConfig;        
  uint32                              StatusRsvd20c;           
  uint32                              StatusRsvd210;           
  uint32                              StatusRsvd214;           
  uint32                              StatusRsvd218;           
  uint32                              StatusRsvd21c;           
  uint32                              StatusRsvd220;           
  uint32                              StatusRsvd224;           
  uint32                              StatusRsvd228;           
  uint32                              StatusRsvd22c;           
  SegdmaSegdmaStatusIdle              IdleChanFlow;            
  SegdmaSegdmaChan32FlowIdle          IdleFlowChan32;          
  SegdmaSegdmaChan10FlowIdle          IdleFlowChan10;          
  SegdmaSegdmaStatusWord              StatusWord;              
  uint32                              StatusRsvd240;           
  uint32                              StatusRsvd244;           
  uint32                              StatusRsvd248;           
  uint32                              StatusRsvd24c;           
  uint32                              StatCntDmaChn3;          
  uint32                              StatCntDmaChn2;          
  uint32                              StatCntDmaChn1;          
  uint32                              StatCntDmaChn0;          
  uint32                              StatCntBfmChn3;          
  uint32                              StatCntBfmChn2;          
  uint32                              StatCntBfmChn1;          
  uint32                              StatCntBfmChn0;          
  uint32                              StatusStsRamWrd1;        
  uint32                              StatusStsRamWrd2;        
  uint32                              StatusStsRamWrd3;        
  uint32                              StatusStsRamWrd4;        
  uint32                              StatusStsRamWrd5;        
  uint32                              StatusStsRamWrd6;        
  uint32                              StatusRsvd288;           
  uint32                              StatusRsvd28c;           
  uint32                              StatusRsvd290;           
  uint32                              StatusRsvd294;           
  uint32                              StatusRsvd298;           
  uint32                              StatusRsvd29c;           
  uint32                              StatusRsvd2a0;           
  uint32                              StatusRsvd2a4;           
  uint32                              StatusRsvd2a8;           
  uint32                              StatusRsvd2ac;           
  uint32                              StatusRsvd2b0;           
  uint32                              StatusRsvd2b4;           
  uint32                              StatusRsvd2b8;           
  uint32                              StatusRsvd2bc;           
  uint32                              StatusRsvd2c0;           
  uint32                              StatusRsvd2c4;           
  uint32                              StatusRsvd2c8;           
  uint32                              StatusRsvd2cc;           
  uint32                              StatusRsvd2d0;           
  uint32                              StatusRsvd2d4;           
  uint32                              StatusRsvd2d8;           
  uint32                              StatusRsvd2dc;           
  uint32                              StatusRsvd2e0;           
  uint32                              StatusRsvd2e4;           
  uint32                              StatusRsvd2e8;           
  uint32                              StatusRsvd2ec;           
  uint32                              StatusRsvd2f0;           
  uint32                              StatusRsvd2f4;           
  uint32                              StatusRsvd2f8;           
  uint32                              StatusRsvd2fc;           
  uint32                              MibFlow0BytesDis;        
  uint32                              MibFlow0TkidsDis;        
  uint32                              MibFlow0TkidsProc;       
  uint32                              MibFlow0Rsvd;            
  uint32                              MibFlow0Ch0segsProc;     
  uint32                              MibFlow0Ch1segsProc;     
  uint32                              MibFlow0Ch2segsProc;     
  uint32                              MibFlow0Ch3segsProc;     
  uint32                              MibFlow1BytesDis;        
  uint32                              MibFlow1TkidsDis;        
  uint32                              MibFlow1TkidsProc;       
  uint32                              MibFlow1Rsvd;            
  uint32                              MibFlow1Ch0segsProc;     
  uint32                              MibFlow1Ch1segsProc;     
  uint32                              MibFlow1Ch2segsProc;     
  uint32                              MibFlow1Ch3segsProc;     
  uint32                              MibFlow2BytesDis;        
  uint32                              MibFlow2TkidsDis;        
  uint32                              MibFlow2TkidsProc;       
  uint32                              MibFlow2Rsvd;            
  uint32                              MibFlow2Ch0segsProc;     
  uint32                              MibFlow2Ch1segsProc;     
  uint32                              MibFlow2Ch2segsProc;     
  uint32                              MibFlow2Ch3segsProc;     
  uint32                              MibFlow3BytesDis;        
  uint32                              MibFlow3TkidsDis;        
  uint32                              MibFlow3TkidsProc;       
  uint32                              MibFlow3Rsvd;            
  uint32                              MibFlow3Ch0segsProc;     
  uint32                              MibFlow3Ch1segsProc;     
  uint32                              MibFlow3Ch2segsProc;     
  uint32                              MibFlow3Ch3segsProc;     
  uint32                              MibFlow4BytesDis;        
  uint32                              MibFlow4TkidsDis;        
  uint32                              MibFlow4TkidsProc;       
  uint32                              MibFlow4Rsvd;            
  uint32                              MibFlow4Ch0segsProc;     
  uint32                              MibFlow4Ch1segsProc;     
  uint32                              MibFlow4Ch2segsProc;     
  uint32                              MibFlow4Ch3segsProc;     
  uint32                              MibFlow5BytesDis;        
  uint32                              MibFlow5TkidsDis;        
  uint32                              MibFlow5TkidsProc;       
  uint32                              MibFlow5Rsvd;            
  uint32                              MibFlow5Ch0segsProc;     
  uint32                              MibFlow5Ch1segsProc;     
  uint32                              MibFlow5Ch2segsProc;     
  uint32                              MibFlow5Ch3segsProc;     
  uint32                              MibFlow6BytesDis;        
  uint32                              MibFlow6TkidsDis;        
  uint32                              MibFlow6TkidsProc;       
  uint32                              MibFlow6Rsvd;            
  uint32                              MibFlow6Ch0segsProc;     
  uint32                              MibFlow6Ch1segsProc;     
  uint32                              MibFlow6Ch2segsProc;     
  uint32                              MibFlow6Ch3segsProc;     
  uint32                              MibFlow7BytesDis;        
  uint32                              MibFlow7TkidsDis;        
  uint32                              MibFlow7TkidsProc;       
  uint32                              MibFlow7Rsvd;            
  uint32                              MibFlow7Ch0segsProc;     
  uint32                              MibFlow7Ch1segsProc;     
  uint32                              MibFlow7Ch2segsProc;     
  uint32                              MibFlow7Ch3segsProc;     
  uint32                              MibFlow8BytesDis;        
  uint32                              MibFlow8TkidsDis;        
  uint32                              MibFlow8TkidsProc;       
  uint32                              MibFlow8Rsvd;            
  uint32                              MibFlow8Ch0segsProc;     
  uint32                              MibFlow8Ch1segsProc;     
  uint32                              MibFlow8Ch2segsProc;     
  uint32                              MibFlow8Ch3segsProc;     
  uint32                              MibFlow9BytesDis;        
  uint32                              MibFlow9TkidsDis;        
  uint32                              MibFlow9TkidsProc;       
  uint32                              MibFlow9Rsvd;            
  uint32                              MibFlow9Ch0segsProc;     
  uint32                              MibFlow9Ch1segsProc;     
  uint32                              MibFlow9Ch2segsProc;     
  uint32                              MibFlow9Ch3segsProc;     
  uint32                              MibFlow10BytesDis;       
  uint32                              MibFlow10TkidsDis;       
  uint32                              MibFlow10TkidsProc;      
  uint32                              MibFlow10Rsvd;           
  uint32                              MibFlow10Ch0segsProc;    
  uint32                              MibFlow10Ch1segsProc;    
  uint32                              MibFlow10Ch2segsProc;    
  uint32                              MibFlow10Ch3segsProc;    
  uint32                              MibFlow11BytesDis;       
  uint32                              MibFlow11TkidsDis;       
  uint32                              MibFlow11TkidsProc;      
  uint32                              MibFlow11Rsvd;           
  uint32                              MibFlow11Ch0segsProc;    
  uint32                              MibFlow11Ch1segsProc;    
  uint32                              MibFlow11Ch2segsProc;    
  uint32                              MibFlow11Ch3segsProc;    
  uint32                              MibFlow12BytesDis;       
  uint32                              MibFlow12TkidsDis;       
  uint32                              MibFlow12TkidsProc;      
  uint32                              MibFlow12Rsvd;           
  uint32                              MibFlow12Ch0segsProc;    
  uint32                              MibFlow12Ch1segsProc;    
  uint32                              MibFlow12Ch2segsProc;    
  uint32                              MibFlow12Ch3segsProc;    
  uint32                              MibFlow13BytesDis;       
  uint32                              MibFlow13TkidsDis;       
  uint32                              MibFlow13TkidsProc;      
  uint32                              MibFlow13Rsvd;           
  uint32                              MibFlow13Ch0segsProc;    
  uint32                              MibFlow13Ch1segsProc;    
  uint32                              MibFlow13Ch2segsProc;    
  uint32                              MibFlow13Ch3segsProc;    
  uint32                              MibFlow14BytesDis;       
  uint32                              MibFlow14TkidsDis;       
  uint32                              MibFlow14TkidsProc;      
  uint32                              MibFlow14Rsvd;           
  uint32                              MibFlow14Ch0segsProc;    
  uint32                              MibFlow14Ch1segsProc;    
  uint32                              MibFlow14Ch2segsProc;    
  uint32                              MibFlow14Ch3segsProc;    
  uint32                              MibFlow15BytesDis;       
  uint32                              MibFlow15TkidsDis;       
  uint32                              MibFlow15TkidsProc;      
  uint32                              MibFlow15Rsvd;           
  uint32                              MibFlow15Ch0segsProc;    
  uint32                              MibFlow15Ch1segsProc;    
  uint32                              MibFlow15Ch2segsProc;    
  uint32                              MibFlow15Ch3segsProc;    
  SegdmaSegdmaTestDiagselMain         TestDiagMainSelect;      
  SegdmaSegdmaTestDiagselAux          TestDiagAuxSelect;       
  SegdmaSegdmaTestModeselAux          TestDiagAuxMode;         
  SegdmaSegdmaTestMemcapCntrl         TestDiagMemcapCntrl;     
  uint32                              TestDiag11mask;          
  uint32                              TestDiag10mask;          
  uint32                              TestDiag21mask;          
  uint32                              TestDiag20mask;          
  uint32                              TestRsvd1;               
  uint32                              TestRsvd2;               
  uint32                              TestDiag1CntEvents;      
  uint32                              TestDiag2CntEvents;      
  uint32                              TestDiagMainRdback;      
  uint32                              TestDiag1Rdback;         
  uint32                              TestDiag2Rdback;         
  uint32                              TestRsvd3;               
  uint32                              TestDiag1CntRdback;      
  uint32                              TestDiag2CntRdback;      
  uint32                              TestRsvd4;               
  uint32                              TestRsvd5;               
}  SegdmaSegdmaRegs;

#endif 



