// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         tc_top.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef TC_TOP_H__
#define TC_TOP_H__



typedef union {
  struct {
    uint8  Reserved                       :4; 
    uint8  AclReverse                     :1; 
                                              
                                              
                                              
    uint8  AclGenerate                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  AclClrAdrsCnt                  :1; 
                                              
                                              
    uint8  AclSwControl                   :1; 
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAclControl;


typedef union {
  struct {
    uint16 Reserved                       :6; 
    uint16 AclHopsPerFrame                :10;
                                              
                                              
                                              
  } Bits;
  uint16 Reg16;
}  TcTcAclHopsPerFrame;


typedef union {
  struct {
    uint16 Reserved                       :11;
    uint16 AclHopsPerIntrvl               :5; 
  } Bits;
  uint16 Reg16;
}  TcTcAclHopsPerIntrvl;


typedef union {
  struct {
    uint8  Reserved                       :5; 
    uint8  IrqMaskAclSts                  :3; 
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAclIrqMask;


typedef union {
  struct {
    uint8  Reserved                       :5; 
    uint8  AclNacUcdErr                   :1; 
                                              
                                              
                                              
    uint8  AclNhcEq0                      :1; 
                                              
                                              
    uint8  AclGenerateDone                :1; 
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAclIrqStatus;


typedef union {
  struct {
    uint8  Reserved                       :1; 
    uint8  AclNhcM1                       :7; 
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAclNhcM1;


typedef union {
  struct {
    uint8  Reserved                       :1; 
    uint8  AclRam                         :7; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAclRam;


typedef union {
  struct {
    uint8  Reserved                       :6; 
    uint8  AclSmStatus                    :2; 
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAclSmStatus;


typedef union {
  struct {
    uint8  TrcUseDsLock                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  TrcCcInit                      :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  TimShiftMsSize                 :1; 
                                              
                                              
    uint8  TimCheckSnap                   :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  SyncMessageEnable              :1; 
                                              
                                              
                                              
    uint8  RfBurstExtEn                   :1; 
                                              
                                              
                                              
                                              
    uint8  UsFifoMode                     :1; 
                                              
                                              
    uint8  ProgQpskEn                     :1; 
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAuxControl0;


typedef union {
  struct {
    uint8  TmSelectMsSys                  :1; 
                                              
                                              
                                              
    uint8  SprdShiftCtrlEn                :1; 
                                              
                                              
                                              
                                              
    uint8  TmSelectMsFrm                  :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  RfBurstIntEn                   :1; 
                                              
    uint8  UpdateMsSizeAuto               :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  TimPhyHandShakeOn              :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  DriftCompReset                 :1; 
                                              
                                              
    uint8  K0RamEnable                    :1; 
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAuxControl1;


typedef union {
  struct {
    uint8  DiagPortClksysPhaseSel         :2; 
                                              
                                              
                                              
    uint8  Reserved                       :1; 
    uint8  DiagXmitTwoEdges               :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  DiagSelectInternalReg          :1; 
                                              
                                              
    uint8  DiagSwTriggerEn                :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  DiagSwapEn                     :1; 
                                              
                                              
    uint8  Diag32BitMode                  :1; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAuxControl2;


typedef union {
  struct {
    uint8  ResetMisr                      :1; 
                                              
    uint8  BabbleCntrlSmReset             :1; 
                                              
    uint8  ClrSnapshot                    :1; 
                                              
                                              
                                              
                                              
    uint8  TimForceSyncLoss               :1; 
                                              
                                              
                                              
    uint8  Reset1024Tim                   :1; 
                                              
                                              
                                              
                                              
    uint8  Reset1024Trc                   :1; 
                                              
                                              
    uint8  DecoupleTimSysReset            :1; 
                                              
                                              
                                              
                                              
    uint8  DecoupleTrcSysReset            :1; 
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAuxControl3;


typedef union {
  struct {
    uint16 DiagIrq                        :1; 
                                              
                                              
                                              
                                              
    uint16 BurstOutput                    :1; 
                                              
                                              
                                              
                                              
    uint16 MltStart                       :1; 
                                              
                                              
                                              
                                              
    uint16 MltDone                        :1; 
                                              
                                              
                                              
    uint16 AstDump                        :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint16 AstInPast                      :1; 
                                              
                                              
                                              
                                              
    uint16 TrcPdStop                      :1; 
                                              
                                              
                                              
                                              
    uint16 TrcCc                          :1; 
                                              
                                              
                                              
                                              
                                              
    uint16 MltGtThreshold                 :1; 
                                              
                                              
                                              
                                              
                                              
    uint16 MltLtThreshold                 :1; 
                                              
                                              
                                              
                                              
                                              
    uint16 SnapInFuture                   :1; 
                                              
                                              
                                              
    uint16 SnapOutOfBounds                :1; 
                                              
                                              
                                              
                                              
                                              
    uint16 SnapJammed                     :1; 
                                              
                                              
                                              
                                              
    uint16 SnapRx                         :1; 
                                              
                                              
                                              
                                              
    uint16 SnapCheckBad                   :1; 
                                              
                                              
                                              
                                              
    uint16 SnapCheckDone                  :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint16 Reg16;
}  TcTcAuxIrqStatus;


typedef union {
  struct {
    uint8  Reserved                       :1; 
    uint8  SnapshotFutureLimit            :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  Reserved2                      :1; 
    uint8  SnapshotPastLimit              :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAuxSnapshotLimits;


typedef union {
  struct {
    uint32 UsfPipeEmpty                   :1; 
                                              
                                              
                                              
    uint32 SprPipeEmpty                   :1; 
                                              
    uint32 TimPipeEmpty                   :1; 
                                              
    uint32 FrmPipeEmpty                   :1; 
                                              
    uint32 PrePipeEmpty                   :1; 
                                              
    uint32 TcmPipeEmpty                   :1; 
                                              
    uint32 ScrPipeEmpty                   :1; 
                                              
    uint32 FecPipeEmpty                   :1; 
                                              
    uint32 TcPipeEmpty                    :1; 
                                              
    uint32 UsphyPipeEmpty                 :1; 
                                              
    uint32 SymPipeEmpty                   :1; 
                                              
    uint32 TencPipeEmpty                  :1; 
                                              
    uint32 Reserved                       :4; 
    uint32 TrellisAtZero                  :1; 
                                              
    uint32 Reserved2                      :7; 
    uint32 UsphyTcTxoe                    :1; 
                                              
    uint32 Reserved3                      :3; 
    uint32 TimMltBusy                     :1; 
                                              
                                              
    uint32 TimSuppressUcdRx               :1; 
                                              
                                              
    uint32 TimWait4Ir                     :1; 
                                              
                                              
                                              
    uint32 TimCatchupInProgress           :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcAuxStatus;


typedef union {
  struct {
    uint8  Reserved                       :3; 
    uint8  CatchupJamLookAhead            :1; 
                                              
                                              
                                              
    uint8  IgnoreUcdsDsmac                :1; 
                                              
                                              
                                              
    uint8  CatchupCheckRegfile            :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  CatchupJamRegfile              :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  RngAdjImmediate                :1; 
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAuxTimCntrl;


typedef union {
  struct {
    uint8  Reserved                       :1; 
    uint8  TimReadDelay                   :3; 
                                              
                                              
                                              
    uint8  Reserved2                      :1; 
    uint8  TimDataValidDelay              :3; 
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcAuxUsPhyIfCntrl;


typedef union {
  struct {
    uint8  Reserved                       :4; 
    uint8  OutputBurstCount               :4; 
                                              
  } Bits;
  uint8 Reg8;
}  TcTcBrstLenCount;


typedef union {
  struct {
    uint32 Reserved                       :12;
    uint32 BurstLengthInSymbols           :20;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcBrstLenInSymbols;


typedef union {
  struct {
    uint32 Pemode                         :1; 
                                              
                                              
                                              
                                              
    uint32 Pqmode                         :2; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Pqscl                          :1; 
                                              
                                              
                                              
    uint32 Emode                          :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Qmode                          :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :3; 
    uint32 RsEn                           :1; 
                                              
                                              
    uint32 Reserved2                      :4; 
    uint32 Slcw                           :1; 
                                              
                                              
                                              
    uint32 Reserved3                      :2; 
    uint32 RsT                            :5; 
                                              
                                              
                                              
    uint32 RsN                            :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcBurstProfileFrmt0;


typedef union {
  struct {
    uint32 Reserved                       :5; 
    uint32 PreambleLength                 :11;
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :5; 
    uint32 PreambleOffset                 :11;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcBurstProfileFrmt1;


typedef union {
  struct {
    uint32 ProgQpskScalePreamble          :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ProgQpskScalePayload           :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ScramblerSeed                  :23;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ScramblerOn                    :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcBurstProfileFrmt2;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 InterleaveDepth                :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 MaxInterleaveDepth             :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :8; 
  } Bits;
  uint32 Reg32;
}  TcTcBurstProfileFrmt3;


typedef union {
  struct {
    uint32 Reserved                       :4; 
    uint32 UseImpluse                     :1; 
                                              
                                              
                                              
    uint32 PmapSel                        :1; 
                                              
    uint32 SpeaderOn                      :1; 
                                              
    uint32 TcmOn                          :1; 
    uint32 CdmaCpsf                       :8; 
    uint32 Reserved2                      :2; 
    uint32 CdmaSiss                       :6; 
                                              
                                              
    uint32 Reserved3                      :2; 
    uint32 KGcd                           :6; 
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcBurstProfileFrmt4;


typedef union {
  struct {
    uint32 Reserved                       :5; 
    uint32 PhyOhslen                      :11;
                                              
                                              
                                              
    uint32 ShiftCntrlEn                   :1; 
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :3; 
    uint32 BbScale                        :12;
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcBurstProfileFrmt5;


typedef union {
  struct {
    uint8  BitReversal                    :1; 
    uint8  RsPolySel                      :1; 
    uint8  Sr                             :1; 
                                              
                                              
    uint8  ScrInvPrbs                     :1; 
                                              
    uint8  SymDsMaps                      :1; 
                                              
    uint8  SymStarVueEn                   :1; 
    uint8  SymQpskPayScale                :1; 
                                              
                                              
    uint8  SymQdctl                       :1; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcControl0;


typedef union {
  struct {
    uint8  TcmRet2ZeroMode                :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  MisrSel                        :1; 
                                              
                                              
                                              
    uint8  UsFifoReset                    :1; 
                                              
                                              
    uint8  TmWfs                          :1; 
                                              
    uint8  Docsis2Pt0Enable               :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  DavicMacEnable                 :1; 
    uint8  Reserved                       :1; 
    uint8  ScdmaEnable                    :1; 
  } Bits;
  uint8 Reg8;
}  TcTcControl1;


typedef union {
  struct {
    uint8  TcmB2sTdmaMap                  :1; 
                                              
                                              
    uint8  PreambleInitDone               :1; 
    uint8  FecPadValue                    :1; 
                                              
                                              
                                              
                                              
    uint8  SprdLt128Codes                 :1; 
                                              
                                              
                                              
    uint8  Reserved                       :2; 
    uint8  SrRdEnable                     :1; 
                                              
                                              
                                              
                                              
    uint8  Ssr                            :1; 
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcControl2;


typedef union {
  struct {
    uint32 ModuleSelectLow                :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 PortSelectLow                  :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ModuleSelectHi                 :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 PortSelectHi                   :5; 
                                              
                                              
                                              
                                              
    uint32 Reserved                       :8; 
    uint32 DiagPsClkHighSel               :4; 
                                              
    uint32 DiagPsClkLowSel                :4; 
                                              
  } Bits;
  uint32 Reg32;
}  TcTcDiagPortCntrl;


typedef union {
  struct {
    uint8  Reserved                       :7; 
    uint8  DiagSwTrigger                  :1; 
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcDiagTrigger;


typedef union {
  struct {
    uint32 DsSymbolClkDivider             :16;
                                              
                                              
                                              
                                              
                                              
    uint32 MasterClkDivider               :16;
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcDsMstrClkDvd;


typedef union {
  struct {
    uint16 Reserved                       :1; 
    uint16 SprHopperSeed                  :15;
                                              
                                              
  } Bits;
  uint16 Reg16;
}  TcTcHopperSeed;


typedef union {
  struct {
    uint8  Reserved                       :4; 
    uint8  Nssu                           :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  UnusedCodes                    :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcInactiveCodes;


typedef union {
  struct {
    uint32 UcdPhyRdy                      :1; 
                                              
                                              
    uint32 UcdTcRdy                       :1; 
                                              
                                              
    uint32 MapperNullFrame                :1; 
                                              
                                              
                                              
    uint32 MapperPrepend                  :1; 
                                              
                                              
                                              
                                              
    uint32 FramerSprdOnOff                :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FramerBurstToLong              :1; 
                                              
                                              
                                              
                                              
    uint32 FramerBurstLate                :1; 
                                              
                                              
                                              
                                              
    uint32 FecSeqNumError                 :1; 
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag7                  :1; 
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag6                  :1; 
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag5                  :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag4                  :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag3                  :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag2                  :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag1                  :1; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 TimErrorFlag0                  :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 TrcThresholdRise               :1; 
                                              
                                              
                                              
                                              
    uint32 TrcThresholdFall               :1; 
                                              
                                              
                                              
                                              
    uint32 RangeAdjAck                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 TimCntrlIrqAdrs1a              :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 TrcPulseLostRise               :1; 
                                              
                                              
    uint32 TrcSyncInconsistent            :1; 
                                              
                                              
                                              
    uint32 TrcK1OutOfBounds               :1; 
                                              
                                              
    uint32 TrcSyncValid                   :1; 
                                              
    uint32 PreambleZeroPayload            :1; 
                                              
                                              
                                              
                                              
    uint32 FramerUseImpulseErr            :1; 
                                              
                                              
                                              
                                              
    uint32 FramerNotComplete              :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 FrameBbScaleErr                :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 AuxIrqAdrs                     :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 AclIrq                         :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 TimCntrlSyncFall               :1; 
                                              
                                              
                                              
    uint32 BabbleCntrl                    :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcIrqStatus;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 MltAboveThreshold              :8; 
                                              
                                              
                                              
    uint32 MltBelowThreshold              :8; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcMltAboveBelowCounts;


typedef union {
  struct {
    uint32 MltExceedsAboveThresh          :8; 
                                              
                                              
                                              
    uint32 MltSampleSizeAbove             :8; 
                                              
                                              
                                              
    uint32 MltFallsBelowThresh            :8; 
                                              
                                              
                                              
    uint32 MltSampleSizeBelow             :8; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcMltAboveBelowThresh;


typedef union {
  struct {
    uint32 MltClear                       :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 LaCountersJammed               :1; 
                                              
                                              
                                              
    uint32 Reserved                       :3; 
    uint32 LookAheadLogicEn               :1; 
                                              
                                              
                                              
                                              
    uint32 MltShiftCntrl                  :2; 
                                              
                                              
    uint32 Reserved2                      :24;
  } Bits;
  uint32 Reg32;
}  TcTcMltControl;


typedef union {
  struct {
    uint32 MinislotSize                   :16;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FrameSize                      :16;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcMsFrmSize;


typedef union {
  struct {
    uint16 Reserved                       :3; 
    uint16 SymbolsPerMs                   :13;
                                              
                                              
                                              
                                              
  } Bits;
  uint16 Reg16;
}  TcTcNumSymPerMs;


typedef union {
  struct {
    uint8  Reserved                       :6; 
    uint8  DiffEncOverride                :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  ScrSeedOverride                :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcOverrideTest;


typedef union {
  struct {
    uint8  Reserved                       :2; 
    uint8  TimResetTime                   :1; 
                                              
                                              
    uint8  TrcReset                       :1; 
                                              
                                              
    uint8  SprdReset                      :1; 
                                              
                                              
    uint8  TimResetBurst                  :1; 
                                              
                                              
                                              
    uint8  RegFileReset                   :1; 
                                              
                                              
    uint8  LogicReset                     :1; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcResetControl;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 PrbsCfg                        :23;
                                              
                                              
    uint32 PrbsTypeSel                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcScrPrbsCfg;


typedef union {
  struct {
    uint16 SnMismatch                     :1; 
                                              
                                              
                                              
    uint16 SnOutSource                    :1; 
                                              
                                              
    uint16 Reserved                       :2; 
    uint16 ActualSn                       :4; 
                                              
                                              
    uint16 Reserved2                      :4; 
    uint16 ExpectedSn                     :4; 
                                              
  } Bits;
  uint16 Reg16;
}  TcTcSeqNumStatus;


typedef union {
  struct {
    uint8  Reserved                       :2; 
    uint8  Sipf                           :6; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcSprIntvlPerFrame;


typedef union {
  struct {
    uint16 Reserved                       :6; 
    uint16 SprHopErr                      :1; 
                                              
                                              
    uint16 SprHopSync                     :1; 
                                              
                                              
    uint16 Reserved2                      :8; 
  } Bits;
  uint16 Reg16;
}  TcTcSprdStatus;


typedef union {
  struct {
    uint8  PatternSelect                  :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  BurstProfileSelect             :3; 
                                              
                                              
    uint8  CycleBurstBank                 :1; 
                                              
                                              
                                              
                                              
                                              
    uint8  TestModuleEnable               :1; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcTestModuleCntrl;


typedef union {
  struct {
    uint32 SnapInFuture                   :1; 
                                              
                                              
                                              
    uint32 DsphyBaudLock                  :1; 
                                              
    uint32 TrcBadSample                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :1; 
    uint32 DumpCounter                    :4; 
                                              
    uint32 Reserved2                      :4; 
    uint32 SyncInBeg                      :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 SyncInMid                      :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ContTx                         :1; 
                                              
                                              
                                              
                                              
    uint32 RangeAdjSync                   :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ExpTicsPerMs                   :3; 
                                              
                                              
                                              
                                              
                                              
    uint32 TimCntrlStandAlone             :1; 
                                              
                                              
                                              
    uint32 Reserved3                      :1; 
    uint32 DumpBurst                      :1; 
                                              
                                              
                                              
    uint32 SyncEnable                     :1; 
                                              
                                              
                                              
                                              
    uint32 CatchupJamUcd                  :1; 
                                              
                                              
                                              
                                              
    uint32 Reserved4                      :8; 
  } Bits;
  uint32 Reg32;
}  TcTcTimCntrl;


typedef union {
  struct {
    uint16 TstmpSyncRise                  :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint16 TstmpSyncFall                  :1; 
                                              
    uint16 TimCntrlSyncRise               :1; 
                                              
    uint16 TimCntrlSyncFall               :1; 
                                              
    uint16 TimDataNoPrepend               :1; 
                                              
    uint16 PrependFifoOverflow            :1; 
    uint16 BadPipe                        :1; 
                                              
                                              
                                              
    uint16 BadSnapCheck                   :1; 
                                              
    uint16 Reserved                       :6; 
    uint16 TelecomSaturated               :1; 
                                              
    uint16 BurstOverlap                   :1; 
                                              
  } Bits;
  uint16 Reg16;
}  TcTcTimIrqStatus;


typedef union {
  struct {
    uint8  Reserved                       :2; 
    uint8  TmLfsrPolySel                  :2; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint8  TmLfsrPrbsSel                  :1; 
                                              
                                              
                                              
    uint8  TmLfsrSeedOvr                  :1; 
                                              
                                              
                                              
    uint8  TmLfsrInvPrbs                  :1; 
                                              
    uint8  TmLfsrEn                       :1; 
                                              
                                              
  } Bits;
  uint8 Reg8;
}  TcTcTmLfsrCntrl;


typedef union {
  struct {
    uint32 TrcClkDiffLatch                :16;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 TrcClkDiff                     :16;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcTrcClkDiff;


typedef union {
  struct {
    uint32 TimingMasterEnable             :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :2; 
    uint32 NewK0RamCoeff                  :1; 
                                              
    uint32 ForceAcq                       :1; 
                                              
    uint32 JamSyncMessage                 :1; 
                                              
                                              
    uint32 ClearLoop                      :1; 
                                              
    uint32 InitSymbolCounters             :1; 
                                              
                                              
    uint32 Source1024Domain               :1; 
                                              
                                              
    uint32 ReferenceSource                :1; 
                                              
                                              
    uint32 LineEstimationEn               :1; 
                                              
                                              
    uint32 AutoLpu                        :1; 
                                              
    uint32 Syn4X8X                        :1; 
                                              
                                              
                                              
    uint32 Reserved2                      :1; 
    uint32 TrcMode                        :1; 
                                              
    uint32 OpenLoop                       :1; 
                                              
                                              
    uint32 Reserved3                      :3; 
    uint32 VoipSel                        :1; 
                                              
                                              
    uint32 VoipSpl                        :2; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 VoipDiv                        :2; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved4                      :2; 
    uint32 NcoDvd                         :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 BlkSize                        :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcTrcCntrl0;


typedef union {
  struct {
    uint32 Reserved                       :3; 
    uint32 K1Offset                       :5; 
                                              
                                              
    uint32 Reserved2                      :3; 
    uint32 TrcPhaseErrThreshold           :5; 
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved3                      :3; 
    uint32 K0                             :5; 
                                              
                                              
                                              
                                              
    uint32 Reserved4                      :3; 
    uint32 K1                             :5; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcTrcCntrl1;


typedef union {
  struct {
    uint32 Reserved                       :3; 
    uint32 DiagFlavor                     :1; 
                                              
    uint32 Reserved2                      :3; 
    uint32 DiagDyn                        :1; 
                                              
    uint32 Reserved3                      :15;
    uint32 K0RamInit                      :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved4                      :8; 
  } Bits;
  uint32 Reg32;
}  TcTcTrcCntrl3;


typedef union {
  struct {
    uint32 SymbolRate                     :2; 
                                              
                                              
                                              
                                              
    uint32 MacAdvanceSize                 :2; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 TrcLockStatus                  :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 PulseLost                      :1; 
                                              
                                              
                                              
                                              
    uint32 TstmpInSync                    :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 TimCntrlInSync                 :1; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :24;
  } Bits;
  uint32 Reg32;
}  TcTcTrcInsyncStatus;


typedef union {
  struct {
    uint32 TrcNumofSynMsg                 :8; 
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :24;
  } Bits;
  uint32 Reg32;
}  TcTcTrcNumofSyncMsg;


typedef union {
  struct {
    uint32 TrcInstPhsErrLsbs              :8; 
                                              
                                              
                                              
                                              
    uint32 TrcInstPhsErrMsbs              :2; 
                                              
                                              
                                              
                                              
    uint32 TrcAcqLoopStatus               :6; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :4; 
    uint32 TrcTcomShiftCntrl              :4; 
                                              
    uint32 Reserved2                      :5; 
    uint32 TrcTcomPow2Div                 :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TcTcTrcStatusTcomCntrl;

typedef struct {
  TcTcControl0                        Control0;                
  TcTcControl1                        Control1;                
  TcTcControl2                        Control2;                
  TcTcResetControl                    ResetControl;            
  uint8                               RfBurstLead;             
  uint8                               RfBurstLag;              
  uint8                               RfBurstSpare;            
  TcTcInactiveCodes                   InactiveCodes;           
  uint8                               CodesPerMs;              
  TcTcSprIntvlPerFrame                SprIntvlPerFrame;        
  TcTcHopperSeed                      HopperSeed;              
  TcTcScrPrbsCfg                      ScrPrbsCfg;              
  uint8                               ActiveCodes;             
  uint8                               NumMsPerFrame;           
  TcTcNumSymPerMs                     NumSymPerMs;             
  TcTcSprdStatus                      SpreaderStatus;          
  uint16                              MisrRdback;              
  TcTcSeqNumStatus                    SequenceNumberStatus;    
  TcTcTimIrqStatus                    TimingControlIrqStatus;  
  uint16                              TimingControlIrqMask;    
  uint16                              BabbleControlSlop;       
  uint32                              Reserved2023;            
  TcTcDiagPortCntrl                   DiagPortCntrl;           
  TcTcTrcInsyncStatus                 TrcInsyncStatus;         
  uint32                              DiagPortRdback;          
  TcTcTestModuleCntrl                 TestModuleCntrl;         
  uint8                               TmSpare8;                
  uint8                               TmBurstLenInMs;          
  uint8                               TmDeadTimeInMs;          
  uint16                              TmPayLenInBytes;         
  uint8                               TmAdvTimeInMs;           
  uint8                               TmSpare81;               
  uint16                              TmPattern1;              
  uint16                              TmPattern2;              
  uint16                              TmPattern3;              
  uint8                               TmNumBurstToXmit;        
  TcTcOverrideTest                    TmOverrideTest;          
  uint32                              Reserved4043;            
  uint32                              Reserved4447;            
  uint32                              Reserved484b;            
  uint32                              Reserved4c4f;            
  TcTcAclControl                      AclControl;              
  uint8                               AclSpare1;               
  TcTcAclSmStatus                     AclSmStatus;             
  TcTcAclNhcM1                        AclNhcM1;                
  TcTcAclHopsPerFrame                 AclHopsPerFrame;         
  TcTcAclHopsPerIntrvl                AclHopsPerIntrvl;        
  TcTcAclIrqStatus                    AclIrqStatus;            
  TcTcAclIrqMask                      AclIrqMask;              
  uint8                               AclSpare2;               
  TcTcAclRam                          AclRam;                  
  uint32                              AclVector;               
  TcTcMsFrmSize                       MinislotFrameSize;       
  uint32                              MacAdvanceTime;          
  uint32                              FramerAdvanceTime;       
  TcTcTimCntrl                        TimCntrl;                
                                                                 
  TcTcIrqStatus                       IrqStatus;               
  uint32                              IrqMaskCpu;              
  uint32                              IrqMaskUsMac;            
  uint32                              Reserved7c7f;            
  TcTcTrcCntrl0                       TrcCntrl0;               
                                                                 
  TcTcTrcCntrl1                       TrcCntrl1;               
                                                                 
  uint32                              Reserved888b;            
  uint32                              TrcNcoCenterFreq;        
  TcTcDsMstrClkDvd                    TrcDsMstrClkDvd;         
  uint32                              TrcRangingOffset;        
  TcTcTrcCntrl3                       TrcCntrl3;               
                                                                 
  uint32                              Reserved9c9f;            
  uint32                              TrcAcqFreq;              
  TcTcTrcNumofSyncMsg                 TrcNumofSynMsg;          
                                                                 
  TcTcTrcStatusTcomCntrl              TrcStatusTcomCntrl;      
  uint32                              TrcTelecomScale;         
  uint32                              TrcTelecomFcw;           
  uint32                              ReservedB4B7;            
  uint32                              ReservedB8Bb;            
  uint32                              ReservedBcBf;            
  uint32                              K0Ram;                   
  uint8                               Pad0[0x3c];
  TcTcBurstProfileFrmt0               BurstBank0Qam;           
  TcTcBurstProfileFrmt1               BurstBank0Pre;           
  TcTcBurstProfileFrmt2               BurstBank0ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank0InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank0MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank0OhslenBbscale; 
                                                                 
  uint32                              Reserved11811b;          
  uint32                              Reserved11c11f;          
  TcTcBurstProfileFrmt0               BurstBank1Qam;           
  TcTcBurstProfileFrmt1               BurstBank1Pre;           
  TcTcBurstProfileFrmt2               BurstBank1ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank1InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank1MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank1OhslenBbscale; 
                                                                 
  uint32                              Reserved13813b;          
  uint32                              Reserved13c13f;          
  TcTcBurstProfileFrmt0               BurstBank2Qam;           
  TcTcBurstProfileFrmt1               BurstBank2Pre;           
  TcTcBurstProfileFrmt2               BurstBank2ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank2InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank2MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank2OhslenBbscale; 
                                                                 
  uint32                              Reserved15815b;          
  uint32                              Reserved15c15f;          
  TcTcBurstProfileFrmt0               BurstBank3Qam;           
  TcTcBurstProfileFrmt1               BurstBank3Pre;           
  TcTcBurstProfileFrmt2               BurstBank3ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank3InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank3MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank3OhslenBbscale; 
                                                                 
  uint32                              Reserved17817b;          
  uint32                              Reserved17c17f;          
  TcTcBurstProfileFrmt0               BurstBank4Qam;           
  TcTcBurstProfileFrmt1               BurstBank4Pre;           
  TcTcBurstProfileFrmt2               BurstBank4ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank4InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank4MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank4OhslenBbscale; 
                                                                 
  uint32                              Reserved19819b;          
  uint32                              Reserved19c19f;          
  TcTcBurstProfileFrmt0               BurstBank5Qam;           
  TcTcBurstProfileFrmt1               BurstBank5Pre;           
  TcTcBurstProfileFrmt2               BurstBank5ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank5InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank5MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank5OhslenBbscale; 
                                                                 
  uint32                              Reserved1b81bb;          
  uint32                              Reserved1bc1bf;          
  TcTcBurstProfileFrmt0               BurstBank6Qam;           
  TcTcBurstProfileFrmt1               BurstBank6Pre;           
  TcTcBurstProfileFrmt2               BurstBank6ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank6InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank6MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank6OhslenBbscale; 
                                                                 
  uint32                              Reserved1d81db;          
  uint32                              Reserved1dc1df;          
  TcTcBurstProfileFrmt0               BurstBank7Qam;           
  TcTcBurstProfileFrmt1               BurstBank7Pre;           
  TcTcBurstProfileFrmt2               BurstBank7ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank7InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank7MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank7OhslenBbscale; 
                                                                 
  uint32                              Reserved1f81fb;          
  uint32                              Reserved1fc1ff;          
  TcTcBurstProfileFrmt0               BurstBank8Qam;           
  TcTcBurstProfileFrmt1               BurstBank8Pre;           
  TcTcBurstProfileFrmt2               BurstBank8ScrSeed;       
  TcTcBurstProfileFrmt3               BurstBank8InterleaverDepth;
  TcTcBurstProfileFrmt4               BurstBank8MiscSettings;  
  TcTcBurstProfileFrmt5               BurstBank8OhslenBbscale; 
                                                                 
  uint32                              Reserved21821b;          
  uint32                              Reserved21c21f;          
  uint8                               Pad1[0x20];
  uint32                              PreambleRam;             
  uint8                               Pad2[0xbc];
  TcTcAuxControl0                     AuxControl0;             
  TcTcAuxControl1                     AuxControl1;             
  TcTcAuxControl2                     AuxControl2;             
  TcTcAuxControl3                     AuxControl3;             
  TcTcAuxUsPhyIfCntrl                 AuxUsPhyIfCntrl;         
  TcTcAuxSnapshotLimits               AuxSnapshotLimits;       
  TcTcAuxTimCntrl                     AuxTimCntrl;             
                                                                 
  uint8                               AuxFineTimingAdj;        
  uint16                              PulseLostPeriod;         
  uint16                              MacMsSize;               
  TcTcTrcClkDiff                      TrcClkDiff;              
  TcTcAuxStatus                       AuxStatus;               
  TcTcAuxIrqStatus                    AuxIrqStatus;            
  uint16                              AuxIrqMask;              
  uint32                              SnapshotTimestampRegf;   
  uint32                              SnapshotMinislotRegf;    
  uint8                               SnapshotFrameRegf;       
  uint8                               TrcClkCompThreshold;     
  TcTcTmLfsrCntrl                     TmLfsrCntrl;             
  uint8                               Reserved323;             
  uint32                              DiagMask;                
  uint8                               Pad3[0x4];
  uint32                              UcdTimestamp;            
  uint32                              UcdMinislot;             
  uint8                               UcdFrameNum;             
  TcTcDiagTrigger                     DiagTrigger;             
  uint8                               Pad4[0x2];
  uint32                              DriftAdjAcc;             
  uint32                              SysMsCount;              
  uint32                              SysTstmpCount;           
  uint32                              InstMapLeadTime;         
  uint32                              MinMapLeadTime;          
  uint32                              AvgMapLeadTime;          
  TcTcBrstLenInSymbols                BrstLenInSymbols;        
  uint8                               Pad5[0x1];
  TcTcBrstLenCount                    BrstLenCount;            
  uint8                               BrstLenInMs;             
  uint8                               BrstLenInFrames;         
  TcTcMltAboveBelowCounts             MltAboveBelowCounts;     
  uint8                               Pad6[0x4];
  uint32                              MacLaAdvanceTime;        
  uint32                              MltThreshold;            
  TcTcMltControl                      MltControl;              
                                                                 
  TcTcMltAboveBelowThresh             MltAboveBelowThresh;     
                                                                 
}  TcTcRegs;

#endif 



