// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         timer.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef TIMER_H__
#define TIMER_H__



typedef union {
  struct {
    uint32 Reserved                       :25;
    uint32 MipsRegfileTm                  :2; 
    uint32 BootromTm                      :5; 
  } Bits;
  uint32 Reg32;
}  TimerMemTm;


typedef union {
  struct {
    uint32 Reserved                       :1; 
    uint32 Interrupt                      :1; 
    uint32 TimerCount                     :30;
  } Bits;
  uint32 Reg32;
}  TimerTimerCnt0;


typedef union {
  struct {
    uint32 TimrEn                         :1; 
    uint32 CntMode                        :1; 
                                              
                                              
    uint32 TimerCount                     :30;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TimerTimerCtlWd;


typedef union {
  struct {
    uint32 Reserved                       :21;
    uint32 Tim2Msk                        :1; 
    uint32 Tim1Msk                        :1; 
    uint32 Tim0Msk                        :1; 
    uint32 Reserved2                      :4; 
    uint32 WdInt                          :1; 
                                              
    uint32 Tim2Int                        :1; 
                                              
    uint32 Tim1Int                        :1; 
                                              
    uint32 Tim0Int                        :1; 
                                              
  } Bits;
  uint32 Reg32;
}  TimerTimrIrqStat;


typedef union {
  struct {
    uint32 Reserved                       :6; 
    uint32 WdRstLen                       :26;
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TimerWdResetCount;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Control                        :16;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  TimerWatchDogCtl;

typedef struct {
  TimerTimrIrqStat                    Timrirqstat;             
  TimerTimerCtlWd                     Timerctl0;               
  TimerTimerCtlWd                     Timerctl1;               
  TimerTimerCtlWd                     Timerctl2;               
  TimerTimerCnt0                      Timercnt0;               
  TimerTimerCnt0                      Timercnt1;               
  TimerTimerCnt0                      Timercnt2;               
  uint32                              WatchDogDefCount;        
  TimerWatchDogCtl                    WatchDogCtl;             
  TimerWdResetCount                   WdResetCount;            
  TimerMemTm                          MemTm;                   
  uint32                              EphyTestcntrl;           
  uint32                              SerdesCntrl;             
  uint32                              SerdesStatus;            
}  TimerRegs;

#endif 



