// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         us_core_regs.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef US_CORE_REGS_H__
#define US_CORE_REGS_H__



typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 BasebandDataCrc                :16;
  } Bits;
  uint32 Reg32;
}  UsCoreBasebandDataCrc;


typedef union {
  struct {
    uint32 Reserved0                      :24;
    uint32 CgOfst                         :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 ModRfLock                      :1; 
                                              
                                              
    uint32 ModMixSelIQb                   :1; 
                                              
                                              
                                              
                                              
    uint32 ModMix                         :1; 
                                              
                                              
    uint32 ModFilt2                       :1; 
                                              
                                              
    uint32 ModVid                         :1; 
                                              
                                              
    uint32 ModFilt1                       :1; 
                                              
                                              
    uint32 Preq                           :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsCoreByp;


typedef union {
  struct {
    uint32 Reserved                       :29;
    uint32 CgBaudRate                     :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsCoreCgBaudRate;


typedef union {
  struct {
    uint32 CgDivCrc                       :16;
    uint32 CgMuCrc                        :16;
  } Bits;
  uint32 Reg32;
}  UsCoreCgDivMuCrc;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 CgFracTimeAdj                  :8; 
  } Bits;
  uint32 Reg32;
}  UsCoreCgFracTimeAdj;


typedef union {
  struct {
    uint32 Reserved                       :26;
    uint32 CgLsFcw3732                    :6; 
  } Bits;
  uint32 Reg32;
}  UsCoreCgLsFcw1;


typedef union {
  struct {
    uint32 Reserved                       :10;
    uint32 CgLsFcwSclDen                  :22;
  } Bits;
  uint32 Reg32;
}  UsCoreCgLsFcwSclDen;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 CgLsFcwSclNum                  :16;
  } Bits;
  uint32 Reg32;
}  UsCoreCgLsFcwSclNum;


typedef union {
  struct {
    uint32 Reserved3                      :28;
    uint32 Reserved0                      :1; 
    uint32 TxMode                         :1; 
                                              
                                              
    uint32 FcwSrc                         :2; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsCoreCgMisc;


typedef union {
  struct {
    uint32 Reserved                       :19;
    uint32 ModBsbndData                   :1; 
    uint32 ModRf1Ofst                     :1; 
    uint32 ModAdjRf1Fcw                   :1; 
    uint32 ModDdfsCos                     :1; 
    uint32 ModDdfsSin                     :1; 
    uint32 ModScl                         :1; 
    uint32 ModMix                         :1; 
    uint32 ModVidI                        :1; 
    uint32 ModVidQ                        :1; 
    uint32 ModFilt1I                      :1; 
    uint32 ModFilt1Q                      :1; 
    uint32 ModFilt1Hb4x                   :1; 
    uint32 Preq                           :1; 
  } Bits;
  uint32 Reg32;
}  UsCoreClip;


typedef union {
  struct {
    uint32 Reserved                       :29;
    uint32 IntCgBaudRate                  :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsCoreIntCgBaudRate;


typedef union {
  struct {
    uint32 Reserved                       :26;
    uint32 CgFcw3732                      :6; 
  } Bits;
  uint32 Reg32;
}  UsCoreIntCgFcw1;


typedef union {
  struct {
    uint32 Reserved                       :10;
    uint32 IntCgFcwSclDen                 :22;
  } Bits;
  uint32 Reg32;
}  UsCoreIntCgFcwSclDen;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 IntCgFcwSclNum                 :16;
  } Bits;
  uint32 Reg32;
}  UsCoreIntCgFcwSclNum;


typedef union {
  struct {
    uint32 Reserved3                      :28;
    uint32 Reserved0                      :1; 
    uint32 TxMode                         :1; 
                                              
                                              
    uint32 FcwSrc                         :2; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsCoreIntCgMisc;


typedef union {
  struct {
    uint32 Reserved                       :20;
    uint32 IntModGain                     :12;
  } Bits;
  uint32 Reg32;
}  UsCoreIntModGain;


typedef union {
  struct {
    uint32 Reserved                       :1; 
    uint32 IntModRfOfstVal                :31;
  } Bits;
  uint32 Reg32;
}  UsCoreIntModRfOfstVal;


typedef union {
  struct {
    uint32 IntPreqCoeffI                  :12;
    uint32 Reserved1                      :4; 
    uint32 IntPreqCoeffQ                  :12;
    uint32 Reserved0                      :4; 
  } Bits;
  uint32 Reg32;
}  UsCoreIntPreqCoeff0;


typedef union {
  struct {
    uint32 IntPreqCoeffI                  :12;
    uint32 Reserved1                      :4; 
    uint32 IntPreqCoeffQ                  :12;
    uint32 Reserved0                      :4; 
  } Bits;
  uint32 Reg32;
}  UsCoreIntPreqCoeff1;


typedef union {
  struct {
    uint32 Reserved2                      :11;
    uint32 IntUseImpLen                   :5; 
                                              
    uint32 Reserved1                      :3; 
    uint32 IntImpExtLen                   :5; 
    uint32 Reserved0                      :3; 
    uint32 IntImpLoc                      :5; 
  } Bits;
  uint32 Reg32;
}  UsCoreIntPreqImp;


typedef union {
  struct {
    uint32 Reserved2                      :24;
    uint32 Reserved1                      :1; 
    uint32 Reserved0                      :1; 
    uint32 Clip                           :1; 
                                              
    uint32 Test                           :1; 
    uint32 Misc                           :1; 
    uint32 Pwr                            :1; 
    uint32 Tx                             :1; 
    uint32 Cg                             :1; 
  } Bits;
  uint32 Reg32;
}  UsCoreIntRst;


typedef union {
  struct {
    uint32 ModCosCrc                      :16;
    uint32 ModSinCrc                      :16;
  } Bits;
  uint32 Reg32;
}  UsCoreModCosSinCrc;


typedef union {
  struct {
    uint32 ModFilt1ICrc                   :16;
    uint32 ModFilt1QCrc                   :16;
  } Bits;
  uint32 Reg32;
}  UsCoreModFilt1IQCrc;


typedef union {
  struct {
    uint32 ModFilt2ICrc                   :16;
    uint32 ModFilt2QCrc                   :16;
  } Bits;
  uint32 Reg32;
}  UsCoreModFilt2IQCrc;


typedef union {
  struct {
    uint32 Reserved                       :20;
    uint32 ModGain                        :12;
  } Bits;
  uint32 Reg32;
}  UsCoreModGain;


typedef union {
  struct {
    uint32 Reserved0                      :28;
    uint32 UseFcw2                        :1; 
                                              
                                              
    uint32 SpInv                          :1; 
                                              
                                              
    uint32 Alpha                          :2; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsCoreModMisc;


typedef union {
  struct {
    uint32 ModMixCrc                      :16;
    uint32 ModSclCrc                      :16;
  } Bits;
  uint32 Reg32;
}  UsCoreModMixSclCrc;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 ModSclClipCnt                  :16;
                                              
  } Bits;
  uint32 Reg32;
}  UsCoreModSclClipCnt;


typedef union {
  struct {
    uint32 ModVidICrc                     :16;
    uint32 ModVidQCrc                     :16;
  } Bits;
  uint32 Reg32;
}  UsCoreModVidIQCrc;


typedef union {
  struct {
    uint32 PreqCoeffI                     :12;
    uint32 Reserved1                      :4; 
    uint32 PreqCoeffQ                     :12;
    uint32 Reserved0                      :4; 
  } Bits;
  uint32 Reg32;
}  UsCorePreqCoeff0;


typedef union {
  struct {
    uint32 PreqCoeffI                     :12;
    uint32 Reserved1                      :4; 
    uint32 PreqCoeffQ                     :12;
    uint32 Reserved0                      :4; 
  } Bits;
  uint32 Reg32;
}  UsCorePreqCoeff1;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 PreqCrc                        :16;
  } Bits;
  uint32 Reg32;
}  UsCorePreqCrc;


typedef union {
  struct {
    uint32 Reserved3                      :8; 
    uint32 Reserved2                      :3; 
    uint32 UseImpLen                      :5; 
                                              
    uint32 Reserved1                      :3; 
    uint32 ImpExtLen                      :5; 
    uint32 Reserved0                      :3; 
    uint32 ImpLoc                         :5; 
  } Bits;
  uint32 Reg32;
}  UsCorePreqImp;


typedef union {
  struct {
    uint32 Reserved1                      :28;
    uint32 Reserved0                      :3; 
    uint32 PreqGain                       :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsCorePreqMisc;


typedef union {
  struct {
    uint32 Reserved2                      :24;
    uint32 Reserved1                      :1; 
    uint32 Reserved0                      :1; 
    uint32 Clip                           :1; 
    uint32 Test                           :1; 
    uint32 Misc                           :1; 
    uint32 Pwr                            :1; 
    uint32 Tx                             :1; 
    uint32 Cg                             :1; 
  } Bits;
  uint32 Reg32;
}  UsCoreRst;


typedef union {
  struct {
    uint32 Misc                           :16;
    uint32 Length                         :16;
  } Bits;
  uint32 Reg32;
}  UsCoreTestMisc;

typedef struct {
  UsCoreRst                           Rst;                     
  UsCoreTestMisc                      TestMisc;                
  UsCoreByp                           Byp;                     
  UsCoreCgMisc                        CgMisc;                  
  UsCoreCgLsFcw1                      CgLsFcw1;                
                                                                 
  uint32                              CgLsFcw0;                
                                                                 
  UsCoreCgLsFcwSclNum                 CgLsFcwSclNum;           
                                                                 
  UsCoreCgLsFcwSclDen                 CgLsFcwSclDen;           
                                                                 
  UsCoreCgBaudRate                    CgBaudRate;              
  UsCoreCgFracTimeAdj                 CgFracTimeAdj;           
  UsCorePreqMisc                      PreqMisc;                
  UsCorePreqImp                       PreqImp;                 
  uint32                              PreqSftDin;              
  UsCorePreqCoeff0                    PreqCoeff00;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff01;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff02;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff03;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff04;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff05;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff06;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff07;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff08;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff09;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff10;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff11;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff12;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff13;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff14;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff15;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff16;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff17;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff18;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff19;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff20;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff21;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff22;             
                                                                 
  UsCorePreqCoeff1                    PreqCoeff23;             
                                                                 
  UsCoreModMisc                       ModMisc;                 
  uint32                              ModNomRf1Fcw;            
  uint32                              ModNomRf2Fcw;            
  uint32                              ModRfOfstGain;           
  UsCoreModGain                       ModGain;                 
  uint8                               Pad0[0x18];
  UsCoreIntCgMisc                     IntCgMisc;               
  UsCoreIntCgFcw1                     IntCgFcw1;               
                                                                 
  uint32                              IntCgFcw0;               
                                                                 
  UsCoreIntCgFcwSclNum                IntCgFcwSclNum;          
                                                                 
  UsCoreIntCgFcwSclDen                IntCgFcwSclDen;          
                                                                 
  UsCoreIntCgBaudRate                 IntCgBaudRate;           
  uint8                               Pad1[0x4];
  UsCoreIntPreqImp                    IntPreqImp;              
  UsCoreIntPreqCoeff0                 IntPreqCoeff00;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff01;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff02;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff03;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff04;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff05;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff06;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff07;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff08;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff09;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff10;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff11;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff12;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff13;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff14;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff15;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff16;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff17;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff18;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff19;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff20;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff21;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff22;          
                                                                 
  UsCoreIntPreqCoeff1                 IntPreqCoeff23;          
                                                                 
  uint32                              IntModNomRf1Fcw;         
                                                                 
  uint32                              IntModNomRf2Fcw;         
                                                                 
  uint32                              IntModRfOfstGain;        
  UsCoreIntModRfOfstVal               IntModRfOfstVal;         
  uint32                              IntModAdjRf1Fcw;         
                                                                 
  UsCoreIntModGain                    IntModGain;              
  UsCoreClip                          Clip;                    
  UsCoreModSclClipCnt                 ModSclClipCnt;           
  UsCoreIntRst                        IntRst;                  
  uint8                               Pad2[0x10];
  uint32                              CgCtrlCrc;               
  uint32                              CgFcwCrc1;               
  uint32                              CgFcwCrc0;               
  uint32                              CgOfstCrc1;              
  uint32                              CgOfstCrc0;              
  uint32                              CgNcoCrc1;               
  uint32                              CgNcoCrc0;               
  UsCoreCgDivMuCrc                    CgDivMuCrc;              
  uint32                              CgBaudCrc1;              
  uint32                              CgBaudCrc0;              
  uint32                              ModRf1LockCrc;           
  uint32                              ModRf2LockCrc;           
  UsCorePreqCrc                       PreqCrc;                 
  UsCoreBasebandDataCrc               BasebandDataCrc;         
  UsCoreModFilt1IQCrc                 ModFilt1IQCrc;           
  UsCoreModVidIQCrc                   ModVidIQCrc;             
  UsCoreModFilt2IQCrc                 ModFilt2IQCrc;           
  UsCoreModCosSinCrc                  ModCosSinCrc;            
  UsCoreModMixSclCrc                  ModMixSclCrc;            
}  UsCoreRegs;

#endif 



