// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         us_top_regs.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef US_TOP_REGS_H__
#define US_TOP_REGS_H__



typedef union {
  struct {
    uint32 LogDac                         :6; 
    uint32 CscStrength                    :3; 
                                              
                                              
                                              
                                              
                                              
    uint32 Atten                          :1; 
                                              
                                              
    uint32 CoaseGain                      :5; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 FineGain                       :4; 
                                              
    uint32 GainMode                       :1; 
                                              
                                              
                                              
    uint32 GainDec                        :2; 
                                              
                                              
                                              
                                              
    uint32 CscAdj                         :1; 
                                              
                                              
    uint32 AttBias                        :3; 
                                              
                                              
    uint32 TcObb                          :1; 
                                              
                                              
    uint32 CscBias                        :4; 
                                              
    uint32 ClkInv                         :1; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopAnalogCtrl0;


typedef union {
  struct {
    uint32 Reserved1                      :16;
    uint32 Reserved0                      :16;
  } Bits;
  uint32 Reg32;
}  UsTopAnalogCtrl1;


typedef union {
  struct {
    uint32 Reserved0                      :26;
    uint32 GlbEn                          :1; 
                                              
                                              
                                              
    uint32 En                             :1; 
                                              
                                              
    uint32 Sel                            :4; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopBaseband;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Misc                           :1; 
    uint32 Reg                            :2; 
                                              
                                              
                                              
                                              
    uint32 A                              :3; 
    uint32 B                              :3; 
    uint32 C                              :3; 
    uint32 RefLog                         :3; 
    uint32 Ref50u                         :1; 
  } Bits;
  uint32 Reg32;
}  UsTopBiasCtrl;


typedef union {
  struct {
    uint32 Reserved                       :26;
    uint32 CgDsFcw3732                    :6; 
  } Bits;
  uint32 Reg32;
}  UsTopCgDsFcw1;


typedef union {
  struct {
    uint32 Reserved                       :20;
    uint32 CgDsFcwDwell                   :12;
  } Bits;
  uint32 Reg32;
}  UsTopCgDsFcwDwell;


typedef union {
  struct {
    uint32 Reserved                       :10;
    uint32 CgDsFcwSclDen                  :22;
  } Bits;
  uint32 Reg32;
}  UsTopCgDsFcwSclDen;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 CgDsFcwSclNum                  :16;
  } Bits;
  uint32 Reg32;
}  UsTopCgDsFcwSclNum;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 CgDsFcwSclDen                  :5; 
  } Bits;
  uint32 Reg32;
}  UsTopCgDsNcoRatio;


typedef union {
  struct {
    uint32 Reserved                       :26;
    uint32 CgMsFcw3732                    :6; 
  } Bits;
  uint32 Reg32;
}  UsTopCgMsFcw1;


typedef union {
  struct {
    uint32 Reserved                       :10;
    uint32 CgMsFcwSclDen                  :22;
  } Bits;
  uint32 Reg32;
}  UsTopCgMsFcwSclDen;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 CgMsFcwSclNum                  :16;
  } Bits;
  uint32 Reg32;
}  UsTopCgMsFcwSclNum;


typedef union {
  struct {
    uint32 Reserved                       :10;
    uint32 CgObFcwSclDen                  :22;
  } Bits;
  uint32 Reg32;
}  UsTopCgObFcwSclDen;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 CgObFcwSclNum                  :16;
  } Bits;
  uint32 Reg32;
}  UsTopCgObFcwSclNum;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 ClipCntInit                    :16;
  } Bits;
  uint32 Reg32;
}  UsTopClipCntInit;


typedef union {
  struct {
    uint32 Reserved0                      :28;
    uint32 Core3                          :1; 
                                              
                                              
    uint32 Core2                          :1; 
                                              
                                              
    uint32 Core1                          :1; 
                                              
                                              
    uint32 Core0                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopCoreEn;


typedef union {
  struct {
    uint32 Reserved0                      :26;
    uint32 GlbEn                          :1; 
                                              
                                              
                                              
    uint32 En                             :1; 
                                              
                                              
    uint32 Sel                            :4; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopDavicMac;


typedef union {
  struct {
    uint32 Reserved                       :19;
    uint32 En                             :1; 
                                              
                                              
    uint32 MajorBlkSel                    :4; 
    uint32 MinorBlockSel                  :4; 
    uint32 SubBlockSel                    :4; 
  } Bits;
  uint32 Reg32;
}  UsTopDiag;


typedef union {
  struct {
    uint32 Reserved                       :26;
    uint32 CgDsFcw3732                    :6; 
  } Bits;
  uint32 Reg32;
}  UsTopIntCgDsFcw1;


typedef union {
  struct {
    uint32 Reserved                       :20;
    uint32 CgDsFcwDwell                   :12;
  } Bits;
  uint32 Reg32;
}  UsTopIntCgDsFcwDwellCnt;


typedef union {
  struct {
    uint32 Reserved                       :27;
    uint32 CgDsFcwSclDen                  :5; 
  } Bits;
  uint32 Reg32;
}  UsTopIntCgDsNcoRatioCnt;


typedef union {
  struct {
    uint32 Reserved2                      :24;
    uint32 Reserved1                      :1; 
    uint32 Reserved0                      :1; 
    uint32 Clip                           :1; 
                                              
    uint32 Test                           :1; 
    uint32 Misc                           :1; 
    uint32 Pwr                            :1; 
    uint32 Tx                             :1; 
    uint32 Cg                             :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIntRst;


typedef union {
  struct {
    uint32 Reserved0                      :24;
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 Irq03                          :1; 
    uint32 BrstDone                       :1; 
    uint32 BistDone                       :1; 
    uint32 CgDsFcwOutOfLock               :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsTopIrq1;


typedef union {
  struct {
    uint32 Reserved0                      :24;
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 Irq03                          :1; 
    uint32 BrstDone                       :1; 
    uint32 BistDone                       :1; 
    uint32 CgDsFcwOutOfLock               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq1Clr;


typedef union {
  struct {
    uint32 Reserved0                      :24;
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 Irq03                          :1; 
    uint32 BrstDone                       :1; 
    uint32 BistDone                       :1; 
    uint32 CgDsFcwOutOfLock               :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsTopIrq1Mask;


typedef union {
  struct {
    uint32 Reserved0                      :24;
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 Irq03                          :1; 
    uint32 BrstDone                       :1; 
    uint32 BistDone                       :1; 
    uint32 CgDsFcwOutOfLock               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq1MaskClr;


typedef union {
  struct {
    uint32 Reserved0                      :24;
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 Irq03                          :1; 
    uint32 BrstDone                       :1; 
    uint32 BistDone                       :1; 
    uint32 CgDsFcwOutOfLock               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq1MaskSet;


typedef union {
  struct {
    uint32 Reserved0                      :24;
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 Irq03                          :1; 
    uint32 BrstDone                       :1; 
    uint32 BistDone                       :1; 
    uint32 CgDsFcwOutOfLock               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq1Set;


typedef union {
  struct {
    uint32 Irq31                          :1; 
    uint32 Irq30                          :1; 
    uint32 Irq29                          :1; 
    uint32 Irq28                          :1; 
    uint32 RampPwrPdac3Error              :1; 
                                              
                                              
    uint32 RampPwrPdac2Error              :1; 
                                              
                                              
    uint32 RampPwrPdac1Error              :1; 
                                              
                                              
    uint32 RampPwrPdac0Error              :1; 
                                              
                                              
    uint32 Irq23                          :1; 
    uint32 Irq22                          :1; 
    uint32 Irq21                          :1; 
    uint32 Irq20                          :1; 
    uint32 RangeAdj3Ack                   :1; 
                                              
    uint32 RangeAdj2Ack                   :1; 
                                              
    uint32 RangeAdj1Ack                   :1; 
                                              
    uint32 RangeAdj0Ack                   :1; 
                                              
    uint32 Irq15                          :1; 
    uint32 Irq14                          :1; 
    uint32 Irq13                          :1; 
    uint32 Irq12                          :1; 
    uint32 TxNow3AckError                 :1; 
                                              
    uint32 TxNow2AckError                 :1; 
                                              
    uint32 TxNow1AckError                 :1; 
                                              
    uint32 TxNow0AckError                 :1; 
                                              
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 TxDinValid3Error               :1; 
                                              
    uint32 TxDinValid2Error               :1; 
                                              
    uint32 TxDinValid1Error               :1; 
                                              
    uint32 TxDinValid0Error               :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsTopIrq2;


typedef union {
  struct {
    uint32 Irq31                          :1; 
    uint32 Irq30                          :1; 
    uint32 Irq29                          :1; 
    uint32 Irq28                          :1; 
    uint32 RampPwrPdac3Error              :1; 
    uint32 RampPwrPdac2Error              :1; 
    uint32 RampPwrPdac1Error              :1; 
    uint32 RampPwrPdac0Error              :1; 
    uint32 Irq23                          :1; 
    uint32 Irq22                          :1; 
    uint32 Irq21                          :1; 
    uint32 Irq20                          :1; 
    uint32 RangeAdj3Ack                   :1; 
    uint32 RangeAdj2Ack                   :1; 
    uint32 RangeAdj1Ack                   :1; 
    uint32 RangeAdj0Ack                   :1; 
    uint32 Irq15                          :1; 
    uint32 Irq14                          :1; 
    uint32 Irq13                          :1; 
    uint32 Irq12                          :1; 
    uint32 TxNow3AckError                 :1; 
    uint32 TxNow2AckError                 :1; 
    uint32 TxNow1AckError                 :1; 
    uint32 TxNow0AckError                 :1; 
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 TxDinValid3Error               :1; 
    uint32 TxDinValid2Error               :1; 
    uint32 TxDinValid1Error               :1; 
    uint32 TxDinValid0Error               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq2Clr;


typedef union {
  struct {
    uint32 Irq31                          :1; 
    uint32 Irq30                          :1; 
    uint32 Irq29                          :1; 
    uint32 Irq28                          :1; 
    uint32 RampPwrPdac3Error              :1; 
    uint32 RampPwrPdac2Error              :1; 
    uint32 RampPwrPdac1Error              :1; 
    uint32 RampPwrPdac0Error              :1; 
    uint32 Irq23                          :1; 
    uint32 Irq22                          :1; 
    uint32 Irq21                          :1; 
    uint32 Irq20                          :1; 
    uint32 RangeAdj3Ack                   :1; 
    uint32 RangeAdj2Ack                   :1; 
    uint32 RangeAdj1Ack                   :1; 
    uint32 RangeAdj0Ack                   :1; 
    uint32 Irq15                          :1; 
    uint32 Irq14                          :1; 
    uint32 Irq13                          :1; 
    uint32 Irq12                          :1; 
    uint32 TxNow3AckError                 :1; 
    uint32 TxNow2AckError                 :1; 
    uint32 TxNow1AckError                 :1; 
    uint32 TxNow0AckError                 :1; 
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 TxDinValid3Error               :1; 
    uint32 TxDinValid2Error               :1; 
    uint32 TxDinValid1Error               :1; 
    uint32 TxDinValid0Error               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq2Mask;


typedef union {
  struct {
    uint32 Irq31                          :1; 
    uint32 Irq30                          :1; 
    uint32 Irq29                          :1; 
    uint32 Irq28                          :1; 
    uint32 RampPwrPdac3Error              :1; 
    uint32 RampPwrPdac2Error              :1; 
    uint32 RampPwrPdac1Error              :1; 
    uint32 RampPwrPdac0Error              :1; 
    uint32 Irq23                          :1; 
    uint32 Irq22                          :1; 
    uint32 Irq21                          :1; 
    uint32 Irq20                          :1; 
    uint32 RangeAdj3Ack                   :1; 
    uint32 RangeAdj2Ack                   :1; 
    uint32 RangeAdj1Ack                   :1; 
    uint32 RangeAdj0Ack                   :1; 
    uint32 Irq15                          :1; 
    uint32 Irq14                          :1; 
    uint32 Irq13                          :1; 
    uint32 Irq12                          :1; 
    uint32 TxNow3AckError                 :1; 
    uint32 TxNow2AckError                 :1; 
    uint32 TxNow1AckError                 :1; 
    uint32 TxNow0AckError                 :1; 
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 TxDinValid3Error               :1; 
    uint32 TxDinValid2Error               :1; 
    uint32 TxDinValid1Error               :1; 
    uint32 TxDinValid0Error               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq2MaskClr;


typedef union {
  struct {
    uint32 Irq31                          :1; 
    uint32 Irq30                          :1; 
    uint32 Irq29                          :1; 
    uint32 Irq28                          :1; 
    uint32 RampPwrPdac3Error              :1; 
    uint32 RampPwrPdac2Error              :1; 
    uint32 RampPwrPdac1Error              :1; 
    uint32 RampPwrPdac0Error              :1; 
    uint32 Irq23                          :1; 
    uint32 Irq22                          :1; 
    uint32 Irq21                          :1; 
    uint32 Irq20                          :1; 
    uint32 RangeAdj3Ack                   :1; 
    uint32 RangeAdj2Ack                   :1; 
    uint32 RangeAdj1Ack                   :1; 
    uint32 RangeAdj0Ack                   :1; 
    uint32 Irq15                          :1; 
    uint32 Irq14                          :1; 
    uint32 Irq13                          :1; 
    uint32 Irq12                          :1; 
    uint32 TxNow3AckError                 :1; 
    uint32 TxNow2AckError                 :1; 
    uint32 TxNow1AckError                 :1; 
    uint32 TxNow0AckError                 :1; 
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 TxDinValid3Error               :1; 
    uint32 TxDinValid2Error               :1; 
    uint32 TxDinValid1Error               :1; 
    uint32 TxDinValid0Error               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq2MaskSet;


typedef union {
  struct {
    uint32 Irq31                          :1; 
    uint32 Irq30                          :1; 
    uint32 Irq29                          :1; 
    uint32 Irq28                          :1; 
    uint32 RampPwrPdac3Error              :1; 
    uint32 RampPwrPdac2Error              :1; 
    uint32 RampPwrPdac1Error              :1; 
    uint32 RampPwrPdac0Error              :1; 
    uint32 Irq23                          :1; 
    uint32 Irq22                          :1; 
    uint32 Irq21                          :1; 
    uint32 Irq20                          :1; 
    uint32 RangeAdj3Ack                   :1; 
    uint32 RangeAdj2Ack                   :1; 
    uint32 RangeAdj1Ack                   :1; 
    uint32 RangeAdj0Ack                   :1; 
    uint32 Irq15                          :1; 
    uint32 Irq14                          :1; 
    uint32 Irq13                          :1; 
    uint32 Irq12                          :1; 
    uint32 TxNow3AckError                 :1; 
    uint32 TxNow2AckError                 :1; 
    uint32 TxNow1AckError                 :1; 
    uint32 TxNow0AckError                 :1; 
    uint32 Irq07                          :1; 
    uint32 Irq06                          :1; 
    uint32 Irq05                          :1; 
    uint32 Irq04                          :1; 
    uint32 TxDinValid3Error               :1; 
    uint32 TxDinValid2Error               :1; 
    uint32 TxDinValid1Error               :1; 
    uint32 TxDinValid0Error               :1; 
  } Bits;
  uint32 Reg32;
}  UsTopIrq2Set;


typedef union {
  struct {
    uint32 Reserved1                      :24;
    uint32 Reserved0                      :1; 
    uint32 UseSftObIfc                    :1; 
                                              
                                              
                                              
    uint32 UseSftDsIfc                    :1; 
                                              
                                              
                                              
    uint32 SelPwrTestClk                  :1; 
                                              
                                              
                                              
                                              
    uint32 EnLoadClipCntInit              :1; 
                                              
                                              
                                              
                                              
    uint32 DisableSelfClearRsts           :1; 
                                              
                                              
                                              
                                              
    uint32 EnSftRangeAdj                  :1; 
                                              
                                              
                                              
                                              
    uint32 TestDsObIfc                    :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopMisc;


typedef union {
  struct {
    uint32 Reserved                       :1; 
    uint32 ModMsRfOfstVal                 :31;
  } Bits;
  uint32 Reg32;
}  UsTopModMsRfOfstVal;


typedef union {
  struct {
    uint32 Reserved1                      :24;
    uint32 Reserved0                      :1; 
    uint32 UseCoreOe                      :1; 
                                              
                                              
    uint32 UseSftPaOe                     :1; 
                                              
                                              
    uint32 SftPaOe                        :1; 
                                              
                                              
    uint32 PaSpiSsPol                     :1; 
                                              
                                              
    uint32 PaSpiSckPol                    :1; 
                                              
                                              
    uint32 PaCtrlIsSpi                    :1; 
                                              
                                              
    uint32 PaOePol                        :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPaMisc;


typedef union {
  struct {
    uint32 Reserved1                      :24;
    uint32 Pwr                            :8; 
  } Bits;
  uint32 Reg32;
}  UsTopPaPwr;


typedef union {
  struct {
    uint32 Reserved0                      :28;
    uint32 Pdac3                          :1; 
                                              
                                              
    uint32 Pdac2                          :1; 
                                              
                                              
    uint32 Pdac1                          :1; 
                                              
                                              
    uint32 Pdac0                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPdacEn;


typedef union {
  struct {
    uint32 Reserved1                      :28;
    uint32 Pdac3                          :1; 
                                              
                                              
                                              
    uint32 Pdac2                          :1; 
                                              
                                              
                                              
    uint32 Pdac1                          :1; 
                                              
                                              
                                              
    uint32 Pdac0                          :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPdacInpMuxEn;


typedef union {
  struct {
    uint32 Reserved2                      :16;
    uint32 Reserved1                      :1; 
    uint32 ForceUsePllClkDsAfe3           :1; 
                                              
                                              
    uint32 ForceUsePllClkDsAfe2           :1; 
                                              
                                              
    uint32 ForceUsePllClkDsAfe1           :1; 
                                              
                                              
    uint32 ForceUsePllClkDsAfe0           :1; 
                                              
                                              
    uint32 ForceUsePllClkDs               :1; 
                                              
                                              
    uint32 ForceUsePllClkOb               :1; 
                                              
                                              
    uint32 ForceUsePllClkUs               :1; 
                                              
                                              
    uint32 Reserved0                      :1; 
    uint32 ForceBypPllClkDsAfe3           :1; 
                                              
                                              
                                              
                                              
    uint32 ForceBypPllClkDsAfe2           :1; 
                                              
                                              
                                              
                                              
    uint32 ForceBypPllClkDsAfe1           :1; 
                                              
                                              
                                              
                                              
    uint32 ForceBypPllClkDsAfe0           :1; 
                                              
                                              
                                              
                                              
    uint32 ForceBypPllClkDs               :1; 
                                              
                                              
                                              
                                              
    uint32 ForceBypPllClkOb               :1; 
                                              
                                              
                                              
                                              
    uint32 ForceBypPllClkUs               :1; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllByp;


typedef union {
  struct {
    uint32 Reserved2                      :16;
    uint32 Div                            :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved1                      :2; 
    uint32 Dly                            :2; 
                                              
    uint32 Reserved0                      :1; 
    uint32 PwrupCmlbuf                    :1; 
                                              
                                              
    uint32 Pwrup                          :1; 
                                              
                                              
    uint32 EnClk                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllClkDs;


typedef union {
  struct {
    uint32 Reserved2                      :16;
    uint32 Div                            :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved1                      :2; 
    uint32 Dly                            :2; 
                                              
    uint32 Reserved0                      :1; 
    uint32 PwrupCmlbuf                    :1; 
                                              
                                              
    uint32 Pwrup                          :1; 
                                              
                                              
    uint32 EnClk                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllClkDsAfe0;


typedef union {
  struct {
    uint32 Reserved2                      :16;
    uint32 Div                            :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved1                      :2; 
    uint32 Dly                            :2; 
                                              
    uint32 Reserved0                      :1; 
    uint32 PwrupCmlbuf                    :1; 
                                              
                                              
    uint32 Pwrup                          :1; 
                                              
                                              
    uint32 EnClk                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllClkDsAfe1;


typedef union {
  struct {
    uint32 Reserved2                      :16;
    uint32 Div                            :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved1                      :2; 
    uint32 Dly                            :2; 
                                              
    uint32 Reserved0                      :1; 
    uint32 PwrupCmlbuf                    :1; 
                                              
                                              
    uint32 Pwrup                          :1; 
                                              
                                              
    uint32 EnClk                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllClkDsAfe2;


typedef union {
  struct {
    uint32 Reserved2                      :16;
    uint32 Div                            :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved1                      :2; 
    uint32 Dly                            :2; 
                                              
    uint32 Reserved0                      :1; 
    uint32 PwrupCmlbuf                    :1; 
                                              
                                              
    uint32 Pwrup                          :1; 
                                              
                                              
    uint32 EnClk                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllClkDsAfe3;


typedef union {
  struct {
    uint32 Reserved2                      :16;
    uint32 Div                            :8; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved1                      :2; 
    uint32 Dly                            :2; 
                                              
    uint32 Reserved0                      :1; 
    uint32 PwrupCmlbuf                    :1; 
                                              
                                              
    uint32 Pwrup                          :1; 
                                              
                                              
    uint32 EnClk                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllClkOb;


typedef union {
  struct {
    uint32 Reserved0                      :31;
    uint32 EnClk                          :1; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllClkUs;


typedef union {
  struct {
    uint32 PtapAdj                        :2; 
                                              
                                              
                                              
                                              
    uint32 CtapAdj                        :2; 
                                              
                                              
                                              
                                              
    uint32 Reserved0                      :1; 
    uint32 KvcoXs                         :3; 
                                              
                                              
                                              
                                              
    uint32 KvcoXf                         :3; 
                                              
                                              
    uint32 Icpx                           :5; 
                                              
                                              
    uint32 BgBiasEn                       :1; 
                                              
                                              
    uint32 LpfBw                          :2; 
                                              
                                              
                                              
    uint32 LpfOrder                       :1; 
                                              
                                              
                                              
                                              
    uint32 Cn                             :2; 
                                              
    uint32 Rn                             :3; 
                                              
    uint32 Cp                             :2; 
                                              
    uint32 Cz                             :2; 
                                              
    uint32 Rz                             :3; 
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllCtrl0;


typedef union {
  struct {
    uint32 Reserved1                      :24;
    uint32 Reserved0                      :8; 
  } Bits;
  uint32 Reg32;
}  UsTopPllCtrl1;


typedef union {
  struct {
    uint32 Reserved3                      :7; 
    uint32 NdivInt                        :9; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved2                      :4; 
    uint32 Reserved1                      :4; 
    uint32 Reserved0                      :4; 
    uint32 P1div                          :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllDiv1;


typedef union {
  struct {
    uint32 Reserved                       :8; 
    uint32 NdivFrac                       :24;
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllDiv2;


typedef union {
  struct {
    uint32 Reserved1                      :20;
    uint32 Reserved0                      :2; 
    uint32 TestEn                         :2; 
                                              
                                              
                                              
                                              
    uint32 TestSel                        :4; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 DisFreqDetect                  :1; 
                                              
                                              
    uint32 DisAvdd1P2Detect               :1; 
                                              
                                              
    uint32 NdivMode                       :2; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllMisc;


typedef union {
  struct {
    uint32 Reserved                       :6; 
    uint32 InvMsb                         :1; 
                                              
                                              
                                              
                                              
    uint32 UsClkPhase                     :5; 
                                              
                                              
                                              
    uint32 Dac3ClkPhase                   :5; 
                                              
                                              
    uint32 Dac2ClkPhase                   :5; 
                                              
                                              
    uint32 Dac1ClkPhase                   :5; 
                                              
                                              
    uint32 Dac0ClkPhase                   :5; 
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllPhase0;


typedef union {
  struct {
    uint32 Reserved1                      :16;
    uint32 Reserved0                      :6; 
    uint32 UsClkQuad                      :2; 
                                              
                                              
                                              
                                              
    uint32 Dac3ClkQuad                    :2; 
                                              
                                              
                                              
                                              
    uint32 Dac2ClkQuad                    :2; 
                                              
                                              
                                              
                                              
    uint32 Dac1ClkQuad                    :2; 
                                              
                                              
                                              
                                              
    uint32 Dac0ClkQuad                    :2; 
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllPhase1;


typedef union {
  struct {
    uint32 Reserved6                      :29;
    uint32 Phase                          :1; 
                                              
                                              
                                              
    uint32 Digital                        :1; 
                                              
                                              
                                              
    uint32 Analog                         :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPllRst;


typedef union {
  struct {
    uint32 Reserved0                      :26;
    uint32 GlbEn                          :1; 
                                              
                                              
                                              
    uint32 En                             :1; 
                                              
                                              
    uint32 Sel                            :4; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPod;


typedef union {
  struct {
    uint32 Reserved1                      :16;
    uint32 Reserved0                      :7; 
    uint32 Logbias3                       :1; 
                                              
                                              
    uint32 Logbias2                       :1; 
                                              
                                              
    uint32 Logbias1                       :1; 
                                              
                                              
    uint32 Logbias0                       :1; 
                                              
                                              
    uint32 Bias                           :1; 
                                              
                                              
    uint32 Bgcore                         :1; 
                                              
                                              
    uint32 Vreg                           :1; 
                                              
                                              
    uint32 PhaseItp                       :1; 
                                              
                                              
    uint32 Pll                            :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopPwrdn;


typedef union {
  struct {
    uint32 Reserved0                      :30;
    uint32 Force                          :1; 
                                              
                                              
                                              
    uint32 Disable                        :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsTopRegShadow;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 RevId                          :16;
  } Bits;
  uint32 Reg32;
}  UsTopRevId;


typedef union {
  struct {
    uint32 Reserved4                      :16;
    uint32 Reserved3                      :1; 
    uint32 Reserved2                      :1; 
    uint32 TopClip                        :1; 
    uint32 TopTest                        :1; 
    uint32 TopMisc                        :1; 
    uint32 TopPwr                         :1; 
    uint32 TopTx                          :1; 
    uint32 TopCg                          :1; 
    uint32 Reserved1                      :1; 
    uint32 Reserved0                      :1; 
    uint32 AllClip                        :1; 
                                              
    uint32 AllTest                        :1; 
    uint32 AllMisc                        :1; 
                                              
    uint32 AllPwr                         :1; 
    uint32 AllTx                          :1; 
    uint32 AllCg                          :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsTopRst;


typedef union {
  struct {
    uint32 Reserved4                      :9; 
    uint32 RunBistPa                      :1; 
                                              
    uint32 RunBistTx                      :1; 
    uint32 RunBrstTx                      :1; 
    uint32 Reserved3                      :3; 
    uint32 BistDone                       :1; 
    uint32 Reserved2                      :3; 
    uint32 PllLock                        :1; 
    uint32 Reserved1                      :2; 
    uint32 CgDsFcwLock                    :1; 
                                              
    uint32 CgDsFcwOutOfLock               :1; 
                                              
    uint32 Reserved0                      :4; 
    uint32 UsMod3Busy                     :1; 
    uint32 UsMod2Busy                     :1; 
    uint32 UsMod1Busy                     :1; 
    uint32 UsMod0Busy                     :1; 
  } Bits;
  uint32 Reg32;
}  UsTopStatus;


typedef union {
  struct {
    uint32 Misc                           :16;
    uint32 Length                         :16;
  } Bits;
  uint32 Reg32;
}  UsTopTestMisc;


typedef union {
  struct {
    uint32 Reserved                       :24;
    uint32 Mode                           :8; 
  } Bits;
  uint32 Reg32;
}  UsTopTestMode;

typedef struct {
  UsTopRevId                          RevId;                   
  UsTopRst                            Rst;                     
  UsTopStatus                         Status;                  
  UsTopIrq1                           Irq1;                    
  UsTopIrq1Set                        Irq1Set;                 
  UsTopIrq1Clr                        Irq1Clr;                 
  UsTopIrq1Mask                       Irq1Mask;                
  UsTopIrq1MaskSet                    Irq1MaskSet;             
  UsTopIrq1MaskClr                    Irq1MaskClr;             
  UsTopIrq2                           Irq2;                    
  UsTopIrq2Set                        Irq2Set;                 
  UsTopIrq2Clr                        Irq2Clr;                 
  UsTopIrq2Mask                       Irq2Mask;                
  UsTopIrq2MaskSet                    Irq2MaskSet;             
  UsTopIrq2MaskClr                    Irq2MaskClr;             
  UsTopPwrdn                          Pwrdn;                   
  UsTopRegShadow                      RegShadow;               
  UsTopCoreEn                         CoreEn;                  
  UsTopPdacEn                         PdacEn;                  
  UsTopPdacInpMuxEn                   PdacInpMuxEn;            
  UsTopDiag                           Diag;                    
  UsTopTestMode                       TestMode;                
  UsTopTestMisc                       TestMisc;                
  UsTopBaseband                       Baseband;                
  UsTopPod                            Pod;                     
  UsTopDavicMac                       DavicMac;                
  UsTopClipCntInit                    ClipCntInit;             
  UsTopMisc                           Misc;                    
  UsTopPaMisc                         PaMisc;                  
  UsTopPaPwr                          PaPwr;                   
  uint8                               Pad0[0x8];
  UsTopCgDsNcoRatio                   CgDsNcoRatio;            
  UsTopCgDsFcwDwell                   CgDsFcwDwell;            
                                                                 
  UsTopCgDsFcw1                       CgDsFcw1;                
                                                                 
  uint32                              CgDsFcw0;                
                                                                 
                                                                 
  UsTopCgDsFcwSclNum                  CgDsFcwSclNum;           
  UsTopCgDsFcwSclDen                  CgDsFcwSclDen;           
  uint32                              CgObFcw;                 
                                                                 
  UsTopCgObFcwSclNum                  CgObFcwSclNum;           
  UsTopCgObFcwSclDen                  CgObFcwSclDen;           
  UsTopCgMsFcw1                       CgMsFcw1;                
                                                                 
  uint32                              CgMsFcw0;                
                                                                 
  UsTopCgMsFcwSclNum                  CgMsFcwSclNum;           
  UsTopCgMsFcwSclDen                  CgMsFcwSclDen;           
  UsTopModMsRfOfstVal                 ModMsRfOfstVal;          
  uint8                               Pad1[0x8];
  UsTopPllDiv1                        PllDiv1;                 
  UsTopPllDiv2                        PllDiv2;                 
  UsTopPllClkUs                       PllClkUs;                
  UsTopPllClkOb                       PllClkOb;                
  UsTopPllClkDs                       PllClkDs;                
  UsTopPllClkDsAfe0                   PllClkDsAfe0;            
  UsTopPllClkDsAfe1                   PllClkDsAfe1;            
  UsTopPllClkDsAfe2                   PllClkDsAfe2;            
  UsTopPllClkDsAfe3                   PllClkDsAfe3;            
  UsTopPllByp                         PllByp;                  
  UsTopPllRst                         PllRst;                  
  UsTopPllMisc                        PllMisc;                 
  UsTopPllCtrl1                       PllCtrl1;                
  UsTopPllCtrl0                       PllCtrl0;                
  UsTopPllPhase1                      PllPhase1;               
  UsTopPllPhase0                      PllPhase0;               
  UsTopBiasCtrl                       BiasCtrl;                
  UsTopAnalogCtrl1                    AnalogCtrl1;             
  UsTopAnalogCtrl0                    AnalogCtrl0;             
  uint8                               Pad2[0x4];
  UsTopIntCgDsNcoRatioCnt             IntCgDsNcoRatioCnt;      
                                                                 
  UsTopIntCgDsFcwDwellCnt             IntCgDsFcwDwellCnt;      
  UsTopIntCgDsFcw1                    IntCgDsFcw1;             
                                                                 
  uint32                              IntCgDsFcw0;             
                                                                 
  uint32                              IntCgObFcw;              
  UsTopIntRst                         IntRst;                  
  uint8                               Pad3[0x40];
  uint32                              CgCtrlCrc;               
  uint32                              CgDsFcwCrc1;             
  uint32                              CgDsFcwCrc0;             
  uint32                              CgObFcwCrc1;             
  uint32                              CgObFcwCrc0;             
  uint32                              PaPwrCrc;                
}  UsTopRegs;

#endif 



