// ****************************************************************************
//
// Copyright (c) 2008 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         usb_otg_regs.h
//  Generated by:     RDB Utility
//  Creation Date:    8/7/2008
//  Command Line:     
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef USB_OTG_REGS_H__
#define USB_OTG_REGS_H__



typedef union {
  struct {
    uint32 ExpXfersize                    :31;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 ChEnable                       :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeChCtrl;


typedef union {
  struct {
    uint32 Reserved                       :21;
    uint32 ChIntstMask                    :11;
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeChIntstMask;


typedef union {
  struct {
    uint32 Reserved                       :10;
    uint32 WriteReadCommand               :1; 
                                              
                                              
                                              
    uint32 Phyad                          :5; 
                                              
    uint32 Reserved2                      :11;
    uint32 Regad                          :5; 
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeCtrl0;


typedef union {
  struct {
    uint32 WrStatus                       :1; 
                                              
                                              
                                              
                                              
    uint32 Reserved                       :15;
    uint32 WriteData                      :16;
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeCtrl1;


typedef union {
  struct {
    uint32 RdStatus                       :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Reserved                       :15;
    uint32 ReadData                       :16;
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeCtrl2;


typedef union {
  struct {
    uint32 Reserved                       :16;
    uint32 Idle                           :16;
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeCtrlStatus;


typedef union {
  struct {
    uint32 DbgCtrl                        :16;
    uint32 BypPwrfltFilter                :1; 
                                              
    uint32 BypActiveFilter                :1; 
                                              
    uint32 TopDbgSel                      :6; 
                                              
    uint32 DbgSel                         :6; 
                                              
    uint32 OtgScale                       :2; 
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeDebugCtrl;


typedef union {
  struct {
    uint32 Reserved                       :28;
    uint32 UsbActive                      :1; 
                                              
                                              
    uint32 UsbPwrfl                       :1; 
                                              
                                              
    uint32 UsbPwrflPolarity               :1; 
                                              
                                              
    uint32 UsbPwrOn                       :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeGpio;


typedef union {
  struct {
    uint32 Reserved                       :19;
    uint32 UsbActiveInterruptMask         :1; 
                                              
    uint32 UsbPwrfltInterruptMask         :1; 
                                              
    uint32 Ch7InterruptMask               :1; 
                                              
                                              
                                              
    uint32 Ch6InterruptMask               :1; 
                                              
                                              
                                              
    uint32 Ch5InterruptMask               :1; 
                                              
                                              
                                              
    uint32 Ch4InterruptMask               :1; 
                                              
                                              
                                              
    uint32 Ch3InterruptMask               :1; 
                                              
                                              
                                              
    uint32 Ch2InterruptMask               :1; 
                                              
                                              
                                              
    uint32 Ch1InterruptMask               :1; 
                                              
                                              
                                              
    uint32 Ch0InterruptMask               :1; 
                                              
                                              
                                              
    uint32 UsbMsgInterruptMask            :1; 
                                              
    uint32 MbdmaInterruptMask             :1; 
                                              
    uint32 OtgInterruptMask               :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeIntrMask;


typedef union {
  struct {
    uint32 Reserved                       :19;
    uint32 UsbActiveChangeInterrupt       :1; 
                                              
                                              
                                              
    uint32 UsbPwrfltChangeInterrupt       :1; 
                                              
                                              
                                              
                                              
    uint32 Ch7Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Ch6Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Ch5Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Ch4Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Ch3Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Ch2Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Ch1Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 Ch0Interrupt                   :1; 
                                              
                                              
                                              
                                              
                                              
    uint32 UsbMsgInterrupt                :1; 
                                              
                                              
    uint32 MbdmaInterrupt                 :1; 
                                              
    uint32 OtgInterrupt                   :1; 
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeIntrStatus;


typedef union {
  struct {
    uint32 Misc                           :6; 
                                              
    uint32 TxEndianCtrl                   :1; 
                                              
                                              
                                              
                                              
    uint32 RxEndianCtrl                   :1; 
                                              
                                              
                                              
                                              
    uint32 MiscReserved                   :16;
    uint32 IgnrExpField7                  :1; 
                                              
                                              
                                              
    uint32 IgnrExpField6                  :1; 
                                              
                                              
                                              
    uint32 IgnrExpField5                  :1; 
                                              
                                              
                                              
    uint32 IgnrExpField4                  :1; 
                                              
                                              
                                              
    uint32 IgnrExpField3                  :1; 
                                              
                                              
                                              
    uint32 IgnrExpField2                  :1; 
                                              
                                              
                                              
    uint32 IgnrExpField1                  :1; 
                                              
                                              
                                              
    uint32 IgnrExpField0                  :1; 
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgTypeMisc;


typedef union {
  struct {
    uint32 BrtPktSize                     :16;
    uint32 BrtPktCnt                      :16;
  } Bits;
  uint32 Reg32;
}  UsbOtgBrtCtl1;


typedef union {
  struct {
    uint32 PllctlSpare                    :22;
    uint32 PllReset                       :1; 
    uint32 Phypllbyp                      :1; 
                                              
                                              
                                              
                                              
    uint32 Clksel                         :2; 
    uint32 PllSuspendEn                   :1; 
    uint32 PllCalen                       :1; 
    uint32 PllPwrdwnb                     :1; 
                                              
                                              
                                              
    uint32 XtalPwrdwnb                    :1; 
                                              
                                              
    uint32 Refclksel                      :2; 
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgPllCtl1;


typedef union {
  struct {
    uint32 Reserved                       :17;
    uint32 TpoutSel                       :7; 
    uint32 TestMuxSel                     :8; 
  } Bits;
  uint32 Reg32;
}  UsbOtgTestPortCtl;


typedef union {
  struct {
    uint32 Reserved                       :1; 
    uint32 InvertBypassPll                :1; 
    uint32 DisableUtmiSrp                 :1; 
                                              
    uint32 ShdnSel                        :1; 
                                              
    uint32 OtgMode                        :1; 
    uint32 HostbDev                       :1; 
                                              
                                              
                                              
    uint32 PhyPwdnb                       :1; 
                                              
                                              
    uint32 UtmiPwdnb                      :1; 
                                              
                                              
    uint32 UtmiSoftResetb                 :1; 
    uint32 Reserved2                      :1; 
    uint32 DisconPhy                      :1; 
                                              
                                              
    uint32 TxPhase                        :1; 
                                              
                                              
                                              
                                              
    uint32 ChirpRx                        :1; 
                                              
    uint32 SyncDetLeng                    :3; 
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
    uint32 GenericCrt                     :16;
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
  } Bits;
  uint32 Reg32;
}  UsbOtgUtmiCtl1;

typedef struct {
  UsbOtgTypeCtrl0                     Ctrl0;                   
  UsbOtgTypeCtrl1                     Ctrl1;                   
  UsbOtgTypeCtrl2                     Ctrl2;                   
}  UsbOtgMdioReg;

typedef struct {
  UsbOtgTypeIntrStatus                IntrStatus;              
  UsbOtgTypeIntrMask                  IntrMask;                
  UsbOtgTypeMisc                      MiscReg;                 
  UsbOtgTypeCtrlStatus                CtrlStatus;              
  UsbOtgTypeChCtrl                    ChCtrl0;                 
  UsbOtgTypeChCtrl                    ChCtrl1;                 
  UsbOtgTypeChCtrl                    ChCtrl2;                 
  UsbOtgTypeChCtrl                    ChCtrl3;                 
  UsbOtgTypeChCtrl                    ChCtrl4;                 
  UsbOtgTypeChCtrl                    ChCtrl5;                 
  UsbOtgTypeChCtrl                    ChCtrl6;                 
  UsbOtgTypeChCtrl                    ChCtrl7;                 
  UsbOtgTypeChCtrl                    ChCtrl8;                 
  UsbOtgTypeChCtrl                    ChCtrl9;                 
  UsbOtgTypeChCtrl                    ChCtrl10;                
  UsbOtgTypeChCtrl                    ChCtrl11;                
  UsbOtgTypeChCtrl                    ChCtrl12;                
  UsbOtgTypeChCtrl                    ChCtrl13;                
  UsbOtgTypeChCtrl                    ChCtrl14;                
  UsbOtgTypeChCtrl                    ChCtrl15;                
  UsbOtgTypeChIntstMask               ChIntstMask0;            
  UsbOtgTypeChIntstMask               ChIntstMask1;            
  UsbOtgTypeChIntstMask               ChIntstMask2;            
  UsbOtgTypeChIntstMask               ChIntstMask3;            
  UsbOtgTypeChIntstMask               ChIntstMask4;            
  UsbOtgTypeChIntstMask               ChIntstMask5;            
  UsbOtgTypeChIntstMask               ChIntstMask6;            
  UsbOtgTypeChIntstMask               ChIntstMask7;            
  UsbOtgTypeChIntstMask               ChIntstMask8;            
  UsbOtgTypeChIntstMask               ChIntstMask9;            
  UsbOtgTypeChIntstMask               ChIntstMask10;           
  UsbOtgTypeChIntstMask               ChIntstMask11;           
  UsbOtgTypeChIntstMask               ChIntstMask12;           
  UsbOtgTypeChIntstMask               ChIntstMask13;           
  UsbOtgTypeChIntstMask               ChIntstMask14;           
  UsbOtgTypeChIntstMask               ChIntstMask15;           
  UsbOtgTypeDebugCtrl                 DbgCtrl;                 
  uint32                              Dbg;                     
  uint32                              MbistTm;                 
  UsbOtgBrtCtl1                       BrtCtl1;                 
  uint32                              BrtCtl2;                 
  uint32                              BrtStat1;                
  uint32                              BrtStat2;                
  UsbOtgUtmiCtl1                      UtmiCtl1;                
  UsbOtgTestPortCtl                   TestPortCtl;             
  UsbOtgPllCtl1                       PllCtl1;                 
  UsbOtgTypeGpio                      Gpio;                    
}  UsbOtgReg;

#endif 



